image: docker:20.10.12

services:
  - name: docker:20.10.12-dind
    command: ["--tls=false"]
    privileged: true

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

build_job:
  stage: build
  script:
    - docker info
    - docker build -t my-app .
