/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Mon May 19 14:11:10 CEST 2025
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif

// Core Global Definitions
char Shared[1155657]; //  size:= 1155657*char
char *const setup_ri_pipeline_0_psf_host_set_up_0__setup_ri_pipeline_0__0 = (char*) (Shared + 0); // setup_ri_pipeline_0_psf_host_set_up_0 > setup_ri_pipeline_0_Broadcast_psf_0 size:= 262144*char
char *const setup_ri_pipeline_0_Broadcast_psf_0__setup_ri_pipeline_0_c__0 = (char*) (Shared + 262144); // setup_ri_pipeline_0_Broadcast_psf_0 > setup_ri_pipeline_0_clean_psf_set_up_0 size:= 262144*char
char *const setup_ri_pipeline_0_Broadcast_psf_0__sink_5_0__0 = (char*) (Shared + 524288); // setup_ri_pipeline_0_Broadcast_psf_0 > sink_5_0 size:= 262144*char
char *const setup_ri_pipeline_0_clean_psf_set_up_0__sink_1_0__0 = (char*) (Shared + 0); // setup_ri_pipeline_0_clean_psf_set_up_0 > sink_1_0 size:= 262144*char
char *const setup_ri_pipeline_0_gains_host_set_up_0__sink_6_0__0 = (char*) (Shared + 786432); // setup_ri_pipeline_0_gains_host_set_up_0 > sink_6_0 size:= 130816*char
char *const setup_ri_pipeline_0_degridding_kernel_host_set_up_0__sink___0 = (char*) (Shared + 917248); // setup_ri_pipeline_0_degridding_kernel_host_set_up_0 > sink_9_0 size:= 108800*char
char *const setup_ri_pipeline_0_kernel_host_set_up_0__sink_4_0__0 = (char*) (Shared + 1026048); // setup_ri_pipeline_0_kernel_host_set_up_0 > sink_4_0 size:= 108800*char
char *const setup_ri_pipeline_0_visibility_host_set_up_0__sink_7_0__0 = (char*) (Shared + 1134848); // setup_ri_pipeline_0_visibility_host_set_up_0 > sink_7_0 size:= 10000*char
char *const setup_ri_pipeline_0_visibility_host_set_up_0__sink_11_0__0 = (char*) (Shared + 1144848); // setup_ri_pipeline_0_visibility_host_set_up_0 > sink_11_0 size:= 10000*char
char *const setup_ri_pipeline_0_gains_host_set_up_0__sink_10_0__0 = (char*) (Shared + 1154848); // setup_ri_pipeline_0_gains_host_set_up_0 > sink_10_0 size:= 512*char
char *const setup_ri_pipeline_0_correction_set_up_0__sink_12_0__0 = (char*) (Shared + 1155360); // setup_ri_pipeline_0_correction_set_up_0 > sink_12_0 size:= 256*char
char *const setup_ri_pipeline_0_degridding_kernel_host_set_up_0__sink___1 = (char*) (Shared + 1155616); // setup_ri_pipeline_0_degridding_kernel_host_set_up_0 > sink_8_0 size:= 17*char
char *const setup_ri_pipeline_0_kernel_host_set_up_0__sink_3_0__0 = (char*) (Shared + 1155633); // setup_ri_pipeline_0_kernel_host_set_up_0 > sink_3_0 size:= 17*char
char *const setup_ri_pipeline_0_psf_host_set_up_0__setup_ri_pipeline_0__1 = (char*) (Shared + 786432); // setup_ri_pipeline_0_psf_host_set_up_0 > setup_ri_pipeline_0_config_struct_set_up_sequel_0 size:= 8*char
char *const setup_ri_pipeline_0_config_struct_set_up_0__setup_ri_pipel__0 = (char*) (Shared + 0); // setup_ri_pipeline_0_config_struct_set_up_0 > setup_ri_pipeline_0_Broadcast_config_prequel_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_prequel_0__setup_ri_p__0 = (char*) (Shared + 786440); // setup_ri_pipeline_0_Broadcast_config_prequel_0 > setup_ri_pipeline_0_config_struct_set_up_sequel_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_prequel_0__setup_ri_p__1 = (char*) (Shared + 262144); // setup_ri_pipeline_0_Broadcast_config_prequel_0 > setup_ri_pipeline_0_psf_host_set_up_0 size:= 1*char
char *const setup_ri_pipeline_0_config_struct_set_up_sequel_0__setup_r__0 = (char*) (Shared + 786441); // setup_ri_pipeline_0_config_struct_set_up_sequel_0 > setup_ri_pipeline_0_Broadcast_config_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_0__setup_ri_pipeline___0 = (char*) (Shared + 1155650); // setup_ri_pipeline_0_Broadcast_config_0 > setup_ri_pipeline_0_clean_psf_set_up_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_0__setup_ri_pipeline___1 = (char*) (Shared + 1155651); // setup_ri_pipeline_0_Broadcast_config_0 > setup_ri_pipeline_0_degridding_kernel_host_set_up_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_0__setup_ri_pipeline___2 = (char*) (Shared + 1155652); // setup_ri_pipeline_0_Broadcast_config_0 > setup_ri_pipeline_0_gains_host_set_up_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_0__setup_ri_pipeline___3 = (char*) (Shared + 1155653); // setup_ri_pipeline_0_Broadcast_config_0 > setup_ri_pipeline_0_visibility_host_set_up_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_0__setup_ri_pipeline___4 = (char*) (Shared + 1155654); // setup_ri_pipeline_0_Broadcast_config_0 > setup_ri_pipeline_0_kernel_host_set_up_0 size:= 1*char
char *const setup_ri_pipeline_0_Broadcast_config_0__sink_0_0__0 = (char*) (Shared + 1155655); // setup_ri_pipeline_0_Broadcast_config_0 > sink_0_0 size:= 1*char
char *const setup_ri_pipeline_0_clean_psf_set_up_0__sink_2_0__0 = (char*) (Shared + 1155656); // setup_ri_pipeline_0_clean_psf_set_up_0 > sink_2_0 size:= 1*char
PRECISION *const psf__input__0 = (PRECISION*) (Shared + 0); // setup_ri_pipeline_0_psf_host_set_up_0_psf > setup_ri_pipeline_0_Broadcast_psf_0_input size:= 262144*PRECISION
PRECISION *const setup_clean_psf_0__dirty_psf__0 = (PRECISION*) (Shared + 262144); // setup_ri_pipeline_0_Broadcast_psf_0_setup_clean_psf_0 > setup_ri_pipeline_0_clean_psf_set_up_0_dirty_psf size:= 262144*PRECISION
PRECISION *const output_1__in__0 = (PRECISION*) (Shared + 524288); // setup_ri_pipeline_0_Broadcast_psf_0_output_1 > sink_5_0_in size:= 262144*PRECISION
PRECISION *const clean_psf__in__0 = (PRECISION*) (Shared + 0); // setup_ri_pipeline_0_clean_psf_set_up_0_clean_psf > sink_1_0_in size:= 262144*PRECISION
int2 *const receiver_pairs__in__0 = (int2*) (Shared + 786432); // setup_ri_pipeline_0_gains_host_set_up_0_receiver_pairs > sink_6_0_in size:= 130816*int2
PRECISION2 *const degridding_kernels__in__0 = (PRECISION2*) (Shared + 917248); // setup_ri_pipeline_0_degridding_kernel_host_set_up_0_degridding_kernels > sink_9_0_in size:= 108800*PRECISION2
PRECISION2 *const kernels__in__0 = (PRECISION2*) (Shared + 1026048); // setup_ri_pipeline_0_kernel_host_set_up_0_kernels > sink_4_0_in size:= 108800*PRECISION2
PRECISION3 *const vis_uvw_coords__in__0 = (PRECISION3*) (Shared + 1134848); // setup_ri_pipeline_0_visibility_host_set_up_0_vis_uvw_coords > sink_7_0_in size:= 10000*PRECISION3
PRECISION2 *const measured_vis__in__0 = (PRECISION2*) (Shared + 1144848); // setup_ri_pipeline_0_visibility_host_set_up_0_measured_vis > sink_11_0_in size:= 10000*PRECISION2
PRECISION2 *const gains__in__0 = (PRECISION2*) (Shared + 1154848); // setup_ri_pipeline_0_gains_host_set_up_0_gains > sink_10_0_in size:= 512*PRECISION2
PRECISION *const prolate__in__0 = (PRECISION*) (Shared + 1155360); // setup_ri_pipeline_0_correction_set_up_0_prolate > sink_12_0_in size:= 256*PRECISION
int2 *const degridding_kernel_supports__in__0 = (int2*) (Shared + 1155616); // setup_ri_pipeline_0_degridding_kernel_host_set_up_0_degridding_kernel_supports > sink_8_0_in size:= 17*int2
int2 *const kernel_supports__in__0 = (int2*) (Shared + 1155633); // setup_ri_pipeline_0_kernel_host_set_up_0_kernel_supports > sink_3_0_in size:= 17*int2
double *const psf_max_value__psf_max_value__0 = (double*) (Shared + 786432); // setup_ri_pipeline_0_psf_host_set_up_0_psf_max_value > setup_ri_pipeline_0_config_struct_set_up_sequel_0_psf_max_value size:= 1*double
Config *const config__input__0 = (Config*) (Shared + 0); // setup_ri_pipeline_0_config_struct_set_up_0_config > setup_ri_pipeline_0_Broadcast_config_prequel_0_input size:= 1*Config
Config *const setup_prequel_0__config_in__0 = (Config*) (Shared + 786440); // setup_ri_pipeline_0_Broadcast_config_prequel_0_setup_prequel_0 > setup_ri_pipeline_0_config_struct_set_up_sequel_0_config_in size:= 1*Config
Config *const setup_psf_1__config__0 = (Config*) (Shared + 262144); // setup_ri_pipeline_0_Broadcast_config_prequel_0_setup_psf_1 > setup_ri_pipeline_0_psf_host_set_up_0_config size:= 1*Config
Config *const config_out__input__0 = (Config*) (Shared + 786441); // setup_ri_pipeline_0_config_struct_set_up_sequel_0_config_out > setup_ri_pipeline_0_Broadcast_config_0_input size:= 1*Config
Config *const setup_clean_psf_0__config__0 = (Config*) (Shared + 1155650); // setup_ri_pipeline_0_Broadcast_config_0_setup_clean_psf_0 > setup_ri_pipeline_0_clean_psf_set_up_0_config size:= 1*Config
Config *const setup_degridding_kernel_2__config__0 = (Config*) (Shared + 1155651); // setup_ri_pipeline_0_Broadcast_config_0_setup_degridding_kernel_2 > setup_ri_pipeline_0_degridding_kernel_host_set_up_0_config size:= 1*Config
Config *const setup_gains_3__config__0 = (Config*) (Shared + 1155652); // setup_ri_pipeline_0_Broadcast_config_0_setup_gains_3 > setup_ri_pipeline_0_gains_host_set_up_0_config size:= 1*Config
Config *const setup_vis_4__config__0 = (Config*) (Shared + 1155653); // setup_ri_pipeline_0_Broadcast_config_0_setup_vis_4 > setup_ri_pipeline_0_visibility_host_set_up_0_config size:= 1*Config
Config *const setup_gridding_kernel_5__config__0 = (Config*) (Shared + 1155654); // setup_ri_pipeline_0_Broadcast_config_0_setup_gridding_kernel_5 > setup_ri_pipeline_0_kernel_host_set_up_0_config size:= 1*Config
Config *const output_1__in__1 = (Config*) (Shared + 1155655); // setup_ri_pipeline_0_Broadcast_config_0_output_1 > sink_0_0_in size:= 1*Config
int2 *const partial_psf_halfdims__in__0 = (int2*) (Shared + 1155656); // setup_ri_pipeline_0_clean_psf_set_up_0_partial_psf_halfdims > sink_2_0_in size:= 1*int2

void* computationThread_Core0(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_prolate__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_prolate__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_output_1__in__1;
	PREESM_MD5_Init(&preesm_md5_ctx_output_1__in__1);
	PREESM_MD5_CTX preesm_md5_ctx_gains__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_gains__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_measured_vis__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_measured_vis__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_kernel_supports__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_kernel_supports__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_kernels__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_kernels__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_receiver_pairs__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_receiver_pairs__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_vis_uvw_coords__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_vis_uvw_coords__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_degridding_kernel_supports__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_degridding_kernel_supports__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_degridding_kernels__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_degridding_kernels__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_output_1__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_output_1__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_clean_psf__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_clean_psf__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_partial_psf_halfdims__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_partial_psf_halfdims__in__0);
#endif
// Initialisation(s)

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    config_struct_set_up(512/*GRID_SIZE*/, 17/*NUM_KERNELS*/, config__input__0); // setup_ri_pipeline_0_config_struct_set_up_0

    correction_set_up(512/*GRID_SIZE*/, prolate__in__0); // setup_ri_pipeline_0_correction_set_up_0

    // Broadcast setup_ri_pipeline_0_Broadcast_config_prequel_0

    {
      // memcpy #0
      memcpy(setup_prequel_0__config_in__0 + 0, config__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(setup_psf_1__config__0 + 0, config__input__0 + 0, 1); // 1 * Config
    }

    sink(prolate__in__0); // sink_12_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_prolate__in__0,(char *)prolate__in__0, 256);
		#endif

    psf_host_set_up(512/*GRID_SIZE*/, 2458/*PSF_GRID_SIZE*/, setup_psf_1__config__0, psf__input__0,
        psf_max_value__psf_max_value__0); // setup_ri_pipeline_0_psf_host_set_up_0

    // Broadcast setup_ri_pipeline_0_Broadcast_psf_0

    {
      // memcpy #0
      memcpy(setup_clean_psf_0__dirty_psf__0 + 0, psf__input__0 + 0, 262144); // 262144 * PRECISION
      // memcpy #0
      memcpy(output_1__in__0 + 0, psf__input__0 + 0, 262144); // 262144 * PRECISION
    }

    config_struct_set_up_sequel(setup_prequel_0__config_in__0, psf_max_value__psf_max_value__0, config_out__input__0); // setup_ri_pipeline_0_config_struct_set_up_sequel_0

    // Broadcast setup_ri_pipeline_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(setup_clean_psf_0__config__0 + 0, config_out__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_1__in__1 + 0, config_out__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(setup_degridding_kernel_2__config__0 + 0, config_out__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(setup_gains_3__config__0 + 0, config_out__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(setup_vis_4__config__0 + 0, config_out__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(setup_gridding_kernel_5__config__0 + 0, config_out__input__0 + 0, 1); // 1 * Config
    }

    degridding_kernel_host_set_up(17/*NUM_DEGRIDDING_KERNELS*/, 108800/*TOTAL_DEGRIDDING_KERNEL_SAMPLES*/,
        setup_degridding_kernel_2__config__0, degridding_kernel_supports__in__0, degridding_kernels__in__0); // setup_ri_pipeline_0_degridding_kernel_host_set_up_0

    gains_host_set_up(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, setup_gains_3__config__0, gains__in__0,
        receiver_pairs__in__0); // setup_ri_pipeline_0_gains_host_set_up_0

    kernel_host_set_up(17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/, setup_gridding_kernel_5__config__0,
        kernel_supports__in__0, kernels__in__0); // setup_ri_pipeline_0_kernel_host_set_up_0

    visibility_host_set_up(10000/*NUM_VISIBILITIES*/, setup_vis_4__config__0, vis_uvw_coords__in__0,
        measured_vis__in__0); // setup_ri_pipeline_0_visibility_host_set_up_0

    sink(output_1__in__1); // sink_0_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_output_1__in__1,(char *)output_1__in__1, 1);
		#endif

    sink(gains__in__0); // sink_10_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_gains__in__0,(char *)gains__in__0, 512);
		#endif

    sink(measured_vis__in__0); // sink_11_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_measured_vis__in__0,(char *)measured_vis__in__0, 10000);
		#endif

    sink(kernel_supports__in__0); // sink_3_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_kernel_supports__in__0,(char *)kernel_supports__in__0, 17);
		#endif

    sink(kernels__in__0); // sink_4_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_kernels__in__0,(char *)kernels__in__0, 108800);
		#endif

    sink(receiver_pairs__in__0); // sink_6_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_receiver_pairs__in__0,(char *)receiver_pairs__in__0, 130816);
		#endif

    sink(vis_uvw_coords__in__0); // sink_7_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_vis_uvw_coords__in__0,(char *)vis_uvw_coords__in__0, 10000);
		#endif

    sink(degridding_kernel_supports__in__0); // sink_8_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_degridding_kernel_supports__in__0,(char *)degridding_kernel_supports__in__0, 17);
		#endif

    sink(degridding_kernels__in__0); // sink_9_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_degridding_kernels__in__0,(char *)degridding_kernels__in__0, 108800);
		#endif

    clean_psf_host_set_up(512/*GRID_SIZE*/, 0/*GAUSSIAN_CLEAN_PSF*/, setup_clean_psf_0__config__0,
        setup_clean_psf_0__dirty_psf__0, clean_psf__in__0, partial_psf_halfdims__in__0); // setup_ri_pipeline_0_clean_psf_set_up_0

    sink(output_1__in__0); // sink_5_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_output_1__in__0,(char *)output_1__in__0, 262144);
		#endif

    sink(clean_psf__in__0); // sink_1_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_clean_psf__in__0,(char *)clean_psf__in__0, 262144);
		#endif

    sink(partial_psf_halfdims__in__0); // sink_2_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_partial_psf_halfdims__in__0,(char *)partial_psf_halfdims__in__0, 1);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_prolate__in__0);
	printf("preesm_md5_prolate__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_output_1__in__1);
	printf("preesm_md5_output_1__in__1 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_gains__in__0);
	printf("preesm_md5_gains__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_measured_vis__in__0);
	printf("preesm_md5_measured_vis__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_kernel_supports__in__0);
	printf("preesm_md5_kernel_supports__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_kernels__in__0);
	printf("preesm_md5_kernels__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_receiver_pairs__in__0);
	printf("preesm_md5_receiver_pairs__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_vis_uvw_coords__in__0);
	printf("preesm_md5_vis_uvw_coords__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_degridding_kernel_supports__in__0);
	printf("preesm_md5_degridding_kernel_supports__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_degridding_kernels__in__0);
	printf("preesm_md5_degridding_kernels__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_output_1__in__0);
	printf("preesm_md5_output_1__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_clean_psf__in__0);
	printf("preesm_md5_clean_psf__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_partial_psf_halfdims__in__0);
	printf("preesm_md5_partial_psf_halfdims__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

