/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Mon May 19 22:05:12 CEST 2025
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif

// Core Global Definitions
char Shared[11811285273]; //  size:= 11811285273*char
char *const delta_0_implode_delta_0_merge_grids_0_grids__delta_0_merge__0 = (char*) (Shared + 0); // delta_0_implode_delta_0_merge_grids_0_grids > delta_0_merge_grids_0 size:= 4294967296*char
char *const src_0_0__delta_0_image_passthrough_0__0 = (char*) (Shared + 4294967296); // src_0_0 > delta_0_image_passthrough_0 size:= 1073741824*char
char *const src_10_0__delta_0_psf_sink_0__0 = (char*) (Shared + 5368709120); // src_10_0 > delta_0_psf_sink_0 size:= 1073741824*char
char *const delta_0_image_passthrough_0__sink_1_0__0 = (char*) (Shared + 6442450944); // delta_0_image_passthrough_0 > sink_1_0 size:= 1073741824*char
char *const delta_0_gridding_run_0_gridding_actor_0__delta_0_implode_d__0 = (char*) (Shared + 7516192768); // delta_0_gridding_run_0_gridding_actor_0 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_gridding_run_1_gridding_actor_0__delta_0_implode_d__0 = (char*) (Shared + 8589934592); // delta_0_gridding_run_1_gridding_actor_0 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_gridding_run_2_gridding_actor_0__delta_0_implode_d__0 = (char*) (Shared + 9663676416); // delta_0_gridding_run_2_gridding_actor_0 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_gridding_run_3_gridding_actor_0__delta_0_implode_d__0 = (char*) (Shared + 10737418240); // delta_0_gridding_run_3_gridding_actor_0 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_merge_grids_0__delta_0_ifft_run_0_fft_shift_comple__0 = (char*) (Shared + 7516192768); // delta_0_merge_grids_0 > delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0__d__0 = (char*) (Shared + 0); // delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0 > delta_0_ifft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 size:= 1073741824*char
char *const delta_0_ifft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0__delt__0 = (char*) (Shared + 1073741824); // delta_0_ifft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 > delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0 size:= 1073741824*char
char *const delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0__delt__0 = (char*) (Shared + 0); // delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 1073741824*char
char *const delta_0_convolution_correction_run_0_execute_convolution_c__0 = (char*) (Shared + 1073741824); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 > sink_0_0 size:= 1073741824*char
char *const src_1_0__delta_0_split_vis_0__0 = (char*) (Shared + 0);  // src_1_0 > delta_0_split_vis_0 size:= 981120*char
char *const src_6_0__delta_0_split_vis_0__0 = (char*) (Shared + 981120); // src_6_0 > delta_0_split_vis_0 size:= 981120*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_v__0 = (char*) (Shared + 1962240); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_visibilities size:= 981120*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_o__0 = (char*) (Shared + 2943360); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_out_vis_coords size:= 981120*char
char *const delta_0_explode_delta_0_split_vis_0_visibilities__delta_0___0 = (char*) (Shared + 0); // delta_0_explode_delta_0_split_vis_0_visibilities > delta_0_subtraction_run_0_subtraction_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_visibilities__delta_0___1 = (char*) (Shared + 245280); // delta_0_explode_delta_0_split_vis_0_visibilities > delta_0_subtraction_run_1_subtraction_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_visibilities__delta_0___2 = (char*) (Shared + 490560); // delta_0_explode_delta_0_split_vis_0_visibilities > delta_0_subtraction_run_2_subtraction_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_visibilities__delta_0___3 = (char*) (Shared + 735840); // delta_0_explode_delta_0_split_vis_0_visibilities > delta_0_subtraction_run_3_subtraction_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___0 = (char*) (Shared + 981120); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_broadcast_vis_coords_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___1 = (char*) (Shared + 1226400); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_broadcast_vis_coords_1 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___2 = (char*) (Shared + 1471680); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_broadcast_vis_coords_2 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___3 = (char*) (Shared + 1716960); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_broadcast_vis_coords_3 size:= 245280*char
char *const delta_0_broadcast_vis_coords_0__delta_0_dft_run_0_dft_acto__0 = (char*) (Shared + 2943360); // delta_0_broadcast_vis_coords_0 > delta_0_dft_run_0_dft_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_0__delta_0_gridding_run_0_gri__0 = (char*) (Shared + 3188640); // delta_0_broadcast_vis_coords_0 > delta_0_gridding_run_0_gridding_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_1__delta_0_dft_run_1_dft_acto__0 = (char*) (Shared + 3433920); // delta_0_broadcast_vis_coords_1 > delta_0_dft_run_1_dft_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_1__delta_0_gridding_run_1_gri__0 = (char*) (Shared + 3679200); // delta_0_broadcast_vis_coords_1 > delta_0_gridding_run_1_gridding_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_2__delta_0_dft_run_2_dft_acto__0 = (char*) (Shared + 3924480); // delta_0_broadcast_vis_coords_2 > delta_0_dft_run_2_dft_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_2__delta_0_gridding_run_2_gri__0 = (char*) (Shared + 4169760); // delta_0_broadcast_vis_coords_2 > delta_0_gridding_run_2_gridding_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_3__delta_0_dft_run_3_dft_acto__0 = (char*) (Shared + 4415040); // delta_0_broadcast_vis_coords_3 > delta_0_dft_run_3_dft_actor_0 size:= 245280*char
char *const delta_0_broadcast_vis_coords_3__delta_0_gridding_run_3_gri__0 = (char*) (Shared + 4660320); // delta_0_broadcast_vis_coords_3 > delta_0_gridding_run_3_gridding_actor_0 size:= 245280*char
char *const delta_0_dft_run_0_dft_actor_0__delta_0_add_visibilities_0__0 = (char*) (Shared + 981120); // delta_0_dft_run_0_dft_actor_0 > delta_0_add_visibilities_0 size:= 245280*char
char *const delta_0_dft_run_1_dft_actor_0__delta_0_add_visibilities_1__0 = (char*) (Shared + 1226400); // delta_0_dft_run_1_dft_actor_0 > delta_0_add_visibilities_1 size:= 245280*char
char *const delta_0_dft_run_2_dft_actor_0__delta_0_add_visibilities_2__0 = (char*) (Shared + 1471680); // delta_0_dft_run_2_dft_actor_0 > delta_0_add_visibilities_2 size:= 245280*char
char *const delta_0_dft_run_3_dft_actor_0__delta_0_add_visibilities_3__0 = (char*) (Shared + 1716960); // delta_0_dft_run_3_dft_actor_0 > delta_0_add_visibilities_3 size:= 245280*char
char *const delta_0_add_visibilities_0__delta_0_subtraction_run_0_subt__0 = (char*) (Shared + 2943360); // delta_0_add_visibilities_0 > delta_0_subtraction_run_0_subtraction_0 size:= 245280*char
char *const delta_0_add_visibilities_1__delta_0_subtraction_run_1_subt__0 = (char*) (Shared + 3433920); // delta_0_add_visibilities_1 > delta_0_subtraction_run_1_subtraction_0 size:= 245280*char
char *const delta_0_add_visibilities_2__delta_0_subtraction_run_2_subt__0 = (char*) (Shared + 3924480); // delta_0_add_visibilities_2 > delta_0_subtraction_run_2_subtraction_0 size:= 245280*char
char *const delta_0_add_visibilities_3__delta_0_subtraction_run_3_subt__0 = (char*) (Shared + 4415040); // delta_0_add_visibilities_3 > delta_0_subtraction_run_3_subtraction_0 size:= 245280*char
char *const delta_0_subtraction_run_0_subtraction_0__delta_0_gridding___0 = (char*) (Shared + 981120); // delta_0_subtraction_run_0_subtraction_0 > delta_0_gridding_run_0_gridding_actor_0 size:= 245280*char
char *const delta_0_subtraction_run_1_subtraction_0__delta_0_gridding___0 = (char*) (Shared + 1226400); // delta_0_subtraction_run_1_subtraction_0 > delta_0_gridding_run_1_gridding_actor_0 size:= 245280*char
char *const delta_0_subtraction_run_2_subtraction_0__delta_0_gridding___0 = (char*) (Shared + 1471680); // delta_0_subtraction_run_2_subtraction_0 > delta_0_gridding_run_2_gridding_actor_0 size:= 245280*char
char *const delta_0_subtraction_run_3_subtraction_0__delta_0_gridding___0 = (char*) (Shared + 1716960); // delta_0_subtraction_run_3_subtraction_0 > delta_0_gridding_run_3_gridding_actor_0 size:= 245280*char
char *const src_8_0__BR_delta_0__receiver_pairs__0 = (char*) (Shared + 4905600); // src_8_0 > BR_delta_0__receiver_pairs size:= 130816*char
char *const BR_delta_0__receiver_pairs__delta_0_subtraction_run_0_subt__0 = (char*) (Shared + 5036416); // BR_delta_0__receiver_pairs > delta_0_subtraction_run_0_subtraction_0 size:= 130816*char
char *const BR_delta_0__receiver_pairs__delta_0_subtraction_run_1_subt__0 = (char*) (Shared + 5167232); // BR_delta_0__receiver_pairs > delta_0_subtraction_run_1_subtraction_0 size:= 130816*char
char *const BR_delta_0__receiver_pairs__delta_0_subtraction_run_2_subt__0 = (char*) (Shared + 5298048); // BR_delta_0__receiver_pairs > delta_0_subtraction_run_2_subtraction_0 size:= 130816*char
char *const BR_delta_0__receiver_pairs__delta_0_subtraction_run_3_subt__0 = (char*) (Shared + 5428864); // BR_delta_0__receiver_pairs > delta_0_subtraction_run_3_subtraction_0 size:= 130816*char
char *const src_5_0__BR_delta_0__gridding_kernels__0 = (char*) (Shared + 5559680); // src_5_0 > BR_delta_0__gridding_kernels size:= 108800*char
char *const src_14_0__delta_0_degridding_kernel_sink_0__0 = (char*) (Shared + 11811160064); // src_14_0 > delta_0_degridding_kernel_sink_0 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_gridding_run_0_gridd__0 = (char*) (Shared + 5668480); // BR_delta_0__gridding_kernels > delta_0_gridding_run_0_gridding_actor_0 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_gridding_run_1_gridd__0 = (char*) (Shared + 5777280); // BR_delta_0__gridding_kernels > delta_0_gridding_run_1_gridding_actor_0 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_gridding_run_2_gridd__0 = (char*) (Shared + 5886080); // BR_delta_0__gridding_kernels > delta_0_gridding_run_2_gridding_actor_0 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_gridding_run_3_gridd__0 = (char*) (Shared + 5994880); // BR_delta_0__gridding_kernels > delta_0_gridding_run_3_gridding_actor_0 size:= 108800*char
char *const src_11_0__delta_0_convolution_correction_run_0_execute_con__0 = (char*) (Shared + 11811268864); // src_11_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 16384*char
char *const src_7_0__BR_delta_0__gains__0 = (char*) (Shared + 6103680);  // src_7_0 > BR_delta_0__gains size:= 512*char
char *const BR_delta_0__gains__delta_0_subtraction_run_0_reciprocal_tr__0 = (char*) (Shared + 6104192); // BR_delta_0__gains > delta_0_subtraction_run_0_reciprocal_transform_actor_0 size:= 512*char
char *const BR_delta_0__gains__delta_0_subtraction_run_1_reciprocal_tr__0 = (char*) (Shared + 6104704); // BR_delta_0__gains > delta_0_subtraction_run_1_reciprocal_transform_actor_0 size:= 512*char
char *const BR_delta_0__gains__delta_0_subtraction_run_2_reciprocal_tr__0 = (char*) (Shared + 6105216); // BR_delta_0__gains > delta_0_subtraction_run_2_reciprocal_transform_actor_0 size:= 512*char
char *const BR_delta_0__gains__delta_0_subtraction_run_3_reciprocal_tr__0 = (char*) (Shared + 6105728); // BR_delta_0__gains > delta_0_subtraction_run_3_reciprocal_transform_actor_0 size:= 512*char
char *const delta_0_subtraction_run_0_reciprocal_transform_actor_0__de__0 = (char*) (Shared + 6103680); // delta_0_subtraction_run_0_reciprocal_transform_actor_0 > delta_0_subtraction_run_0_subtraction_0 size:= 512*char
char *const delta_0_subtraction_run_1_reciprocal_transform_actor_0__de__0 = (char*) (Shared + 6106240); // delta_0_subtraction_run_1_reciprocal_transform_actor_0 > delta_0_subtraction_run_1_subtraction_0 size:= 512*char
char *const delta_0_subtraction_run_2_reciprocal_transform_actor_0__de__0 = (char*) (Shared + 6106752); // delta_0_subtraction_run_2_reciprocal_transform_actor_0 > delta_0_subtraction_run_2_subtraction_0 size:= 512*char
char *const delta_0_subtraction_run_3_reciprocal_transform_actor_0__de__0 = (char*) (Shared + 6107264); // delta_0_subtraction_run_3_reciprocal_transform_actor_0 > delta_0_subtraction_run_3_subtraction_0 size:= 512*char
char *const src_2_0__BR_delta_0__source_list__0 = (char*) (Shared + 6107776); // src_2_0 > BR_delta_0__source_list size:= 200*char
char *const BR_delta_0__source_list__delta_0_dft_run_0_dft_actor_0__0 = (char*) (Shared + 6107976); // BR_delta_0__source_list > delta_0_dft_run_0_dft_actor_0 size:= 200*char
char *const BR_delta_0__source_list__delta_0_dft_run_1_dft_actor_0__0 = (char*) (Shared + 6108176); // BR_delta_0__source_list > delta_0_dft_run_1_dft_actor_0 size:= 200*char
char *const BR_delta_0__source_list__delta_0_dft_run_2_dft_actor_0__0 = (char*) (Shared + 6108376); // BR_delta_0__source_list > delta_0_dft_run_2_dft_actor_0 size:= 200*char
char *const BR_delta_0__source_list__delta_0_dft_run_3_dft_actor_0__0 = (char*) (Shared + 6108576); // BR_delta_0__source_list > delta_0_dft_run_3_dft_actor_0 size:= 200*char
char *const src_4_0__BR_delta_0__gridding_kernel_supports__0 = (char*) (Shared + 6108776); // src_4_0 > BR_delta_0__gridding_kernel_supports size:= 17*char
char *const src_13_0__delta_0_degridding_kernel_sink_0__0 = (char*) (Shared + 11811285248); // src_13_0 > delta_0_degridding_kernel_sink_0 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_gridding_run__0 = (char*) (Shared + 6108793); // BR_delta_0__gridding_kernel_supports > delta_0_gridding_run_0_gridding_actor_0 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_gridding_run__1 = (char*) (Shared + 6108810); // BR_delta_0__gridding_kernel_supports > delta_0_gridding_run_1_gridding_actor_0 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_gridding_run__2 = (char*) (Shared + 6108827); // BR_delta_0__gridding_kernel_supports > delta_0_gridding_run_2_gridding_actor_0 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_gridding_run__3 = (char*) (Shared + 6108844); // BR_delta_0__gridding_kernel_supports > delta_0_gridding_run_3_gridding_actor_0 size:= 17*char
char *const src_3_0__BR_delta_0__num_sources_in__0 = (char*) (Shared + 6108861); // src_3_0 > BR_delta_0__num_sources_in size:= 4*char
char *const src_12_0__delta_0_token_sink_0__0 = (char*) (Shared + 11811285265); // src_12_0 > delta_0_token_sink_0 size:= 4*char
char *const BR_delta_0__num_sources_in__delta_0_dft_run_0_dft_actor_0__0 = (char*) (Shared + 6108865); // BR_delta_0__num_sources_in > delta_0_dft_run_0_dft_actor_0 size:= 4*char
char *const BR_delta_0__num_sources_in__delta_0_dft_run_1_dft_actor_0__0 = (char*) (Shared + 6108869); // BR_delta_0__num_sources_in > delta_0_dft_run_1_dft_actor_0 size:= 4*char
char *const BR_delta_0__num_sources_in__delta_0_dft_run_2_dft_actor_0__0 = (char*) (Shared + 6108873); // BR_delta_0__num_sources_in > delta_0_dft_run_2_dft_actor_0 size:= 4*char
char *const BR_delta_0__num_sources_in__delta_0_dft_run_3_dft_actor_0__0 = (char*) (Shared + 6108877); // BR_delta_0__num_sources_in > delta_0_dft_run_3_dft_actor_0 size:= 4*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_o__1 = (char*) (Shared + 6106240); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_output_configs size:= 4*char
char *const src_9_0__delta_0_split_vis_0__0 = (char*) (Shared + 3924480); // src_9_0 > delta_0_split_vis_0 size:= 1*char
char *const delta_0_split_vis_0__delta_0_Broadcast_singular_config_0__0 = (char*) (Shared + 11811285269); // delta_0_split_vis_0 > delta_0_Broadcast_singular_config_0 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___0 = (char*) (Shared + 6108881); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_broadcast_config_0 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___1 = (char*) (Shared + 6106244); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_broadcast_config_1 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___2 = (char*) (Shared + 6106752); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_broadcast_config_2 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___3 = (char*) (Shared + 6107264); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_broadcast_config_3 size:= 1*char
char *const delta_0_Broadcast_singular_config_0__delta_0_ifft_run_0_Br__0 = (char*) (Shared + 11811285270); // delta_0_Broadcast_singular_config_0 > delta_0_ifft_run_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_singular_config_0__delta_0_convolution_c__0 = (char*) (Shared + 11811285271); // delta_0_Broadcast_singular_config_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 1*char
char *const delta_0_broadcast_config_0__delta_0_dft_run_0_dft_actor_0__0 = (char*) (Shared + 6108882); // delta_0_broadcast_config_0 > delta_0_dft_run_0_dft_actor_0 size:= 1*char
char *const delta_0_broadcast_config_0__delta_0_subtraction_run_0_Broa__0 = (char*) (Shared + 6108883); // delta_0_broadcast_config_0 > delta_0_subtraction_run_0_Broadcast_config_0 size:= 1*char
char *const delta_0_broadcast_config_0__delta_0_gridding_run_0_griddin__0 = (char*) (Shared + 6108884); // delta_0_broadcast_config_0 > delta_0_gridding_run_0_gridding_actor_0 size:= 1*char
char *const delta_0_broadcast_config_1__delta_0_dft_run_1_dft_actor_0__0 = (char*) (Shared + 6108885); // delta_0_broadcast_config_1 > delta_0_dft_run_1_dft_actor_0 size:= 1*char
char *const delta_0_broadcast_config_1__delta_0_subtraction_run_1_Broa__0 = (char*) (Shared + 6106240); // delta_0_broadcast_config_1 > delta_0_subtraction_run_1_Broadcast_config_0 size:= 1*char
char *const delta_0_broadcast_config_1__delta_0_gridding_run_1_griddin__0 = (char*) (Shared + 6108886); // delta_0_broadcast_config_1 > delta_0_gridding_run_1_gridding_actor_0 size:= 1*char
char *const delta_0_broadcast_config_2__delta_0_dft_run_2_dft_actor_0__0 = (char*) (Shared + 6108887); // delta_0_broadcast_config_2 > delta_0_dft_run_2_dft_actor_0 size:= 1*char
char *const delta_0_broadcast_config_2__delta_0_subtraction_run_2_Broa__0 = (char*) (Shared + 6106753); // delta_0_broadcast_config_2 > delta_0_subtraction_run_2_Broadcast_config_0 size:= 1*char
char *const delta_0_broadcast_config_2__delta_0_gridding_run_2_griddin__0 = (char*) (Shared + 6108888); // delta_0_broadcast_config_2 > delta_0_gridding_run_2_gridding_actor_0 size:= 1*char
char *const delta_0_broadcast_config_3__delta_0_dft_run_3_dft_actor_0__0 = (char*) (Shared + 6108889); // delta_0_broadcast_config_3 > delta_0_dft_run_3_dft_actor_0 size:= 1*char
char *const delta_0_broadcast_config_3__delta_0_subtraction_run_3_Broa__0 = (char*) (Shared + 6107265); // delta_0_broadcast_config_3 > delta_0_subtraction_run_3_Broadcast_config_0 size:= 1*char
char *const delta_0_broadcast_config_3__delta_0_gridding_run_3_griddin__0 = (char*) (Shared + 6108890); // delta_0_broadcast_config_3 > delta_0_gridding_run_3_gridding_actor_0 size:= 1*char
char *const delta_0_ifft_run_0_Broadcast_config_0__delta_0_ifft_run_0___0 = (char*) (Shared + 11811285269); // delta_0_ifft_run_0_Broadcast_config_0 > delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1*char
char *const delta_0_ifft_run_0_Broadcast_config_0__delta_0_ifft_run_0___1 = (char*) (Shared + 11811285272); // delta_0_ifft_run_0_Broadcast_config_0 > delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0 size:= 1*char
char *const delta_0_subtraction_run_0_Broadcast_config_0__delta_0_subt__0 = (char*) (Shared + 6108881); // delta_0_subtraction_run_0_Broadcast_config_0 > delta_0_subtraction_run_0_reciprocal_transform_actor_0 size:= 1*char
char *const delta_0_subtraction_run_0_Broadcast_config_0__delta_0_subt__1 = (char*) (Shared + 6108891); // delta_0_subtraction_run_0_Broadcast_config_0 > delta_0_subtraction_run_0_subtraction_0 size:= 1*char
char *const delta_0_subtraction_run_1_Broadcast_config_0__delta_0_subt__0 = (char*) (Shared + 6108892); // delta_0_subtraction_run_1_Broadcast_config_0 > delta_0_subtraction_run_1_reciprocal_transform_actor_0 size:= 1*char
char *const delta_0_subtraction_run_1_Broadcast_config_0__delta_0_subt__1 = (char*) (Shared + 6108893); // delta_0_subtraction_run_1_Broadcast_config_0 > delta_0_subtraction_run_1_subtraction_0 size:= 1*char
char *const delta_0_subtraction_run_2_Broadcast_config_0__delta_0_subt__0 = (char*) (Shared + 6108894); // delta_0_subtraction_run_2_Broadcast_config_0 > delta_0_subtraction_run_2_reciprocal_transform_actor_0 size:= 1*char
char *const delta_0_subtraction_run_2_Broadcast_config_0__delta_0_subt__1 = (char*) (Shared + 6108895); // delta_0_subtraction_run_2_Broadcast_config_0 > delta_0_subtraction_run_2_subtraction_0 size:= 1*char
char *const delta_0_subtraction_run_3_Broadcast_config_0__delta_0_subt__0 = (char*) (Shared + 6108896); // delta_0_subtraction_run_3_Broadcast_config_0 > delta_0_subtraction_run_3_reciprocal_transform_actor_0 size:= 1*char
char *const delta_0_subtraction_run_3_Broadcast_config_0__delta_0_subt__1 = (char*) (Shared + 6108897); // delta_0_subtraction_run_3_Broadcast_config_0 > delta_0_subtraction_run_3_subtraction_0 size:= 1*char
PRECISION2 *const uv_grid__grids__0 = (PRECISION2*) (Shared + 0); // delta_0_implode_delta_0_merge_grids_0_grids_uv_grid > delta_0_merge_grids_0_grids size:= 4294967296*PRECISION2
PRECISION *const out__image__0 = (PRECISION*) (Shared + 4294967296); // src_0_0_out > delta_0_image_passthrough_0_image size:= 1073741824*PRECISION
PRECISION *const out__psf__0 = (PRECISION*) (Shared + 5368709120); // src_10_0_out > delta_0_psf_sink_0_psf size:= 1073741824*PRECISION
PRECISION *const output_image__in__0 = (PRECISION*) (Shared + 6442450944); // delta_0_image_passthrough_0_output_image > sink_1_0_in size:= 1073741824*PRECISION
PRECISION2 *const uv_grid__grids_0__0 = (PRECISION2*) (Shared + 7516192768); // delta_0_gridding_run_0_gridding_actor_0_uv_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_0 size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid__grids_1__0 = (PRECISION2*) (Shared + 8589934592); // delta_0_gridding_run_1_gridding_actor_0_uv_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_1 size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid__grids_2__0 = (PRECISION2*) (Shared + 9663676416); // delta_0_gridding_run_2_gridding_actor_0_uv_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_2 size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid__grids_3__0 = (PRECISION2*) (Shared + 10737418240); // delta_0_gridding_run_3_gridding_actor_0_uv_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_3 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__uv_grid_in__0 = (PRECISION2*) (Shared + 7516192768); // delta_0_merge_grids_0_output_grid > delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid_in__0 = (PRECISION2*) (Shared + 0); // delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_out > delta_0_ifft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_ifft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_out > delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0_uv_grid size:= 1073741824*PRECISION2
PRECISION *const dirty_image__dirty_image_in__0 = (PRECISION*) (Shared + 0); // delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0_dirty_image > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_dirty_image_in size:= 1073741824*PRECISION
PRECISION *const dirty_image_out__in__0 = (PRECISION*) (Shared + 1073741824); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_dirty_image_out > sink_0_0_in size:= 1073741824*PRECISION
PRECISION2 *const out__measured_visibilities__0 = (PRECISION2*) (Shared + 0); // src_1_0_out > delta_0_split_vis_0_measured_visibilities size:= 981120*PRECISION2
PRECISION3 *const out__vis_coords__0 = (PRECISION3*) (Shared + 981120); // src_6_0_out > delta_0_split_vis_0_vis_coords size:= 981120*PRECISION3
PRECISION2 *const visibilities__measured_vis__0 = (PRECISION2*) (Shared + 1962240); // delta_0_split_vis_0_visibilities > delta_0_explode_delta_0_split_vis_0_visibilities_measured_vis size:= 981120*PRECISION2
PRECISION3 *const out_vis_coords__input__0 = (PRECISION3*) (Shared + 2943360); // delta_0_split_vis_0_out_vis_coords > delta_0_explode_delta_0_split_vis_0_out_vis_coords_input size:= 981120*PRECISION3
PRECISION2 *const visibilities_0__measured_vis__0 = (PRECISION2*) (Shared + 0); // delta_0_explode_delta_0_split_vis_0_visibilities_visibilities_0 > delta_0_subtraction_run_0_subtraction_0_measured_vis size:= 245280*PRECISION2
PRECISION2 *const visibilities_1__measured_vis__0 = (PRECISION2*) (Shared + 245280); // delta_0_explode_delta_0_split_vis_0_visibilities_visibilities_1 > delta_0_subtraction_run_1_subtraction_0_measured_vis size:= 245280*PRECISION2
PRECISION2 *const visibilities_2__measured_vis__0 = (PRECISION2*) (Shared + 490560); // delta_0_explode_delta_0_split_vis_0_visibilities_visibilities_2 > delta_0_subtraction_run_2_subtraction_0_measured_vis size:= 245280*PRECISION2
PRECISION2 *const visibilities_3__measured_vis__0 = (PRECISION2*) (Shared + 735840); // delta_0_explode_delta_0_split_vis_0_visibilities_visibilities_3 > delta_0_subtraction_run_3_subtraction_0_measured_vis size:= 245280*PRECISION2
PRECISION3 *const out_vis_coords_0__input__0 = (PRECISION3*) (Shared + 981120); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_0 > delta_0_broadcast_vis_coords_0_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_1__input__0 = (PRECISION3*) (Shared + 1226400); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_1 > delta_0_broadcast_vis_coords_1_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_2__input__0 = (PRECISION3*) (Shared + 1471680); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_2 > delta_0_broadcast_vis_coords_2_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_3__input__0 = (PRECISION3*) (Shared + 1716960); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_3 > delta_0_broadcast_vis_coords_3_input size:= 245280*PRECISION3
PRECISION3 *const output_dft_0__vis_uvw_coords__0 = (PRECISION3*) (Shared + 2943360); // delta_0_broadcast_vis_coords_0_output_dft_0 > delta_0_dft_run_0_dft_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_gridding_1__vis_uvw_coords__0 = (PRECISION3*) (Shared + 3188640); // delta_0_broadcast_vis_coords_0_output_gridding_1 > delta_0_gridding_run_0_gridding_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_dft_0__vis_uvw_coords__1 = (PRECISION3*) (Shared + 3433920); // delta_0_broadcast_vis_coords_1_output_dft_0 > delta_0_dft_run_1_dft_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_gridding_1__vis_uvw_coords__1 = (PRECISION3*) (Shared + 3679200); // delta_0_broadcast_vis_coords_1_output_gridding_1 > delta_0_gridding_run_1_gridding_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_dft_0__vis_uvw_coords__2 = (PRECISION3*) (Shared + 3924480); // delta_0_broadcast_vis_coords_2_output_dft_0 > delta_0_dft_run_2_dft_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_gridding_1__vis_uvw_coords__2 = (PRECISION3*) (Shared + 4169760); // delta_0_broadcast_vis_coords_2_output_gridding_1 > delta_0_gridding_run_2_gridding_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_dft_0__vis_uvw_coords__3 = (PRECISION3*) (Shared + 4415040); // delta_0_broadcast_vis_coords_3_output_dft_0 > delta_0_dft_run_3_dft_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const output_gridding_1__vis_uvw_coords__3 = (PRECISION3*) (Shared + 4660320); // delta_0_broadcast_vis_coords_3_output_gridding_1 > delta_0_gridding_run_3_gridding_actor_0_vis_uvw_coords size:= 245280*PRECISION3
PRECISION2 *const visibilities__v2__0 = (PRECISION2*) (Shared + 981120); // delta_0_dft_run_0_dft_actor_0_visibilities > delta_0_add_visibilities_0_v2 size:= 245280*PRECISION2
PRECISION2 *const visibilities__v2__1 = (PRECISION2*) (Shared + 1226400); // delta_0_dft_run_1_dft_actor_0_visibilities > delta_0_add_visibilities_1_v2 size:= 245280*PRECISION2
PRECISION2 *const visibilities__v2__2 = (PRECISION2*) (Shared + 1471680); // delta_0_dft_run_2_dft_actor_0_visibilities > delta_0_add_visibilities_2_v2 size:= 245280*PRECISION2
PRECISION2 *const visibilities__v2__3 = (PRECISION2*) (Shared + 1716960); // delta_0_dft_run_3_dft_actor_0_visibilities > delta_0_add_visibilities_3_v2 size:= 245280*PRECISION2
PRECISION2 *const output__visibilities_in__0 = (PRECISION2*) (Shared + 2943360); // delta_0_add_visibilities_0_output > delta_0_subtraction_run_0_subtraction_0_visibilities_in size:= 245280*PRECISION2
PRECISION2 *const output__visibilities_in__1 = (PRECISION2*) (Shared + 3433920); // delta_0_add_visibilities_1_output > delta_0_subtraction_run_1_subtraction_0_visibilities_in size:= 245280*PRECISION2
PRECISION2 *const output__visibilities_in__2 = (PRECISION2*) (Shared + 3924480); // delta_0_add_visibilities_2_output > delta_0_subtraction_run_2_subtraction_0_visibilities_in size:= 245280*PRECISION2
PRECISION2 *const output__visibilities_in__3 = (PRECISION2*) (Shared + 4415040); // delta_0_add_visibilities_3_output > delta_0_subtraction_run_3_subtraction_0_visibilities_in size:= 245280*PRECISION2
PRECISION2 *const visibilities_out__visibilities__0 = (PRECISION2*) (Shared + 981120); // delta_0_subtraction_run_0_subtraction_0_visibilities_out > delta_0_gridding_run_0_gridding_actor_0_visibilities size:= 245280*PRECISION2
PRECISION2 *const visibilities_out__visibilities__1 = (PRECISION2*) (Shared + 1226400); // delta_0_subtraction_run_1_subtraction_0_visibilities_out > delta_0_gridding_run_1_gridding_actor_0_visibilities size:= 245280*PRECISION2
PRECISION2 *const visibilities_out__visibilities__2 = (PRECISION2*) (Shared + 1471680); // delta_0_subtraction_run_2_subtraction_0_visibilities_out > delta_0_gridding_run_2_gridding_actor_0_visibilities size:= 245280*PRECISION2
PRECISION2 *const visibilities_out__visibilities__3 = (PRECISION2*) (Shared + 1716960); // delta_0_subtraction_run_3_subtraction_0_visibilities_out > delta_0_gridding_run_3_gridding_actor_0_visibilities size:= 245280*PRECISION2
int2 *const out__receiver_pairs__0 = (int2*) (Shared + 4905600); // src_8_0_out > BR_delta_0__receiver_pairs_receiver_pairs size:= 130816*int2
int2 *const receiver_pairs_0_3__receiver_pairs__0 = (int2*) (Shared + 5036416); // BR_delta_0__receiver_pairs_receiver_pairs_0_3 > delta_0_subtraction_run_0_subtraction_0_receiver_pairs size:= 130816*int2
int2 *const receiver_pairs_1_3__receiver_pairs__0 = (int2*) (Shared + 5167232); // BR_delta_0__receiver_pairs_receiver_pairs_1_3 > delta_0_subtraction_run_1_subtraction_0_receiver_pairs size:= 130816*int2
int2 *const receiver_pairs_2_3__receiver_pairs__0 = (int2*) (Shared + 5298048); // BR_delta_0__receiver_pairs_receiver_pairs_2_3 > delta_0_subtraction_run_2_subtraction_0_receiver_pairs size:= 130816*int2
int2 *const receiver_pairs_3_3__receiver_pairs__0 = (int2*) (Shared + 5428864); // BR_delta_0__receiver_pairs_receiver_pairs_3_3 > delta_0_subtraction_run_3_subtraction_0_receiver_pairs size:= 130816*int2
PRECISION2 *const out__gridding_kernels__0 = (PRECISION2*) (Shared + 5559680); // src_5_0_out > BR_delta_0__gridding_kernels_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const out__kernels__0 = (PRECISION2*) (Shared + 11811160064); // src_14_0_out > delta_0_degridding_kernel_sink_0_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_0_3__kernels__0 = (PRECISION2*) (Shared + 5668480); // BR_delta_0__gridding_kernels_gridding_kernels_0_3 > delta_0_gridding_run_0_gridding_actor_0_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_1_3__kernels__0 = (PRECISION2*) (Shared + 5777280); // BR_delta_0__gridding_kernels_gridding_kernels_1_3 > delta_0_gridding_run_1_gridding_actor_0_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_2_3__kernels__0 = (PRECISION2*) (Shared + 5886080); // BR_delta_0__gridding_kernels_gridding_kernels_2_3 > delta_0_gridding_run_2_gridding_actor_0_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_3_3__kernels__0 = (PRECISION2*) (Shared + 5994880); // BR_delta_0__gridding_kernels_gridding_kernels_3_3 > delta_0_gridding_run_3_gridding_actor_0_kernels size:= 108800*PRECISION2
PRECISION *const out__prolate__0 = (PRECISION*) (Shared + 11811268864); // src_11_0_out > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_prolate size:= 16384*PRECISION
PRECISION2 *const out__gains__0 = (PRECISION2*) (Shared + 6103680); // src_7_0_out > BR_delta_0__gains_gains size:= 512*PRECISION2
PRECISION2 *const gains_0_3__gains_in__0 = (PRECISION2*) (Shared + 6104192); // BR_delta_0__gains_gains_0_3 > delta_0_subtraction_run_0_reciprocal_transform_actor_0_gains_in size:= 512*PRECISION2
PRECISION2 *const gains_1_3__gains_in__0 = (PRECISION2*) (Shared + 6104704); // BR_delta_0__gains_gains_1_3 > delta_0_subtraction_run_1_reciprocal_transform_actor_0_gains_in size:= 512*PRECISION2
PRECISION2 *const gains_2_3__gains_in__0 = (PRECISION2*) (Shared + 6105216); // BR_delta_0__gains_gains_2_3 > delta_0_subtraction_run_2_reciprocal_transform_actor_0_gains_in size:= 512*PRECISION2
PRECISION2 *const gains_3_3__gains_in__0 = (PRECISION2*) (Shared + 6105728); // BR_delta_0__gains_gains_3_3 > delta_0_subtraction_run_3_reciprocal_transform_actor_0_gains_in size:= 512*PRECISION2
PRECISION2 *const gains_out__gains__0 = (PRECISION2*) (Shared + 6103680); // delta_0_subtraction_run_0_reciprocal_transform_actor_0_gains_out > delta_0_subtraction_run_0_subtraction_0_gains size:= 512*PRECISION2
PRECISION2 *const gains_out__gains__1 = (PRECISION2*) (Shared + 6106240); // delta_0_subtraction_run_1_reciprocal_transform_actor_0_gains_out > delta_0_subtraction_run_1_subtraction_0_gains size:= 512*PRECISION2
PRECISION2 *const gains_out__gains__2 = (PRECISION2*) (Shared + 6106752); // delta_0_subtraction_run_2_reciprocal_transform_actor_0_gains_out > delta_0_subtraction_run_2_subtraction_0_gains size:= 512*PRECISION2
PRECISION2 *const gains_out__gains__3 = (PRECISION2*) (Shared + 6107264); // delta_0_subtraction_run_3_reciprocal_transform_actor_0_gains_out > delta_0_subtraction_run_3_subtraction_0_gains size:= 512*PRECISION2
PRECISION3 *const out__source_list__0 = (PRECISION3*) (Shared + 6107776); // src_2_0_out > BR_delta_0__source_list_source_list size:= 200*PRECISION3
PRECISION3 *const source_list_0_3__sources__0 = (PRECISION3*) (Shared + 6107976); // BR_delta_0__source_list_source_list_0_3 > delta_0_dft_run_0_dft_actor_0_sources size:= 200*PRECISION3
PRECISION3 *const source_list_1_3__sources__0 = (PRECISION3*) (Shared + 6108176); // BR_delta_0__source_list_source_list_1_3 > delta_0_dft_run_1_dft_actor_0_sources size:= 200*PRECISION3
PRECISION3 *const source_list_2_3__sources__0 = (PRECISION3*) (Shared + 6108376); // BR_delta_0__source_list_source_list_2_3 > delta_0_dft_run_2_dft_actor_0_sources size:= 200*PRECISION3
PRECISION3 *const source_list_3_3__sources__0 = (PRECISION3*) (Shared + 6108576); // BR_delta_0__source_list_source_list_3_3 > delta_0_dft_run_3_dft_actor_0_sources size:= 200*PRECISION3
int2 *const out__gridding_kernel_supports__0 = (int2*) (Shared + 6108776); // src_4_0_out > BR_delta_0__gridding_kernel_supports_gridding_kernel_supports size:= 17*int2
int2 *const out__supports__0 = (int2*) (Shared + 11811285248); // src_13_0_out > delta_0_degridding_kernel_sink_0_supports size:= 17*int2
int2 *const gridding_kernel_supports_0_3__kernel_supports__0 = (int2*) (Shared + 6108793); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_0_3 > delta_0_gridding_run_0_gridding_actor_0_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_1_3__kernel_supports__0 = (int2*) (Shared + 6108810); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_1_3 > delta_0_gridding_run_1_gridding_actor_0_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_2_3__kernel_supports__0 = (int2*) (Shared + 6108827); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_2_3 > delta_0_gridding_run_2_gridding_actor_0_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_3_3__kernel_supports__0 = (int2*) (Shared + 6108844); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_3_3 > delta_0_gridding_run_3_gridding_actor_0_kernel_supports size:= 17*int2
int *const out__num_sources_in__0 = (int*) (Shared + 6108861); // src_3_0_out > BR_delta_0__num_sources_in_num_sources_in size:= 1*int
int *const out__token_in__0 = (int*) (Shared + 11811285265); // src_12_0_out > delta_0_token_sink_0_token_in size:= 1*int
int *const num_sources_in_0_3__num_sources__0 = (int*) (Shared + 6108865); // BR_delta_0__num_sources_in_num_sources_in_0_3 > delta_0_dft_run_0_dft_actor_0_num_sources size:= 1*int
int *const num_sources_in_1_3__num_sources__0 = (int*) (Shared + 6108869); // BR_delta_0__num_sources_in_num_sources_in_1_3 > delta_0_dft_run_1_dft_actor_0_num_sources size:= 1*int
int *const num_sources_in_2_3__num_sources__0 = (int*) (Shared + 6108873); // BR_delta_0__num_sources_in_num_sources_in_2_3 > delta_0_dft_run_2_dft_actor_0_num_sources size:= 1*int
int *const num_sources_in_3_3__num_sources__0 = (int*) (Shared + 6108877); // BR_delta_0__num_sources_in_num_sources_in_3_3 > delta_0_dft_run_3_dft_actor_0_num_sources size:= 1*int
Config *const output_configs__input__0 = (Config*) (Shared + 6106240); // delta_0_split_vis_0_output_configs > delta_0_explode_delta_0_split_vis_0_output_configs_input size:= 4*Config
Config *const out__config__0 = (Config*) (Shared + 3924480); // src_9_0_out > delta_0_split_vis_0_config size:= 1*Config
Config *const output_config__input__0 = (Config*) (Shared + 11811285269); // delta_0_split_vis_0_output_config > delta_0_Broadcast_singular_config_0_input size:= 1*Config
Config *const output_configs_0__input__0 = (Config*) (Shared + 6108881); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_0 > delta_0_broadcast_config_0_input size:= 1*Config
Config *const output_configs_1__input__0 = (Config*) (Shared + 6106244); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_1 > delta_0_broadcast_config_1_input size:= 1*Config
Config *const output_configs_2__input__0 = (Config*) (Shared + 6106752); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_2 > delta_0_broadcast_config_2_input size:= 1*Config
Config *const output_configs_3__input__0 = (Config*) (Shared + 6107264); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_3 > delta_0_broadcast_config_3_input size:= 1*Config
Config *const ifft_0__input__0 = (Config*) (Shared + 11811285270); // delta_0_Broadcast_singular_config_0_ifft_0 > delta_0_ifft_run_0_Broadcast_config_0_input size:= 1*Config
Config *const prolate_1__config__0 = (Config*) (Shared + 11811285271); // delta_0_Broadcast_singular_config_0_prolate_1 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_config size:= 1*Config
Config *const output_dft_0__config__0 = (Config*) (Shared + 6108882); // delta_0_broadcast_config_0_output_dft_0 > delta_0_dft_run_0_dft_actor_0_config size:= 1*Config
Config *const output_gainsapply_1__input__0 = (Config*) (Shared + 6108883); // delta_0_broadcast_config_0_output_gainsapply_1 > delta_0_subtraction_run_0_Broadcast_config_0_input size:= 1*Config
Config *const output_gridding_2__config__0 = (Config*) (Shared + 6108884); // delta_0_broadcast_config_0_output_gridding_2 > delta_0_gridding_run_0_gridding_actor_0_config size:= 1*Config
Config *const output_dft_0__config__1 = (Config*) (Shared + 6108885); // delta_0_broadcast_config_1_output_dft_0 > delta_0_dft_run_1_dft_actor_0_config size:= 1*Config
Config *const output_gainsapply_1__input__1 = (Config*) (Shared + 6106240); // delta_0_broadcast_config_1_output_gainsapply_1 > delta_0_subtraction_run_1_Broadcast_config_0_input size:= 1*Config
Config *const output_gridding_2__config__1 = (Config*) (Shared + 6108886); // delta_0_broadcast_config_1_output_gridding_2 > delta_0_gridding_run_1_gridding_actor_0_config size:= 1*Config
Config *const output_dft_0__config__2 = (Config*) (Shared + 6108887); // delta_0_broadcast_config_2_output_dft_0 > delta_0_dft_run_2_dft_actor_0_config size:= 1*Config
Config *const output_gainsapply_1__input__2 = (Config*) (Shared + 6106753); // delta_0_broadcast_config_2_output_gainsapply_1 > delta_0_subtraction_run_2_Broadcast_config_0_input size:= 1*Config
Config *const output_gridding_2__config__2 = (Config*) (Shared + 6108888); // delta_0_broadcast_config_2_output_gridding_2 > delta_0_gridding_run_2_gridding_actor_0_config size:= 1*Config
Config *const output_dft_0__config__3 = (Config*) (Shared + 6108889); // delta_0_broadcast_config_3_output_dft_0 > delta_0_dft_run_3_dft_actor_0_config size:= 1*Config
Config *const output_gainsapply_1__input__3 = (Config*) (Shared + 6107265); // delta_0_broadcast_config_3_output_gainsapply_1 > delta_0_subtraction_run_3_Broadcast_config_0_input size:= 1*Config
Config *const output_gridding_2__config__3 = (Config*) (Shared + 6108890); // delta_0_broadcast_config_3_output_gridding_2 > delta_0_gridding_run_3_gridding_actor_0_config size:= 1*Config
Config *const output1_0__config__0 = (Config*) (Shared + 11811285269); // delta_0_ifft_run_0_Broadcast_config_0_output1_0 > delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0_config size:= 1*Config
Config *const output2_1__config__0 = (Config*) (Shared + 11811285272); // delta_0_ifft_run_0_Broadcast_config_0_output2_1 > delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0_config size:= 1*Config
Config *const output1_0__config__1 = (Config*) (Shared + 6108881); // delta_0_subtraction_run_0_Broadcast_config_0_output1_0 > delta_0_subtraction_run_0_reciprocal_transform_actor_0_config size:= 1*Config
Config *const output2_1__config__1 = (Config*) (Shared + 6108891); // delta_0_subtraction_run_0_Broadcast_config_0_output2_1 > delta_0_subtraction_run_0_subtraction_0_config size:= 1*Config
Config *const output1_0__config__2 = (Config*) (Shared + 6108892); // delta_0_subtraction_run_1_Broadcast_config_0_output1_0 > delta_0_subtraction_run_1_reciprocal_transform_actor_0_config size:= 1*Config
Config *const output2_1__config__2 = (Config*) (Shared + 6108893); // delta_0_subtraction_run_1_Broadcast_config_0_output2_1 > delta_0_subtraction_run_1_subtraction_0_config size:= 1*Config
Config *const output1_0__config__3 = (Config*) (Shared + 6108894); // delta_0_subtraction_run_2_Broadcast_config_0_output1_0 > delta_0_subtraction_run_2_reciprocal_transform_actor_0_config size:= 1*Config
Config *const output2_1__config__3 = (Config*) (Shared + 6108895); // delta_0_subtraction_run_2_Broadcast_config_0_output2_1 > delta_0_subtraction_run_2_subtraction_0_config size:= 1*Config
Config *const output1_0__config__4 = (Config*) (Shared + 6108896); // delta_0_subtraction_run_3_Broadcast_config_0_output1_0 > delta_0_subtraction_run_3_reciprocal_transform_actor_0_config size:= 1*Config
Config *const output2_1__config__4 = (Config*) (Shared + 6108897); // delta_0_subtraction_run_3_Broadcast_config_0_output2_1 > delta_0_subtraction_run_3_subtraction_0_config size:= 1*Config

void* computationThread_Core0(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_out__supports__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__supports__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__kernels__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__kernels__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__token_in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__token_in__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__psf__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__psf__0);
	PREESM_MD5_CTX preesm_md5_ctx_output_image__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_output_image__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_dirty_image_out__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_dirty_image_out__in__0);
#endif
// Initialisation(s)

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    src(out__image__0); // src_0_0

    src(out__psf__0); // src_10_0

    src(out__prolate__0); // src_11_0

    src(out__token_in__0); // src_12_0

    src(out__supports__0); // src_13_0

    src(out__kernels__0); // src_14_0

    src(out__measured_visibilities__0); // src_1_0

    src(out__source_list__0); // src_2_0

    src(out__num_sources_in__0); // src_3_0

    src(out__gridding_kernel_supports__0); // src_4_0

    src(out__gridding_kernels__0); // src_5_0

    src(out__vis_coords__0); // src_6_0

    src(out__gains__0); // src_7_0

    src(out__receiver_pairs__0); // src_8_0

    src(out__config__0); // src_9_0

    // Broadcast BR_delta_0__gains

    {
      // memcpy #0
      memcpy(gains_0_3__gains_in__0 + 0, out__gains__0 + 0, 512); // 512 * PRECISION2
      // memcpy #0
      memcpy(gains_1_3__gains_in__0 + 0, out__gains__0 + 0, 512); // 512 * PRECISION2
      // memcpy #0
      memcpy(gains_2_3__gains_in__0 + 0, out__gains__0 + 0, 512); // 512 * PRECISION2
      // memcpy #0
      memcpy(gains_3_3__gains_in__0 + 0, out__gains__0 + 0, 512); // 512 * PRECISION2
    }

    // Broadcast BR_delta_0__gridding_kernel_supports

    {
      // memcpy #0
      memcpy(gridding_kernel_supports_0_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_1_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_2_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_3_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
    }

    // Broadcast BR_delta_0__gridding_kernels

    {
      // memcpy #0
      memcpy(gridding_kernels_0_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_1_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_2_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_3_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast BR_delta_0__num_sources_in

    {
      // memcpy #0
      memcpy(num_sources_in_0_3__num_sources__0 + 0, out__num_sources_in__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(num_sources_in_1_3__num_sources__0 + 0, out__num_sources_in__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(num_sources_in_2_3__num_sources__0 + 0, out__num_sources_in__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(num_sources_in_3_3__num_sources__0 + 0, out__num_sources_in__0 + 0, 4); // 1 * int
    }

    // Broadcast BR_delta_0__receiver_pairs

    {
      // memcpy #0
      memcpy(receiver_pairs_0_3__receiver_pairs__0 + 0, out__receiver_pairs__0 + 0, 130816); // 130816 * int2
      // memcpy #0
      memcpy(receiver_pairs_1_3__receiver_pairs__0 + 0, out__receiver_pairs__0 + 0, 130816); // 130816 * int2
      // memcpy #0
      memcpy(receiver_pairs_2_3__receiver_pairs__0 + 0, out__receiver_pairs__0 + 0, 130816); // 130816 * int2
      // memcpy #0
      memcpy(receiver_pairs_3_3__receiver_pairs__0 + 0, out__receiver_pairs__0 + 0, 130816); // 130816 * int2
    }

    // Broadcast BR_delta_0__source_list

    {
      // memcpy #0
      memcpy(source_list_0_3__sources__0 + 0, out__source_list__0 + 0, 200); // 200 * PRECISION3
      // memcpy #0
      memcpy(source_list_1_3__sources__0 + 0, out__source_list__0 + 0, 200); // 200 * PRECISION3
      // memcpy #0
      memcpy(source_list_2_3__sources__0 + 0, out__source_list__0 + 0, 200); // 200 * PRECISION3
      // memcpy #0
      memcpy(source_list_3_3__sources__0 + 0, out__source_list__0 + 0, 200); // 200 * PRECISION3
    }

    degridding_kernel_sink(17/*NUM_DEGRIDDING_KERNELS*/, 108800/*TOTAL_DEGRIDDING_KERNEL_SAMPLES*/, out__supports__0,
        out__kernels__0); // delta_0_degridding_kernel_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__supports__0,(char *)out__supports__0, 17);
		PREESM_MD5_Update(&preesm_md5_ctx_out__kernels__0,(char *)out__kernels__0, 108800);
		#endif

    split_visibilities(out__config__0, 981120/*NUM_VISIBILITIES*/, 4/*SLICES*/, out__measured_visibilities__0,
        out__vis_coords__0, visibilities__measured_vis__0, out_vis_coords__input__0, output_configs__input__0,
        output_config__input__0); // delta_0_split_vis_0

    token_sink(out__token_in__0); // delta_0_token_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__token_in__0,(char *)out__token_in__0, 4);
		#endif

    pass_through_image(32768/*GRID_SIZE*/, out__image__0, output_image__in__0); // delta_0_image_passthrough_0

    psf_sink(32768/*GRID_SIZE*/, out__psf__0); // delta_0_psf_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__psf__0,(char *)out__psf__0, 1073741824);
		#endif

    // Broadcast delta_0_Broadcast_singular_config_0

    {
      // memcpy #0
      memcpy(ifft_0__input__0 + 0, output_config__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(prolate_1__config__0 + 0, output_config__input__0 + 0, 1); // 1 * Config
    }

    // Fork delta_0_explode_delta_0_split_vis_0_out_vis_coords

    {
      memcpy(out_vis_coords_0__input__0 + 0, out_vis_coords__input__0 + 0, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_1__input__0 + 0, out_vis_coords__input__0 + 245280, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_2__input__0 + 0, out_vis_coords__input__0 + 490560, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_3__input__0 + 0, out_vis_coords__input__0 + 735840, 245280); // 245280 * PRECISION3
    }
    // Fork delta_0_explode_delta_0_split_vis_0_output_configs

    {
      memcpy(output_configs_0__input__0 + 0, output_configs__input__0 + 0, 1); // 1 * Config
      memcpy(output_configs_1__input__0 + 0, output_configs__input__0 + 1, 1); // 1 * Config
      memcpy(output_configs_2__input__0 + 0, output_configs__input__0 + 2, 1); // 1 * Config
      memcpy(output_configs_3__input__0 + 0, output_configs__input__0 + 3, 1); // 1 * Config
    }
    // Fork delta_0_explode_delta_0_split_vis_0_visibilities

    {
      memcpy(visibilities_0__measured_vis__0 + 0, visibilities__measured_vis__0 + 0, 245280); // 245280 * PRECISION2
      memcpy(visibilities_1__measured_vis__0 + 0, visibilities__measured_vis__0 + 245280, 245280); // 245280 * PRECISION2
      memcpy(visibilities_2__measured_vis__0 + 0, visibilities__measured_vis__0 + 490560, 245280); // 245280 * PRECISION2
      memcpy(visibilities_3__measured_vis__0 + 0, visibilities__measured_vis__0 + 735840, 245280); // 245280 * PRECISION2
    }
    // Broadcast delta_0_broadcast_config_0

    {
      // memcpy #0
      memcpy(output_dft_0__config__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gainsapply_1__input__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gridding_2__config__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_broadcast_config_1

    {
      // memcpy #0
      memcpy(output_dft_0__config__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gainsapply_1__input__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gridding_2__config__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_broadcast_config_2

    {
      // memcpy #0
      memcpy(output_dft_0__config__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gainsapply_1__input__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gridding_2__config__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_broadcast_config_3

    {
      // memcpy #0
      memcpy(output_dft_0__config__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gainsapply_1__input__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output_gridding_2__config__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_ifft_run_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__0 + 0, ifft_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__0 + 0, ifft_0__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_subtraction_run_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__1 + 0, output_gainsapply_1__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__1 + 0, output_gainsapply_1__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_subtraction_run_1_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__2 + 0, output_gainsapply_1__input__1 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__2 + 0, output_gainsapply_1__input__1 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_subtraction_run_2_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__3 + 0, output_gainsapply_1__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__3 + 0, output_gainsapply_1__input__2 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_subtraction_run_3_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__4 + 0, output_gainsapply_1__input__3 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__4 + 0, output_gainsapply_1__input__3 + 0, 1); // 1 * Config
    }

    reciprocal_transform_actor(512/*NUM_RECEIVERS*/, gains_0_3__gains_in__0, output1_0__config__1, gains_out__gains__0); // delta_0_subtraction_run_0_reciprocal_transform_actor_0

    reciprocal_transform_actor(512/*NUM_RECEIVERS*/, gains_1_3__gains_in__0, output1_0__config__2, gains_out__gains__1); // delta_0_subtraction_run_1_reciprocal_transform_actor_0

    reciprocal_transform_actor(512/*NUM_RECEIVERS*/, gains_2_3__gains_in__0, output1_0__config__3, gains_out__gains__2); // delta_0_subtraction_run_2_reciprocal_transform_actor_0

    reciprocal_transform_actor(512/*NUM_RECEIVERS*/, gains_3_3__gains_in__0, output1_0__config__4, gains_out__gains__3); // delta_0_subtraction_run_3_reciprocal_transform_actor_0

    sink(output_image__in__0); // sink_1_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_output_image__in__0,(char *)output_image__in__0, 1073741824);
		#endif

    // Broadcast delta_0_broadcast_vis_coords_0

    {
      // memcpy #0
      memcpy(output_dft_0__vis_uvw_coords__0 + 0, out_vis_coords_0__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(output_gridding_1__vis_uvw_coords__0 + 0, out_vis_coords_0__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_broadcast_vis_coords_1

    {
      // memcpy #0
      memcpy(output_dft_0__vis_uvw_coords__1 + 0, out_vis_coords_1__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(output_gridding_1__vis_uvw_coords__1 + 0, out_vis_coords_1__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_broadcast_vis_coords_2

    {
      // memcpy #0
      memcpy(output_dft_0__vis_uvw_coords__2 + 0, out_vis_coords_2__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(output_gridding_1__vis_uvw_coords__2 + 0, out_vis_coords_2__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_broadcast_vis_coords_3

    {
      // memcpy #0
      memcpy(output_dft_0__vis_uvw_coords__3 + 0, out_vis_coords_3__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(output_gridding_1__vis_uvw_coords__3 + 0, out_vis_coords_3__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    dft_actor(245280/*NUM_VISIBILITIES*/, 200/*NUM_MAX_SOURCES*/, source_list_0_3__sources__0,
        output_dft_0__vis_uvw_coords__0, num_sources_in_0_3__num_sources__0, output_dft_0__config__0,
        visibilities__v2__0); // delta_0_dft_run_0_dft_actor_0

    dft_actor(245280/*NUM_VISIBILITIES*/, 200/*NUM_MAX_SOURCES*/, source_list_1_3__sources__0,
        output_dft_0__vis_uvw_coords__1, num_sources_in_1_3__num_sources__0, output_dft_0__config__1,
        visibilities__v2__1); // delta_0_dft_run_1_dft_actor_0

    dft_actor(245280/*NUM_VISIBILITIES*/, 200/*NUM_MAX_SOURCES*/, source_list_2_3__sources__0,
        output_dft_0__vis_uvw_coords__2, num_sources_in_2_3__num_sources__0, output_dft_0__config__2,
        visibilities__v2__2); // delta_0_dft_run_2_dft_actor_0

    dft_actor(245280/*NUM_VISIBILITIES*/, 200/*NUM_MAX_SOURCES*/, source_list_3_3__sources__0,
        output_dft_0__vis_uvw_coords__3, num_sources_in_3_3__num_sources__0, output_dft_0__config__3,
        visibilities__v2__3); // delta_0_dft_run_3_dft_actor_0

    add_visibilities(245280/*NUM_VISIBILITIES*/, visibilities__v2__0, output__visibilities_in__0); // delta_0_add_visibilities_0

    add_visibilities(245280/*NUM_VISIBILITIES*/, visibilities__v2__1, output__visibilities_in__1); // delta_0_add_visibilities_1

    add_visibilities(245280/*NUM_VISIBILITIES*/, visibilities__v2__2, output__visibilities_in__2); // delta_0_add_visibilities_2

    add_visibilities(245280/*NUM_VISIBILITIES*/, visibilities__v2__3, output__visibilities_in__3); // delta_0_add_visibilities_3

    subtract_from_measurements(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, 245280/*NUM_VISIBILITIES*/,
        visibilities_0__measured_vis__0, output__visibilities_in__0, gains_out__gains__0,
        receiver_pairs_0_3__receiver_pairs__0, output2_1__config__1, visibilities_out__visibilities__0); // delta_0_subtraction_run_0_subtraction_0

    subtract_from_measurements(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, 245280/*NUM_VISIBILITIES*/,
        visibilities_1__measured_vis__0, output__visibilities_in__1, gains_out__gains__1,
        receiver_pairs_1_3__receiver_pairs__0, output2_1__config__2, visibilities_out__visibilities__1); // delta_0_subtraction_run_1_subtraction_0

    subtract_from_measurements(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, 245280/*NUM_VISIBILITIES*/,
        visibilities_2__measured_vis__0, output__visibilities_in__2, gains_out__gains__2,
        receiver_pairs_2_3__receiver_pairs__0, output2_1__config__3, visibilities_out__visibilities__2); // delta_0_subtraction_run_2_subtraction_0

    subtract_from_measurements(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, 245280/*NUM_VISIBILITIES*/,
        visibilities_3__measured_vis__0, output__visibilities_in__3, gains_out__gains__3,
        receiver_pairs_3_3__receiver_pairs__0, output2_1__config__4, visibilities_out__visibilities__3); // delta_0_subtraction_run_3_subtraction_0

    gridding_actor(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        gridding_kernels_0_3__kernels__0, gridding_kernel_supports_0_3__kernel_supports__0,
        output_gridding_1__vis_uvw_coords__0, visibilities_out__visibilities__0, output_gridding_2__config__0,
        uv_grid__grids_0__0); // delta_0_gridding_run_0_gridding_actor_0

    gridding_actor(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        gridding_kernels_1_3__kernels__0, gridding_kernel_supports_1_3__kernel_supports__0,
        output_gridding_1__vis_uvw_coords__1, visibilities_out__visibilities__1, output_gridding_2__config__1,
        uv_grid__grids_1__0); // delta_0_gridding_run_1_gridding_actor_0

    gridding_actor(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        gridding_kernels_2_3__kernels__0, gridding_kernel_supports_2_3__kernel_supports__0,
        output_gridding_1__vis_uvw_coords__2, visibilities_out__visibilities__2, output_gridding_2__config__2,
        uv_grid__grids_2__0); // delta_0_gridding_run_2_gridding_actor_0

    gridding_actor(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        gridding_kernels_3_3__kernels__0, gridding_kernel_supports_3_3__kernel_supports__0,
        output_gridding_1__vis_uvw_coords__3, visibilities_out__visibilities__3, output_gridding_2__config__3,
        uv_grid__grids_3__0); // delta_0_gridding_run_3_gridding_actor_0

    // Join delta_0_implode_delta_0_merge_grids_0_grids

    {
      memcpy(uv_grid__grids__0 + 0, uv_grid__grids_0__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(uv_grid__grids__0 + 1073741824, uv_grid__grids_1__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(uv_grid__grids__0 + 2147483648, uv_grid__grids_2__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(uv_grid__grids__0 + 3221225472, uv_grid__grids_3__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }
    merge_gridded_visibilities(32768/*GRID_SIZE*/, 4/*SLICES*/, uv_grid__grids__0, output_grid__uv_grid_in__0); // delta_0_merge_grids_0

    fft_shift_complex_to_complex_actor(32768/*GRID_SIZE*/, output_grid__uv_grid_in__0, output1_0__config__0,
        uv_grid_out__uv_grid_in__0); // delta_0_ifft_run_0_fft_shift_complex_to_complex_actor_0

    CUFFT_EXECUTE_INVERSE_C2C_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid_in__0, uv_grid_out__uv_grid__0); // delta_0_ifft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0

    fft_shift_complex_to_real_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid__0, output2_1__config__0,
        dirty_image__dirty_image_in__0); // delta_0_ifft_run_0_fft_shift_complex_to_real_actor_0

    execute_convolution_correction_actor(32768/*GRID_SIZE*/, dirty_image__dirty_image_in__0, out__prolate__0,
        prolate_1__config__0, dirty_image_out__in__0); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0

    sink(dirty_image_out__in__0); // sink_0_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_dirty_image_out__in__0,(char *)dirty_image_out__in__0, 1073741824);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__supports__0);
	printf("preesm_md5_out__supports__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__kernels__0);
	printf("preesm_md5_out__kernels__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__token_in__0);
	printf("preesm_md5_out__token_in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__psf__0);
	printf("preesm_md5_out__psf__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_output_image__in__0);
	printf("preesm_md5_output_image__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_dirty_image_out__in__0);
	printf("preesm_md5_dirty_image_out__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

