/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Wed May 21 09:25:01 CEST 2025
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif

// Core Global Definitions
char Shared[15038396010]; //  size:= 15038396010*char
char *const delta_0_split_uvgrid_0__delta_0_explode_delta_0_split_uvgr__0 = (char*) (Shared + 0); // delta_0_split_uvgrid_0 > delta_0_explode_delta_0_split_uvgrid_0_output_grid size:= 4294967296*char
char *const delta_0_implode_delta_0_merge_grids_0_grids__delta_0_merge__0 = (char*) (Shared + 0); // delta_0_implode_delta_0_merge_grids_0_grids > delta_0_merge_grids_0 size:= 4294967296*char
char *const src_0_0__delta_0_Broadcast_image_estimate_0__0 = (char*) (Shared + 0); // src_0_0 > delta_0_Broadcast_image_estimate_0 size:= 1073741824*char
char *const src_10_0__delta_0_psf_sink_0__0 = (char*) (Shared + 4294967296); // src_10_0 > delta_0_psf_sink_0 size:= 1073741824*char
char *const delta_0_Broadcast_image_estimate_0__delta_0_inverse_conv_c__0 = (char*) (Shared + 1073741824); // delta_0_Broadcast_image_estimate_0 > delta_0_inverse_conv_correction_0 size:= 1073741824*char
char *const delta_0_Broadcast_image_estimate_0__sink_1_0__0 = (char*) (Shared + 5368709120); // delta_0_Broadcast_image_estimate_0 > sink_1_0 size:= 1073741824*char
char *const delta_0_inverse_conv_correction_0__delta_0_fft_run_0_fft_s__0 = (char*) (Shared + 0); // delta_0_inverse_conv_correction_0 > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_fft_run_0_fft_shift_real_to_complex_actor_0__delta__0 = (char*) (Shared + 1073741824); // delta_0_fft_run_0_fft_shift_real_to_complex_actor_0 > delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0 size:= 1073741824*char
char *const delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0__delta__0 = (char*) (Shared + 0); // delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0 > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0__de__0 = (char*) (Shared + 6442450944); // delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0 > delta_0_split_uvgrid_0 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___0 = (char*) (Shared + 6442450944); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_Broadcast_uvgrid_0 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___1 = (char*) (Shared + 7516192768); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_Broadcast_uvgrid_1 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___2 = (char*) (Shared + 8589934592); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_Broadcast_uvgrid_2 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___3 = (char*) (Shared + 9663676416); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_Broadcast_uvgrid_3 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_0__delta_0_grid_0__0 = (char*) (Shared + 0); // delta_0_Broadcast_uvgrid_0 > delta_0_grid_0 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_0__delta_0_fft_degrid_0__0 = (char*) (Shared + 1073741824); // delta_0_Broadcast_uvgrid_0 > delta_0_fft_degrid_0 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_1__delta_0_grid_1__0 = (char*) (Shared + 2147483648); // delta_0_Broadcast_uvgrid_1 > delta_0_grid_1 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_1__delta_0_fft_degrid_1__0 = (char*) (Shared + 3221225472); // delta_0_Broadcast_uvgrid_1 > delta_0_fft_degrid_1 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_2__delta_0_grid_2__0 = (char*) (Shared + 10737418240); // delta_0_Broadcast_uvgrid_2 > delta_0_grid_2 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_2__delta_0_fft_degrid_2__0 = (char*) (Shared + 11811160064); // delta_0_Broadcast_uvgrid_2 > delta_0_fft_degrid_2 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_3__delta_0_grid_3__0 = (char*) (Shared + 12884901888); // delta_0_Broadcast_uvgrid_3 > delta_0_grid_3 size:= 1073741824*char
char *const delta_0_Broadcast_uvgrid_3__delta_0_fft_degrid_3__0 = (char*) (Shared + 13958643712); // delta_0_Broadcast_uvgrid_3 > delta_0_fft_degrid_3 size:= 1073741824*char
char *const delta_0_grid_0__delta_0_implode_delta_0_merge_grids_0_grid__0 = (char*) (Shared + 6442450944); // delta_0_grid_0 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_grid_1__delta_0_implode_delta_0_merge_grids_0_grid__0 = (char*) (Shared + 7516192768); // delta_0_grid_1 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_grid_2__delta_0_implode_delta_0_merge_grids_0_grid__0 = (char*) (Shared + 8589934592); // delta_0_grid_2 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_grid_3__delta_0_implode_delta_0_merge_grids_0_grid__0 = (char*) (Shared + 9663676416); // delta_0_grid_3 > delta_0_implode_delta_0_merge_grids_0_grids size:= 1073741824*char
char *const delta_0_merge_grids_0__delta_0_inverse_fft_run_0_fft_shift__0 = (char*) (Shared + 6442450944); // delta_0_merge_grids_0 > delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_act__0 = (char*) (Shared + 0); // delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0 > delta_0_inverse_fft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 size:= 1073741824*char
char *const delta_0_inverse_fft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor___0 = (char*) (Shared + 1073741824); // delta_0_inverse_fft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 > delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0 size:= 1073741824*char
char *const delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor___0 = (char*) (Shared + 0); // delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 1073741824*char
char *const delta_0_convolution_correction_run_0_execute_convolution_c__0 = (char*) (Shared + 1073741824); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 > sink_0_0 size:= 1073741824*char
char *const delta_0_correct_to_finegrid_0_correct_to_finegrid_0__delta__0 = (char*) (Shared + 15032385536); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0 > delta_0_split_vis_0 size:= 1962244*char
char *const src_1_0__delta_0_correct_to_finegrid_0_apply_gains_0__0 = (char*) (Shared + 15032385536); // src_1_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 981120*char
char *const src_6_0__delta_0_correct_to_finegrid_0_correct_to_finegrid__0 = (char*) (Shared + 15034347780); // src_6_0 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0 size:= 981120*char
char *const delta_0_correct_to_finegrid_0_apply_gains_0__delta_0_corre__0 = (char*) (Shared + 15035328900); // delta_0_correct_to_finegrid_0_apply_gains_0 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0 size:= 981120*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_o__0 = (char*) (Shared + 15034347780); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_out_vis_coords size:= 981120*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_o__1 = (char*) (Shared + 15035328900); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_output_visibilities size:= 981120*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___0 = (char*) (Shared + 15032385536); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_Broadcast_correct_vis_coords_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___1 = (char*) (Shared + 15032630816); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_Broadcast_correct_vis_coords_1 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___2 = (char*) (Shared + 15032876096); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_Broadcast_correct_vis_coords_2 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_out_vis_coords__delta___3 = (char*) (Shared + 15033121376); // delta_0_explode_delta_0_split_vis_0_out_vis_coords > delta_0_Broadcast_correct_vis_coords_3 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_output_visibilities__d__0 = (char*) (Shared + 15033366656); // delta_0_explode_delta_0_split_vis_0_output_visibilities > delta_0_subtract_from_measurements_finegrid_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_output_visibilities__d__1 = (char*) (Shared + 15033611936); // delta_0_explode_delta_0_split_vis_0_output_visibilities > delta_0_subtract_from_measurements_finegrid_1 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_output_visibilities__d__2 = (char*) (Shared + 15033857216); // delta_0_explode_delta_0_split_vis_0_output_visibilities > delta_0_subtract_from_measurements_finegrid_2 size:= 245280*char
char *const delta_0_explode_delta_0_split_vis_0_output_visibilities__d__3 = (char*) (Shared + 15034102496); // delta_0_explode_delta_0_split_vis_0_output_visibilities > delta_0_subtract_from_measurements_finegrid_3 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_0__delta_0_fft_degrid__0 = (char*) (Shared + 15034347776); // delta_0_Broadcast_correct_vis_coords_0 > delta_0_fft_degrid_0 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_0__delta_0_grid_0__0 = (char*) (Shared + 15034593056); // delta_0_Broadcast_correct_vis_coords_0 > delta_0_grid_0 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_1__delta_0_fft_degrid__0 = (char*) (Shared + 15034838336); // delta_0_Broadcast_correct_vis_coords_1 > delta_0_fft_degrid_1 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_1__delta_0_grid_1__0 = (char*) (Shared + 15035083616); // delta_0_Broadcast_correct_vis_coords_1 > delta_0_grid_1 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_2__delta_0_fft_degrid__0 = (char*) (Shared + 15036310020); // delta_0_Broadcast_correct_vis_coords_2 > delta_0_fft_degrid_2 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_2__delta_0_grid_2__0 = (char*) (Shared + 15036555300); // delta_0_Broadcast_correct_vis_coords_2 > delta_0_grid_2 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_3__delta_0_fft_degrid__0 = (char*) (Shared + 15036800580); // delta_0_Broadcast_correct_vis_coords_3 > delta_0_fft_degrid_3 size:= 245280*char
char *const delta_0_Broadcast_correct_vis_coords_3__delta_0_grid_3__0 = (char*) (Shared + 15037045860); // delta_0_Broadcast_correct_vis_coords_3 > delta_0_grid_3 size:= 245280*char
char *const delta_0_fft_degrid_0__delta_0_subtract_from_measurements_f__0 = (char*) (Shared + 6442450944); // delta_0_fft_degrid_0 > delta_0_subtract_from_measurements_finegrid_0 size:= 245280*char
char *const delta_0_fft_degrid_1__delta_0_subtract_from_measurements_f__0 = (char*) (Shared + 7516192768); // delta_0_fft_degrid_1 > delta_0_subtract_from_measurements_finegrid_1 size:= 245280*char
char *const delta_0_fft_degrid_2__delta_0_subtract_from_measurements_f__0 = (char*) (Shared + 8589934592); // delta_0_fft_degrid_2 > delta_0_subtract_from_measurements_finegrid_2 size:= 245280*char
char *const delta_0_fft_degrid_3__delta_0_subtract_from_measurements_f__0 = (char*) (Shared + 9663676416); // delta_0_fft_degrid_3 > delta_0_subtract_from_measurements_finegrid_3 size:= 245280*char
char *const delta_0_subtract_from_measurements_finegrid_0__delta_0_gri__0 = (char*) (Shared + 1073741824); // delta_0_subtract_from_measurements_finegrid_0 > delta_0_grid_0 size:= 245280*char
char *const delta_0_subtract_from_measurements_finegrid_1__delta_0_gri__0 = (char*) (Shared + 3221225472); // delta_0_subtract_from_measurements_finegrid_1 > delta_0_grid_1 size:= 245280*char
char *const delta_0_subtract_from_measurements_finegrid_2__delta_0_gri__0 = (char*) (Shared + 11811160064); // delta_0_subtract_from_measurements_finegrid_2 > delta_0_grid_2 size:= 245280*char
char *const delta_0_subtract_from_measurements_finegrid_3__delta_0_gri__0 = (char*) (Shared + 13958643712); // delta_0_subtract_from_measurements_finegrid_3 > delta_0_grid_3 size:= 245280*char
char *const src_8_0__delta_0_correct_to_finegrid_0_apply_gains_0__0 = (char*) (Shared + 15033366656); // src_8_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 130816*char
char *const src_5_0__BR_delta_0__gridding_kernels__0 = (char*) (Shared + 15037291140); // src_5_0 > BR_delta_0__gridding_kernels size:= 108800*char
char *const src_14_0__BR_delta_0__degridding_kernels__0 = (char*) (Shared + 15037399940); // src_14_0 > BR_delta_0__degridding_kernels size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_grid_0__0 = (char*) (Shared + 15037508740); // BR_delta_0__gridding_kernels > delta_0_grid_0 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_grid_1__0 = (char*) (Shared + 15037617540); // BR_delta_0__gridding_kernels > delta_0_grid_1 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_grid_2__0 = (char*) (Shared + 15037726340); // BR_delta_0__gridding_kernels > delta_0_grid_2 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_grid_3__0 = (char*) (Shared + 15037835140); // BR_delta_0__gridding_kernels > delta_0_grid_3 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_fft_degrid_0__0 = (char*) (Shared + 15037943940); // BR_delta_0__degridding_kernels > delta_0_fft_degrid_0 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_fft_degrid_1__0 = (char*) (Shared + 15038052740); // BR_delta_0__degridding_kernels > delta_0_fft_degrid_1 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_fft_degrid_2__0 = (char*) (Shared + 15038161540); // BR_delta_0__degridding_kernels > delta_0_fft_degrid_2 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_fft_degrid_3__0 = (char*) (Shared + 15038270340); // BR_delta_0__degridding_kernels > delta_0_fft_degrid_3 size:= 108800*char
char *const src_11_0__delta_0_Broadcast_prolate_0__0 = (char*) (Shared + 2147483648); // src_11_0 > delta_0_Broadcast_prolate_0 size:= 16384*char
char *const delta_0_Broadcast_prolate_0__delta_0_inverse_conv_correcti__0 = (char*) (Shared + 2147500032); // delta_0_Broadcast_prolate_0 > delta_0_inverse_conv_correction_0 size:= 16384*char
char *const delta_0_Broadcast_prolate_0__delta_0_convolution_correctio__0 = (char*) (Shared + 15038379140); // delta_0_Broadcast_prolate_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 16384*char
char *const src_7_0__delta_0_correct_to_finegrid_0_reciprocal_transfor__0 = (char*) (Shared + 15033497472); // src_7_0 > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0 size:= 512*char
char *const delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0__0 = (char*) (Shared + 15033497984); // delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 512*char
char *const src_2_0__delta_0_source_list_sink_0__0 = (char*) (Shared + 15038395524); // src_2_0 > delta_0_source_list_sink_0 size:= 200*char
char *const src_4_0__BR_delta_0__gridding_kernel_supports__0 = (char*) (Shared + 15038395724); // src_4_0 > BR_delta_0__gridding_kernel_supports size:= 17*char
char *const src_13_0__BR_delta_0__degridding_kernel_supports__0 = (char*) (Shared + 15038395741); // src_13_0 > BR_delta_0__degridding_kernel_supports size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_grid_0__0 = (char*) (Shared + 15038395758); // BR_delta_0__gridding_kernel_supports > delta_0_grid_0 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_grid_1__0 = (char*) (Shared + 15038395775); // BR_delta_0__gridding_kernel_supports > delta_0_grid_1 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_grid_2__0 = (char*) (Shared + 15038395792); // BR_delta_0__gridding_kernel_supports > delta_0_grid_2 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_grid_3__0 = (char*) (Shared + 15038395809); // BR_delta_0__gridding_kernel_supports > delta_0_grid_3 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_fft_degrid__0 = (char*) (Shared + 15038395826); // BR_delta_0__degridding_kernel_supports > delta_0_fft_degrid_0 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_fft_degrid__1 = (char*) (Shared + 15038395843); // BR_delta_0__degridding_kernel_supports > delta_0_fft_degrid_1 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_fft_degrid__2 = (char*) (Shared + 15038395860); // BR_delta_0__degridding_kernel_supports > delta_0_fft_degrid_2 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_fft_degrid__3 = (char*) (Shared + 15038395877); // BR_delta_0__degridding_kernel_supports > delta_0_fft_degrid_3 size:= 17*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_n__0 = (char*) (Shared + 15038395894); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_num_vis size:= 16*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_m__0 = (char*) (Shared + 15038395910); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_maj_iter_out size:= 16*char
char *const src_3_0__delta_0_source_list_sink_0__0 = (char*) (Shared + 15038395926); // src_3_0 > delta_0_source_list_sink_0 size:= 4*char
char *const src_12_0__delta_0_split_vis_0__0 = (char*) (Shared + 15036310020); // src_12_0 > delta_0_split_vis_0 size:= 4*char
char *const delta_0_split_vis_0__delta_0_explode_delta_0_split_vis_0_o__2 = (char*) (Shared + 15038395930); // delta_0_split_vis_0 > delta_0_explode_delta_0_split_vis_0_output_configs size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_num_vis__delta_0_Broad__0 = (char*) (Shared + 15038395934); // delta_0_explode_delta_0_split_vis_0_num_vis > delta_0_Broadcast_num_correct_vis_0 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_num_vis__delta_0_Broad__1 = (char*) (Shared + 15038395938); // delta_0_explode_delta_0_split_vis_0_num_vis > delta_0_Broadcast_num_correct_vis_1 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_num_vis__delta_0_Broad__2 = (char*) (Shared + 15038395942); // delta_0_explode_delta_0_split_vis_0_num_vis > delta_0_Broadcast_num_correct_vis_2 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_num_vis__delta_0_Broad__3 = (char*) (Shared + 15038395946); // delta_0_explode_delta_0_split_vis_0_num_vis > delta_0_Broadcast_num_correct_vis_3 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_maj_iter_out__delta_0___0 = (char*) (Shared + 15038395950); // delta_0_explode_delta_0_split_vis_0_maj_iter_out > delta_0_grid_0 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_maj_iter_out__delta_0___1 = (char*) (Shared + 15038395954); // delta_0_explode_delta_0_split_vis_0_maj_iter_out > delta_0_grid_1 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_maj_iter_out__delta_0___2 = (char*) (Shared + 15038395958); // delta_0_explode_delta_0_split_vis_0_maj_iter_out > delta_0_grid_2 size:= 4*char
char *const delta_0_explode_delta_0_split_vis_0_maj_iter_out__delta_0___3 = (char*) (Shared + 15038395962); // delta_0_explode_delta_0_split_vis_0_maj_iter_out > delta_0_grid_3 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_0__delta_0_fft_degrid_0__0 = (char*) (Shared + 15038395894); // delta_0_Broadcast_num_correct_vis_0 > delta_0_fft_degrid_0 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_0__delta_0_subtract_from__0 = (char*) (Shared + 15038395898); // delta_0_Broadcast_num_correct_vis_0 > delta_0_subtract_from_measurements_finegrid_0 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_0__delta_0_grid_0__0 = (char*) (Shared + 15038395902); // delta_0_Broadcast_num_correct_vis_0 > delta_0_grid_0 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_1__delta_0_fft_degrid_1__0 = (char*) (Shared + 15038395906); // delta_0_Broadcast_num_correct_vis_1 > delta_0_fft_degrid_1 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_1__delta_0_subtract_from__0 = (char*) (Shared + 15038395966); // delta_0_Broadcast_num_correct_vis_1 > delta_0_subtract_from_measurements_finegrid_1 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_1__delta_0_grid_1__0 = (char*) (Shared + 15038395970); // delta_0_Broadcast_num_correct_vis_1 > delta_0_grid_1 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_2__delta_0_fft_degrid_2__0 = (char*) (Shared + 15038395974); // delta_0_Broadcast_num_correct_vis_2 > delta_0_fft_degrid_2 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_2__delta_0_subtract_from__0 = (char*) (Shared + 15038395978); // delta_0_Broadcast_num_correct_vis_2 > delta_0_subtract_from_measurements_finegrid_2 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_2__delta_0_grid_2__0 = (char*) (Shared + 15038395982); // delta_0_Broadcast_num_correct_vis_2 > delta_0_grid_2 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_3__delta_0_fft_degrid_3__0 = (char*) (Shared + 15038395986); // delta_0_Broadcast_num_correct_vis_3 > delta_0_fft_degrid_3 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_3__delta_0_subtract_from__0 = (char*) (Shared + 15038395990); // delta_0_Broadcast_num_correct_vis_3 > delta_0_subtract_from_measurements_finegrid_3 size:= 4*char
char *const delta_0_Broadcast_num_correct_vis_3__delta_0_grid_3__0 = (char*) (Shared + 15038395994); // delta_0_Broadcast_num_correct_vis_3 > delta_0_grid_3 size:= 4*char
char *const src_9_0__delta_0_Broadcast_config_0__0 = (char*) (Shared + 2147516416); // src_9_0 > delta_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_correct_to_finegrid_0___0 = (char*) (Shared + 15033497984); // delta_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_split_vis_0__0 = (char*) (Shared + 15036310024); // delta_0_Broadcast_config_0 > delta_0_split_vis_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_inverse_fft_run_0_Broa__0 = (char*) (Shared + 15038395998); // delta_0_Broadcast_config_0 > delta_0_inverse_fft_run_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_inverse_conv_correctio__0 = (char*) (Shared + 2147516417); // delta_0_Broadcast_config_0 > delta_0_inverse_conv_correction_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_convolution_correction__0 = (char*) (Shared + 15038395999); // delta_0_Broadcast_config_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_fft_run_0_Broadcast_co__0 = (char*) (Shared + 2147516418); // delta_0_Broadcast_config_0 > delta_0_fft_run_0_Broadcast_config_0 size:= 1*char
char *const delta_0_correct_to_finegrid_0_Broadcast_config_0__delta_0___0 = (char*) (Shared + 15033498496); // delta_0_correct_to_finegrid_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0 size:= 1*char
char *const delta_0_correct_to_finegrid_0_Broadcast_config_0__delta_0___1 = (char*) (Shared + 15033498497); // delta_0_correct_to_finegrid_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 1*char
char *const delta_0_correct_to_finegrid_0_Broadcast_config_0__delta_0___2 = (char*) (Shared + 15036310025); // delta_0_correct_to_finegrid_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0 size:= 1*char
char *const delta_0_inverse_fft_run_0_Broadcast_config_0__delta_0_inve__0 = (char*) (Shared + 15038396000); // delta_0_inverse_fft_run_0_Broadcast_config_0 > delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1*char
char *const delta_0_inverse_fft_run_0_Broadcast_config_0__delta_0_inve__1 = (char*) (Shared + 15038396001); // delta_0_inverse_fft_run_0_Broadcast_config_0 > delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0 size:= 1*char
char *const delta_0_fft_run_0_Broadcast_config_0__delta_0_fft_run_0_ff__0 = (char*) (Shared + 2147516416); // delta_0_fft_run_0_Broadcast_config_0 > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0 size:= 1*char
char *const delta_0_fft_run_0_Broadcast_config_0__delta_0_fft_run_0_ff__1 = (char*) (Shared + 2147516419); // delta_0_fft_run_0_Broadcast_config_0 > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___0 = (char*) (Shared + 15038396002); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_Broadcast_config_multiple_0 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___1 = (char*) (Shared + 15038396003); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_Broadcast_config_multiple_1 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___2 = (char*) (Shared + 15038396004); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_Broadcast_config_multiple_2 size:= 1*char
char *const delta_0_explode_delta_0_split_vis_0_output_configs__delta___3 = (char*) (Shared + 15038396005); // delta_0_explode_delta_0_split_vis_0_output_configs > delta_0_Broadcast_config_multiple_3 size:= 1*char
char *const delta_0_Broadcast_config_multiple_0__delta_0_grid_0__0 = (char*) (Shared + 15038395930); // delta_0_Broadcast_config_multiple_0 > delta_0_grid_0 size:= 1*char
char *const delta_0_Broadcast_config_multiple_0__delta_0_fft_degrid_0__0 = (char*) (Shared + 15038395931); // delta_0_Broadcast_config_multiple_0 > delta_0_fft_degrid_0 size:= 1*char
char *const delta_0_Broadcast_config_multiple_1__delta_0_grid_1__0 = (char*) (Shared + 15038395932); // delta_0_Broadcast_config_multiple_1 > delta_0_grid_1 size:= 1*char
char *const delta_0_Broadcast_config_multiple_1__delta_0_fft_degrid_1__0 = (char*) (Shared + 15038395933); // delta_0_Broadcast_config_multiple_1 > delta_0_fft_degrid_1 size:= 1*char
char *const delta_0_Broadcast_config_multiple_2__delta_0_grid_2__0 = (char*) (Shared + 15038396006); // delta_0_Broadcast_config_multiple_2 > delta_0_grid_2 size:= 1*char
char *const delta_0_Broadcast_config_multiple_2__delta_0_fft_degrid_2__0 = (char*) (Shared + 15038396007); // delta_0_Broadcast_config_multiple_2 > delta_0_fft_degrid_2 size:= 1*char
char *const delta_0_Broadcast_config_multiple_3__delta_0_grid_3__0 = (char*) (Shared + 15038396008); // delta_0_Broadcast_config_multiple_3 > delta_0_grid_3 size:= 1*char
char *const delta_0_Broadcast_config_multiple_3__delta_0_fft_degrid_3__0 = (char*) (Shared + 15038396009); // delta_0_Broadcast_config_multiple_3 > delta_0_fft_degrid_3 size:= 1*char
PRECISION2 *const output_grid__input__0 = (PRECISION2*) (Shared + 0); // delta_0_split_uvgrid_0_output_grid > delta_0_explode_delta_0_split_uvgrid_0_output_grid_input size:= 4294967296*PRECISION2
PRECISION2 *const output_grid__grids__0 = (PRECISION2*) (Shared + 0); // delta_0_implode_delta_0_merge_grids_0_grids_output_grid > delta_0_merge_grids_0_grids size:= 4294967296*PRECISION2
PRECISION *const out__input__0 = (PRECISION*) (Shared + 0); // src_0_0_out > delta_0_Broadcast_image_estimate_0_input size:= 1073741824*PRECISION
PRECISION *const out__psf__0 = (PRECISION*) (Shared + 4294967296); // src_10_0_out > delta_0_psf_sink_0_psf size:= 1073741824*PRECISION
PRECISION *const fft_run_0__dirty_image_in__0 = (PRECISION*) (Shared + 1073741824); // delta_0_Broadcast_image_estimate_0_fft_run_0 > delta_0_inverse_conv_correction_0_dirty_image_in size:= 1073741824*PRECISION
PRECISION *const output_1__in__0 = (PRECISION*) (Shared + 5368709120); // delta_0_Broadcast_image_estimate_0_output_1 > sink_1_0_in size:= 1073741824*PRECISION
PRECISION *const dirty_image_out__image__0 = (PRECISION*) (Shared + 0); // delta_0_inverse_conv_correction_0_dirty_image_out > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0_image size:= 1073741824*PRECISION
PRECISION2 *const fourier__uv_grid_in__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_fft_run_0_fft_shift_real_to_complex_actor_0_fourier > delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid_in__0 = (PRECISION2*) (Shared + 0); // delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0_uv_grid_out > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__input_grid__0 = (PRECISION2*) (Shared + 6442450944); // delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_out > delta_0_split_uvgrid_0_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_0__input__0 = (PRECISION2*) (Shared + 6442450944); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_0 > delta_0_Broadcast_uvgrid_0_input size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_1__input__0 = (PRECISION2*) (Shared + 7516192768); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_1 > delta_0_Broadcast_uvgrid_1_input size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_2__input__0 = (PRECISION2*) (Shared + 8589934592); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_2 > delta_0_Broadcast_uvgrid_2_input size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_3__input__0 = (PRECISION2*) (Shared + 9663676416); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_3 > delta_0_Broadcast_uvgrid_3_input size:= 1073741824*PRECISION2
PRECISION2 *const grid_0__prev_grid__0 = (PRECISION2*) (Shared + 0); // delta_0_Broadcast_uvgrid_0_grid_0 > delta_0_grid_0_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const degrid_1__input_grid__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_Broadcast_uvgrid_0_degrid_1 > delta_0_fft_degrid_0_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const grid_0__prev_grid__1 = (PRECISION2*) (Shared + 2147483648); // delta_0_Broadcast_uvgrid_1_grid_0 > delta_0_grid_1_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const degrid_1__input_grid__1 = (PRECISION2*) (Shared + 3221225472); // delta_0_Broadcast_uvgrid_1_degrid_1 > delta_0_fft_degrid_1_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const grid_0__prev_grid__2 = (PRECISION2*) (Shared + 10737418240); // delta_0_Broadcast_uvgrid_2_grid_0 > delta_0_grid_2_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const degrid_1__input_grid__2 = (PRECISION2*) (Shared + 11811160064); // delta_0_Broadcast_uvgrid_2_degrid_1 > delta_0_fft_degrid_2_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const grid_0__prev_grid__3 = (PRECISION2*) (Shared + 12884901888); // delta_0_Broadcast_uvgrid_3_grid_0 > delta_0_grid_3_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const degrid_1__input_grid__3 = (PRECISION2*) (Shared + 13958643712); // delta_0_Broadcast_uvgrid_3_degrid_1 > delta_0_fft_degrid_3_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_0__0 = (PRECISION2*) (Shared + 6442450944); // delta_0_grid_0_output_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_0 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_1__0 = (PRECISION2*) (Shared + 7516192768); // delta_0_grid_1_output_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_1 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_2__0 = (PRECISION2*) (Shared + 8589934592); // delta_0_grid_2_output_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_2 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_3__0 = (PRECISION2*) (Shared + 9663676416); // delta_0_grid_3_output_grid > delta_0_implode_delta_0_merge_grids_0_grids_grids_3 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__uv_grid_in__0 = (PRECISION2*) (Shared + 6442450944); // delta_0_merge_grids_0_output_grid > delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid_in__1 = (PRECISION2*) (Shared + 0); // delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_out > delta_0_inverse_fft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_inverse_fft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_out > delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0_uv_grid size:= 1073741824*PRECISION2
PRECISION *const dirty_image__dirty_image_in__0 = (PRECISION*) (Shared + 0); // delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0_dirty_image > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_dirty_image_in size:= 1073741824*PRECISION
PRECISION *const dirty_image_out__in__0 = (PRECISION*) (Shared + 1073741824); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_dirty_image_out > sink_0_0_in size:= 1073741824*PRECISION
PRECISION2 *const output_visibilities__measured_visibilities__0 = (PRECISION2*) (Shared + 15032385536); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0_output_visibilities > delta_0_split_vis_0_measured_visibilities size:= 981120*PRECISION2
int *const num_output_visibilities__num_corrected_vis__0 = (int*) (Shared + 15033366656); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0_num_output_visibilities > delta_0_split_vis_0_num_corrected_vis size:= 1*int
PRECISION3 *const output_finegrid_vis_coords__vis_coords__0 = (PRECISION3*) (Shared + 15033366660); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0_output_finegrid_vis_coords > delta_0_split_vis_0_vis_coords size:= 981120*PRECISION3
PRECISION2 *const out__measured_vis__0 = (PRECISION2*) (Shared + 15032385536); // src_1_0_out > delta_0_correct_to_finegrid_0_apply_gains_0_measured_vis size:= 981120*PRECISION2
PRECISION3 *const out__vis_uvw_coords__0 = (PRECISION3*) (Shared + 15034347780); // src_6_0_out > delta_0_correct_to_finegrid_0_correct_to_finegrid_0_vis_uvw_coords size:= 981120*PRECISION3
PRECISION2 *const visibilities_out__input_visibilities__0 = (PRECISION2*) (Shared + 15035328900); // delta_0_correct_to_finegrid_0_apply_gains_0_visibilities_out > delta_0_correct_to_finegrid_0_correct_to_finegrid_0_input_visibilities size:= 981120*PRECISION2
PRECISION3 *const out_vis_coords__input__0 = (PRECISION3*) (Shared + 15034347780); // delta_0_split_vis_0_out_vis_coords > delta_0_explode_delta_0_split_vis_0_out_vis_coords_input size:= 981120*PRECISION3
PRECISION2 *const output_visibilities__gridded_measured_vis__0 = (PRECISION2*) (Shared + 15035328900); // delta_0_split_vis_0_output_visibilities > delta_0_explode_delta_0_split_vis_0_output_visibilities_gridded_measured_vis size:= 981120*PRECISION2
PRECISION3 *const out_vis_coords_0__input__0 = (PRECISION3*) (Shared + 15032385536); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_0 > delta_0_Broadcast_correct_vis_coords_0_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_1__input__0 = (PRECISION3*) (Shared + 15032630816); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_1 > delta_0_Broadcast_correct_vis_coords_1_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_2__input__0 = (PRECISION3*) (Shared + 15032876096); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_2 > delta_0_Broadcast_correct_vis_coords_2_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_3__input__0 = (PRECISION3*) (Shared + 15033121376); // delta_0_explode_delta_0_split_vis_0_out_vis_coords_out_vis_coords_3 > delta_0_Broadcast_correct_vis_coords_3_input size:= 245280*PRECISION3
PRECISION2 *const output_visibilities_0__gridded_measured_vis__0 = (PRECISION2*) (Shared + 15033366656); // delta_0_explode_delta_0_split_vis_0_output_visibilities_output_visibilities_0 > delta_0_subtract_from_measurements_finegrid_0_gridded_measured_vis size:= 245280*PRECISION2
PRECISION2 *const output_visibilities_1__gridded_measured_vis__0 = (PRECISION2*) (Shared + 15033611936); // delta_0_explode_delta_0_split_vis_0_output_visibilities_output_visibilities_1 > delta_0_subtract_from_measurements_finegrid_1_gridded_measured_vis size:= 245280*PRECISION2
PRECISION2 *const output_visibilities_2__gridded_measured_vis__0 = (PRECISION2*) (Shared + 15033857216); // delta_0_explode_delta_0_split_vis_0_output_visibilities_output_visibilities_2 > delta_0_subtract_from_measurements_finegrid_2_gridded_measured_vis size:= 245280*PRECISION2
PRECISION2 *const output_visibilities_3__gridded_measured_vis__0 = (PRECISION2*) (Shared + 15034102496); // delta_0_explode_delta_0_split_vis_0_output_visibilities_output_visibilities_3 > delta_0_subtract_from_measurements_finegrid_3_gridded_measured_vis size:= 245280*PRECISION2
PRECISION3 *const degrid_0__corrected_vis_uvw_coords__0 = (PRECISION3*) (Shared + 15034347776); // delta_0_Broadcast_correct_vis_coords_0_degrid_0 > delta_0_fft_degrid_0_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_1__corrected_vis_uvw_coords__0 = (PRECISION3*) (Shared + 15034593056); // delta_0_Broadcast_correct_vis_coords_0_grid_1 > delta_0_grid_0_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const degrid_0__corrected_vis_uvw_coords__1 = (PRECISION3*) (Shared + 15034838336); // delta_0_Broadcast_correct_vis_coords_1_degrid_0 > delta_0_fft_degrid_1_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_1__corrected_vis_uvw_coords__1 = (PRECISION3*) (Shared + 15035083616); // delta_0_Broadcast_correct_vis_coords_1_grid_1 > delta_0_grid_1_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const degrid_0__corrected_vis_uvw_coords__2 = (PRECISION3*) (Shared + 15036310020); // delta_0_Broadcast_correct_vis_coords_2_degrid_0 > delta_0_fft_degrid_2_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_1__corrected_vis_uvw_coords__2 = (PRECISION3*) (Shared + 15036555300); // delta_0_Broadcast_correct_vis_coords_2_grid_1 > delta_0_grid_2_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const degrid_0__corrected_vis_uvw_coords__3 = (PRECISION3*) (Shared + 15036800580); // delta_0_Broadcast_correct_vis_coords_3_degrid_0 > delta_0_fft_degrid_3_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_1__corrected_vis_uvw_coords__3 = (PRECISION3*) (Shared + 15037045860); // delta_0_Broadcast_correct_vis_coords_3_grid_1 > delta_0_grid_3_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION2 *const output_visibilities__input_vis__0 = (PRECISION2*) (Shared + 6442450944); // delta_0_fft_degrid_0_output_visibilities > delta_0_subtract_from_measurements_finegrid_0_input_vis size:= 245280*PRECISION2
PRECISION2 *const output_visibilities__input_vis__1 = (PRECISION2*) (Shared + 7516192768); // delta_0_fft_degrid_1_output_visibilities > delta_0_subtract_from_measurements_finegrid_1_input_vis size:= 245280*PRECISION2
PRECISION2 *const output_visibilities__input_vis__2 = (PRECISION2*) (Shared + 8589934592); // delta_0_fft_degrid_2_output_visibilities > delta_0_subtract_from_measurements_finegrid_2_input_vis size:= 245280*PRECISION2
PRECISION2 *const output_visibilities__input_vis__3 = (PRECISION2*) (Shared + 9663676416); // delta_0_fft_degrid_3_output_visibilities > delta_0_subtract_from_measurements_finegrid_3_input_vis size:= 245280*PRECISION2
PRECISION2 *const delta_vis__visibilities__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_subtract_from_measurements_finegrid_0_delta_vis > delta_0_grid_0_visibilities size:= 245280*PRECISION2
PRECISION2 *const delta_vis__visibilities__1 = (PRECISION2*) (Shared + 3221225472); // delta_0_subtract_from_measurements_finegrid_1_delta_vis > delta_0_grid_1_visibilities size:= 245280*PRECISION2
PRECISION2 *const delta_vis__visibilities__2 = (PRECISION2*) (Shared + 11811160064); // delta_0_subtract_from_measurements_finegrid_2_delta_vis > delta_0_grid_2_visibilities size:= 245280*PRECISION2
PRECISION2 *const delta_vis__visibilities__3 = (PRECISION2*) (Shared + 13958643712); // delta_0_subtract_from_measurements_finegrid_3_delta_vis > delta_0_grid_3_visibilities size:= 245280*PRECISION2
int2 *const out__receiver_pairs__0 = (int2*) (Shared + 15033366656); // src_8_0_out > delta_0_correct_to_finegrid_0_apply_gains_0_receiver_pairs size:= 130816*int2
PRECISION2 *const out__gridding_kernels__0 = (PRECISION2*) (Shared + 15037291140); // src_5_0_out > BR_delta_0__gridding_kernels_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const out__degridding_kernels__0 = (PRECISION2*) (Shared + 15037399940); // src_14_0_out > BR_delta_0__degridding_kernels_degridding_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_0_3__kernels__0 = (PRECISION2*) (Shared + 15037508740); // BR_delta_0__gridding_kernels_gridding_kernels_0_3 > delta_0_grid_0_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_1_3__kernels__0 = (PRECISION2*) (Shared + 15037617540); // BR_delta_0__gridding_kernels_gridding_kernels_1_3 > delta_0_grid_1_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_2_3__kernels__0 = (PRECISION2*) (Shared + 15037726340); // BR_delta_0__gridding_kernels_gridding_kernels_2_3 > delta_0_grid_2_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_3_3__kernels__0 = (PRECISION2*) (Shared + 15037835140); // BR_delta_0__gridding_kernels_gridding_kernels_3_3 > delta_0_grid_3_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_0_3__kernels__0 = (PRECISION2*) (Shared + 15037943940); // BR_delta_0__degridding_kernels_degridding_kernels_0_3 > delta_0_fft_degrid_0_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_1_3__kernels__0 = (PRECISION2*) (Shared + 15038052740); // BR_delta_0__degridding_kernels_degridding_kernels_1_3 > delta_0_fft_degrid_1_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_2_3__kernels__0 = (PRECISION2*) (Shared + 15038161540); // BR_delta_0__degridding_kernels_degridding_kernels_2_3 > delta_0_fft_degrid_2_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_3_3__kernels__0 = (PRECISION2*) (Shared + 15038270340); // BR_delta_0__degridding_kernels_degridding_kernels_3_3 > delta_0_fft_degrid_3_kernels size:= 108800*PRECISION2
PRECISION *const out__input__1 = (PRECISION*) (Shared + 2147483648); // src_11_0_out > delta_0_Broadcast_prolate_0_input size:= 16384*PRECISION
PRECISION *const inverse_correct_0__prolate__0 = (PRECISION*) (Shared + 2147500032); // delta_0_Broadcast_prolate_0_inverse_correct_0 > delta_0_inverse_conv_correction_0_prolate size:= 16384*PRECISION
PRECISION *const correct_1__prolate__0 = (PRECISION*) (Shared + 15038379140); // delta_0_Broadcast_prolate_0_correct_1 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_prolate size:= 16384*PRECISION
PRECISION2 *const out__gains_in__0 = (PRECISION2*) (Shared + 15033497472); // src_7_0_out > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0_gains_in size:= 512*PRECISION2
PRECISION2 *const gains_out__gains__0 = (PRECISION2*) (Shared + 15033497984); // delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0_gains_out > delta_0_correct_to_finegrid_0_apply_gains_0_gains size:= 512*PRECISION2
PRECISION3 *const out__source_list__0 = (PRECISION3*) (Shared + 15038395524); // src_2_0_out > delta_0_source_list_sink_0_source_list size:= 200*PRECISION3
int2 *const out__gridding_kernel_supports__0 = (int2*) (Shared + 15038395724); // src_4_0_out > BR_delta_0__gridding_kernel_supports_gridding_kernel_supports size:= 17*int2
int2 *const out__degridding_kernel_supports__0 = (int2*) (Shared + 15038395741); // src_13_0_out > BR_delta_0__degridding_kernel_supports_degridding_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_0_3__kernel_supports__0 = (int2*) (Shared + 15038395758); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_0_3 > delta_0_grid_0_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_1_3__kernel_supports__0 = (int2*) (Shared + 15038395775); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_1_3 > delta_0_grid_1_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_2_3__kernel_supports__0 = (int2*) (Shared + 15038395792); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_2_3 > delta_0_grid_2_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_3_3__kernel_supports__0 = (int2*) (Shared + 15038395809); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_3_3 > delta_0_grid_3_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_0_3__kernel_supports__0 = (int2*) (Shared + 15038395826); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_0_3 > delta_0_fft_degrid_0_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_1_3__kernel_supports__0 = (int2*) (Shared + 15038395843); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_1_3 > delta_0_fft_degrid_1_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_2_3__kernel_supports__0 = (int2*) (Shared + 15038395860); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_2_3 > delta_0_fft_degrid_2_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_3_3__kernel_supports__0 = (int2*) (Shared + 15038395877); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_3_3 > delta_0_fft_degrid_3_kernel_supports size:= 17*int2
int *const num_vis__input__0 = (int*) (Shared + 15038395894); // delta_0_split_vis_0_num_vis > delta_0_explode_delta_0_split_vis_0_num_vis_input size:= 4*int
int *const maj_iter_out__maj_iter__0 = (int*) (Shared + 15038395910); // delta_0_split_vis_0_maj_iter_out > delta_0_explode_delta_0_split_vis_0_maj_iter_out_maj_iter size:= 4*int
int *const out__num_sources__0 = (int*) (Shared + 15038395926); // src_3_0_out > delta_0_source_list_sink_0_num_sources size:= 1*int
int *const out__maj_iter__0 = (int*) (Shared + 15036310020); // src_12_0_out > delta_0_split_vis_0_maj_iter size:= 1*int
Config *const output_configs__input__0 = (Config*) (Shared + 15038395930); // delta_0_split_vis_0_output_configs > delta_0_explode_delta_0_split_vis_0_output_configs_input size:= 4*Config
int *const num_vis_0__input__0 = (int*) (Shared + 15038395934); // delta_0_explode_delta_0_split_vis_0_num_vis_num_vis_0 > delta_0_Broadcast_num_correct_vis_0_input size:= 1*int
int *const num_vis_1__input__0 = (int*) (Shared + 15038395938); // delta_0_explode_delta_0_split_vis_0_num_vis_num_vis_1 > delta_0_Broadcast_num_correct_vis_1_input size:= 1*int
int *const num_vis_2__input__0 = (int*) (Shared + 15038395942); // delta_0_explode_delta_0_split_vis_0_num_vis_num_vis_2 > delta_0_Broadcast_num_correct_vis_2_input size:= 1*int
int *const num_vis_3__input__0 = (int*) (Shared + 15038395946); // delta_0_explode_delta_0_split_vis_0_num_vis_num_vis_3 > delta_0_Broadcast_num_correct_vis_3_input size:= 1*int
int *const maj_iter_out_0__maj_iter__0 = (int*) (Shared + 15038395950); // delta_0_explode_delta_0_split_vis_0_maj_iter_out_maj_iter_out_0 > delta_0_grid_0_maj_iter size:= 1*int
int *const maj_iter_out_1__maj_iter__0 = (int*) (Shared + 15038395954); // delta_0_explode_delta_0_split_vis_0_maj_iter_out_maj_iter_out_1 > delta_0_grid_1_maj_iter size:= 1*int
int *const maj_iter_out_2__maj_iter__0 = (int*) (Shared + 15038395958); // delta_0_explode_delta_0_split_vis_0_maj_iter_out_maj_iter_out_2 > delta_0_grid_2_maj_iter size:= 1*int
int *const maj_iter_out_3__maj_iter__0 = (int*) (Shared + 15038395962); // delta_0_explode_delta_0_split_vis_0_maj_iter_out_maj_iter_out_3 > delta_0_grid_3_maj_iter size:= 1*int
int *const degrid_0__num_corrected_visibilities__0 = (int*) (Shared + 15038395894); // delta_0_Broadcast_num_correct_vis_0_degrid_0 > delta_0_fft_degrid_0_num_corrected_visibilities size:= 1*int
int *const subtract_1__num_finegrid_vis__0 = (int*) (Shared + 15038395898); // delta_0_Broadcast_num_correct_vis_0_subtract_1 > delta_0_subtract_from_measurements_finegrid_0_num_finegrid_vis size:= 1*int
int *const grid_2__num_corrected_visibilities__0 = (int*) (Shared + 15038395902); // delta_0_Broadcast_num_correct_vis_0_grid_2 > delta_0_grid_0_num_corrected_visibilities size:= 1*int
int *const degrid_0__num_corrected_visibilities__1 = (int*) (Shared + 15038395906); // delta_0_Broadcast_num_correct_vis_1_degrid_0 > delta_0_fft_degrid_1_num_corrected_visibilities size:= 1*int
int *const subtract_1__num_finegrid_vis__1 = (int*) (Shared + 15038395966); // delta_0_Broadcast_num_correct_vis_1_subtract_1 > delta_0_subtract_from_measurements_finegrid_1_num_finegrid_vis size:= 1*int
int *const grid_2__num_corrected_visibilities__1 = (int*) (Shared + 15038395970); // delta_0_Broadcast_num_correct_vis_1_grid_2 > delta_0_grid_1_num_corrected_visibilities size:= 1*int
int *const degrid_0__num_corrected_visibilities__2 = (int*) (Shared + 15038395974); // delta_0_Broadcast_num_correct_vis_2_degrid_0 > delta_0_fft_degrid_2_num_corrected_visibilities size:= 1*int
int *const subtract_1__num_finegrid_vis__2 = (int*) (Shared + 15038395978); // delta_0_Broadcast_num_correct_vis_2_subtract_1 > delta_0_subtract_from_measurements_finegrid_2_num_finegrid_vis size:= 1*int
int *const grid_2__num_corrected_visibilities__2 = (int*) (Shared + 15038395982); // delta_0_Broadcast_num_correct_vis_2_grid_2 > delta_0_grid_2_num_corrected_visibilities size:= 1*int
int *const degrid_0__num_corrected_visibilities__3 = (int*) (Shared + 15038395986); // delta_0_Broadcast_num_correct_vis_3_degrid_0 > delta_0_fft_degrid_3_num_corrected_visibilities size:= 1*int
int *const subtract_1__num_finegrid_vis__3 = (int*) (Shared + 15038395990); // delta_0_Broadcast_num_correct_vis_3_subtract_1 > delta_0_subtract_from_measurements_finegrid_3_num_finegrid_vis size:= 1*int
int *const grid_2__num_corrected_visibilities__3 = (int*) (Shared + 15038395994); // delta_0_Broadcast_num_correct_vis_3_grid_2 > delta_0_grid_3_num_corrected_visibilities size:= 1*int
Config *const out__input__2 = (Config*) (Shared + 2147516416); // src_9_0_out > delta_0_Broadcast_config_0_input size:= 1*Config
Config *const finegrid_0__input__0 = (Config*) (Shared + 15033497984); // delta_0_Broadcast_config_0_finegrid_0 > delta_0_correct_to_finegrid_0_Broadcast_config_0_input size:= 1*Config
Config *const split_1__config__0 = (Config*) (Shared + 15036310024); // delta_0_Broadcast_config_0_split_1 > delta_0_split_vis_0_config size:= 1*Config
Config *const ifft_2__input__0 = (Config*) (Shared + 15038395998); // delta_0_Broadcast_config_0_ifft_2 > delta_0_inverse_fft_run_0_Broadcast_config_0_input size:= 1*Config
Config *const icc_3__config__0 = (Config*) (Shared + 2147516417); // delta_0_Broadcast_config_0_icc_3 > delta_0_inverse_conv_correction_0_config size:= 1*Config
Config *const cc_4__config__0 = (Config*) (Shared + 15038395999); // delta_0_Broadcast_config_0_cc_4 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_config size:= 1*Config
Config *const fft_5__input__0 = (Config*) (Shared + 2147516418); // delta_0_Broadcast_config_0_fft_5 > delta_0_fft_run_0_Broadcast_config_0_input size:= 1*Config
Config *const output1_0__config__0 = (Config*) (Shared + 15033498496); // delta_0_correct_to_finegrid_0_Broadcast_config_0_output1_0 > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0_config size:= 1*Config
Config *const output2_1__config__0 = (Config*) (Shared + 15033498497); // delta_0_correct_to_finegrid_0_Broadcast_config_0_output2_1 > delta_0_correct_to_finegrid_0_apply_gains_0_config size:= 1*Config
Config *const output3_2__config__0 = (Config*) (Shared + 15036310025); // delta_0_correct_to_finegrid_0_Broadcast_config_0_output3_2 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0_config size:= 1*Config
Config *const output1_0__config__1 = (Config*) (Shared + 15038396000); // delta_0_inverse_fft_run_0_Broadcast_config_0_output1_0 > delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0_config size:= 1*Config
Config *const output2_1__config__1 = (Config*) (Shared + 15038396001); // delta_0_inverse_fft_run_0_Broadcast_config_0_output2_1 > delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0_config size:= 1*Config
Config *const output1_0__config__2 = (Config*) (Shared + 2147516416); // delta_0_fft_run_0_Broadcast_config_0_output1_0 > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0_config size:= 1*Config
Config *const output2_1__config__2 = (Config*) (Shared + 2147516419); // delta_0_fft_run_0_Broadcast_config_0_output2_1 > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0_config size:= 1*Config
Config *const output_configs_0__input__0 = (Config*) (Shared + 15038396002); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_0 > delta_0_Broadcast_config_multiple_0_input size:= 1*Config
Config *const output_configs_1__input__0 = (Config*) (Shared + 15038396003); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_1 > delta_0_Broadcast_config_multiple_1_input size:= 1*Config
Config *const output_configs_2__input__0 = (Config*) (Shared + 15038396004); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_2 > delta_0_Broadcast_config_multiple_2_input size:= 1*Config
Config *const output_configs_3__input__0 = (Config*) (Shared + 15038396005); // delta_0_explode_delta_0_split_vis_0_output_configs_output_configs_3 > delta_0_Broadcast_config_multiple_3_input size:= 1*Config
Config *const grid_0__config__0 = (Config*) (Shared + 15038395930); // delta_0_Broadcast_config_multiple_0_grid_0 > delta_0_grid_0_config size:= 1*Config
Config *const degrid_1__config__0 = (Config*) (Shared + 15038395931); // delta_0_Broadcast_config_multiple_0_degrid_1 > delta_0_fft_degrid_0_config size:= 1*Config
Config *const grid_0__config__1 = (Config*) (Shared + 15038395932); // delta_0_Broadcast_config_multiple_1_grid_0 > delta_0_grid_1_config size:= 1*Config
Config *const degrid_1__config__1 = (Config*) (Shared + 15038395933); // delta_0_Broadcast_config_multiple_1_degrid_1 > delta_0_fft_degrid_1_config size:= 1*Config
Config *const grid_0__config__2 = (Config*) (Shared + 15038396006); // delta_0_Broadcast_config_multiple_2_grid_0 > delta_0_grid_2_config size:= 1*Config
Config *const degrid_1__config__2 = (Config*) (Shared + 15038396007); // delta_0_Broadcast_config_multiple_2_degrid_1 > delta_0_fft_degrid_2_config size:= 1*Config
Config *const grid_0__config__3 = (Config*) (Shared + 15038396008); // delta_0_Broadcast_config_multiple_3_grid_0 > delta_0_grid_3_config size:= 1*Config
Config *const degrid_1__config__3 = (Config*) (Shared + 15038396009); // delta_0_Broadcast_config_multiple_3_degrid_1 > delta_0_fft_degrid_3_config size:= 1*Config

void* computationThread_Core0(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_out__source_list__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__source_list__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__num_sources__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__num_sources__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__psf__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__psf__0);
	PREESM_MD5_CTX preesm_md5_ctx_output_1__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_output_1__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_dirty_image_out__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_dirty_image_out__in__0);
#endif
// Initialisation(s)

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    src(out__input__0); // src_0_0

    src(out__psf__0); // src_10_0

    src(out__input__1); // src_11_0

    src(out__maj_iter__0); // src_12_0

    src(out__degridding_kernel_supports__0); // src_13_0

    src(out__degridding_kernels__0); // src_14_0

    src(out__measured_vis__0); // src_1_0

    src(out__source_list__0); // src_2_0

    src(out__num_sources__0); // src_3_0

    src(out__gridding_kernel_supports__0); // src_4_0

    src(out__gridding_kernels__0); // src_5_0

    src(out__vis_uvw_coords__0); // src_6_0

    src(out__gains_in__0); // src_7_0

    src(out__receiver_pairs__0); // src_8_0

    src(out__input__2); // src_9_0

    // Broadcast BR_delta_0__degridding_kernel_supports

    {
      // memcpy #0
      memcpy(degridding_kernel_supports_0_3__kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(degridding_kernel_supports_1_3__kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(degridding_kernel_supports_2_3__kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(degridding_kernel_supports_3_3__kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0, 17); // 17 * int2
    }

    // Broadcast BR_delta_0__degridding_kernels

    {
      // memcpy #0
      memcpy(degridding_kernels_0_3__kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(degridding_kernels_1_3__kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(degridding_kernels_2_3__kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(degridding_kernels_3_3__kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast BR_delta_0__gridding_kernel_supports

    {
      // memcpy #0
      memcpy(gridding_kernel_supports_0_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_1_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_2_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_3_3__kernel_supports__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
    }

    // Broadcast BR_delta_0__gridding_kernels

    {
      // memcpy #0
      memcpy(gridding_kernels_0_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_1_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_2_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_3_3__kernels__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(finegrid_0__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(split_1__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(ifft_2__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(icc_3__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(cc_4__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(fft_5__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_prolate_0

    {
      // memcpy #0
      memcpy(inverse_correct_0__prolate__0 + 0, out__input__1 + 0, 16384); // 16384 * PRECISION
      // memcpy #0
      memcpy(correct_1__prolate__0 + 0, out__input__1 + 0, 16384); // 16384 * PRECISION
    }

    source_list_sink(200/*MAX_SOURCES*/, out__source_list__0, out__num_sources__0); // delta_0_source_list_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__source_list__0,(char *)out__source_list__0, 200);
		PREESM_MD5_Update(&preesm_md5_ctx_out__num_sources__0,(char *)out__num_sources__0, 4);
		#endif

    // Broadcast delta_0_correct_to_finegrid_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__0 + 0, finegrid_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__0 + 0, finegrid_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output3_2__config__0 + 0, finegrid_0__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_fft_run_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__2 + 0, fft_5__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__2 + 0, fft_5__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_inverse_fft_run_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__1 + 0, ifft_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__1 + 0, ifft_2__input__0 + 0, 1); // 1 * Config
    }

    reciprocal_transform_actor(512/*NUM_RECEIVERS*/, out__gains_in__0, output1_0__config__0, gains_out__gains__0); // delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0

    // Broadcast delta_0_Broadcast_image_estimate_0

    {
      // memcpy #0
      memcpy(fft_run_0__dirty_image_in__0 + 0, out__input__0 + 0, 1073741824); // 1073741824 * PRECISION
      // memcpy #0
      memcpy(output_1__in__0 + 0, out__input__0 + 0, 1073741824); // 1073741824 * PRECISION
    }

    psf_sink(32768/*GRID_SIZE*/, out__psf__0); // delta_0_psf_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__psf__0,(char *)out__psf__0, 1073741824);
		#endif

    apply_gains_only(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, 981120/*NUM_VISIBILITIES*/, out__measured_vis__0,
        gains_out__gains__0, out__receiver_pairs__0, output2_1__config__0, visibilities_out__input_visibilities__0); // delta_0_correct_to_finegrid_0_apply_gains_0

    correct_to_finegrid(981120/*NUM_VISIBILITIES*/, 32768/*GRID_SIZE*/, 16/*OVERSAMPLING_FACTOR*/,
        0/*PERFORM_SIMPLIFICATION*/, out__vis_uvw_coords__0, visibilities_out__input_visibilities__0,
        output3_2__config__0, output_visibilities__measured_visibilities__0, output_finegrid_vis_coords__vis_coords__0,
        num_output_visibilities__num_corrected_vis__0); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0

    split_fftdegrid_visibilities(981120/*NUM_VISIBILITIES*/, 4/*SLICES*/, 32768/*GRID_SIZE*/, split_1__config__0,
        output_finegrid_vis_coords__vis_coords__0, output_visibilities__measured_visibilities__0,
        num_output_visibilities__num_corrected_vis__0, out__maj_iter__0, output_visibilities__gridded_measured_vis__0,
        out_vis_coords__input__0, output_configs__input__0, num_vis__input__0, maj_iter_out__maj_iter__0); // delta_0_split_vis_0

    // Fork delta_0_explode_delta_0_split_vis_0_maj_iter_out

    {
      memcpy(maj_iter_out_0__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 0, 4); // 1 * int
      memcpy(maj_iter_out_1__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 1, 4); // 1 * int
      memcpy(maj_iter_out_2__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 2, 4); // 1 * int
      memcpy(maj_iter_out_3__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 3, 4); // 1 * int
    }
    // Fork delta_0_explode_delta_0_split_vis_0_num_vis

    {
      memcpy(num_vis_0__input__0 + 0, num_vis__input__0 + 0, 4); // 1 * int
      memcpy(num_vis_1__input__0 + 0, num_vis__input__0 + 1, 4); // 1 * int
      memcpy(num_vis_2__input__0 + 0, num_vis__input__0 + 2, 4); // 1 * int
      memcpy(num_vis_3__input__0 + 0, num_vis__input__0 + 3, 4); // 1 * int
    }
    // Fork delta_0_explode_delta_0_split_vis_0_out_vis_coords

    {
      memcpy(out_vis_coords_0__input__0 + 0, out_vis_coords__input__0 + 0, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_1__input__0 + 0, out_vis_coords__input__0 + 245280, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_2__input__0 + 0, out_vis_coords__input__0 + 490560, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_3__input__0 + 0, out_vis_coords__input__0 + 735840, 245280); // 245280 * PRECISION3
    }
    // Fork delta_0_explode_delta_0_split_vis_0_output_configs

    {
      memcpy(output_configs_0__input__0 + 0, output_configs__input__0 + 0, 1); // 1 * Config
      memcpy(output_configs_1__input__0 + 0, output_configs__input__0 + 1, 1); // 1 * Config
      memcpy(output_configs_2__input__0 + 0, output_configs__input__0 + 2, 1); // 1 * Config
      memcpy(output_configs_3__input__0 + 0, output_configs__input__0 + 3, 1); // 1 * Config
    }
    // Fork delta_0_explode_delta_0_split_vis_0_output_visibilities

    {
      memcpy(output_visibilities_0__gridded_measured_vis__0 + 0, output_visibilities__gridded_measured_vis__0 + 0,
          245280); // 245280 * PRECISION2
      memcpy(output_visibilities_1__gridded_measured_vis__0 + 0, output_visibilities__gridded_measured_vis__0 + 245280,
          245280); // 245280 * PRECISION2
      memcpy(output_visibilities_2__gridded_measured_vis__0 + 0, output_visibilities__gridded_measured_vis__0 + 490560,
          245280); // 245280 * PRECISION2
      memcpy(output_visibilities_3__gridded_measured_vis__0 + 0, output_visibilities__gridded_measured_vis__0 + 735840,
          245280); // 245280 * PRECISION2
    }
    // Broadcast delta_0_Broadcast_config_multiple_0

    {
      // memcpy #0
      memcpy(grid_0__config__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(degrid_1__config__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_config_multiple_1

    {
      // memcpy #0
      memcpy(grid_0__config__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(degrid_1__config__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_config_multiple_2

    {
      // memcpy #0
      memcpy(grid_0__config__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(degrid_1__config__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_config_multiple_3

    {
      // memcpy #0
      memcpy(grid_0__config__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(degrid_1__config__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_num_correct_vis_0

    {
      // memcpy #0
      memcpy(degrid_0__num_corrected_visibilities__0 + 0, num_vis_0__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(subtract_1__num_finegrid_vis__0 + 0, num_vis_0__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(grid_2__num_corrected_visibilities__0 + 0, num_vis_0__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_num_correct_vis_1

    {
      // memcpy #0
      memcpy(degrid_0__num_corrected_visibilities__1 + 0, num_vis_1__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(subtract_1__num_finegrid_vis__1 + 0, num_vis_1__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(grid_2__num_corrected_visibilities__1 + 0, num_vis_1__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_num_correct_vis_2

    {
      // memcpy #0
      memcpy(degrid_0__num_corrected_visibilities__2 + 0, num_vis_2__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(subtract_1__num_finegrid_vis__2 + 0, num_vis_2__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(grid_2__num_corrected_visibilities__2 + 0, num_vis_2__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_num_correct_vis_3

    {
      // memcpy #0
      memcpy(degrid_0__num_corrected_visibilities__3 + 0, num_vis_3__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(subtract_1__num_finegrid_vis__3 + 0, num_vis_3__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(grid_2__num_corrected_visibilities__3 + 0, num_vis_3__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_correct_vis_coords_0

    {
      // memcpy #0
      memcpy(degrid_0__corrected_vis_uvw_coords__0 + 0, out_vis_coords_0__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_1__corrected_vis_uvw_coords__0 + 0, out_vis_coords_0__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_Broadcast_correct_vis_coords_1

    {
      // memcpy #0
      memcpy(degrid_0__corrected_vis_uvw_coords__1 + 0, out_vis_coords_1__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_1__corrected_vis_uvw_coords__1 + 0, out_vis_coords_1__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_Broadcast_correct_vis_coords_2

    {
      // memcpy #0
      memcpy(degrid_0__corrected_vis_uvw_coords__2 + 0, out_vis_coords_2__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_1__corrected_vis_uvw_coords__2 + 0, out_vis_coords_2__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_Broadcast_correct_vis_coords_3

    {
      // memcpy #0
      memcpy(degrid_0__corrected_vis_uvw_coords__3 + 0, out_vis_coords_3__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_1__corrected_vis_uvw_coords__3 + 0, out_vis_coords_3__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    execute_inv_convolution_correction_actor(32768/*GRID_SIZE*/, fft_run_0__dirty_image_in__0,
        inverse_correct_0__prolate__0, icc_3__config__0, dirty_image_out__image__0); // delta_0_inverse_conv_correction_0

    sink(output_1__in__0); // sink_1_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_output_1__in__0,(char *)output_1__in__0, 1073741824);
		#endif

    fft_shift_real_to_complex_actor(32768/*GRID_SIZE*/, dirty_image_out__image__0, output1_0__config__2,
        fourier__uv_grid_in__0); // delta_0_fft_run_0_fft_shift_real_to_complex_actor_0

    CUFFT_EXECUTE_FORWARD_C2C_actor(32768/*GRID_SIZE*/, fourier__uv_grid_in__0, uv_grid_out__uv_grid_in__0); // delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0

    fft_shift_complex_to_complex_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid_in__0, output2_1__config__2,
        uv_grid_out__input_grid__0); // delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0

    split_uvgrid(32768/*GRID_SIZE*/, 4/*SLICES*/, uv_grid_out__input_grid__0, output_grid__input__0); // delta_0_split_uvgrid_0

    // Fork delta_0_explode_delta_0_split_uvgrid_0_output_grid

    {
      memcpy(output_grid_0__input__0 + 0, output_grid__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid_1__input__0 + 0, output_grid__input__0 + 1073741824, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid_2__input__0 + 0, output_grid__input__0 + 2147483648, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid_3__input__0 + 0, output_grid__input__0 + 3221225472, 1073741824); // 1073741824 * PRECISION2
    }
    // Broadcast delta_0_Broadcast_uvgrid_0

    {
      // memcpy #0
      memcpy(grid_0__prev_grid__0 + 0, output_grid_0__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(degrid_1__input_grid__0 + 0, output_grid_0__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_uvgrid_1

    {
      // memcpy #0
      memcpy(grid_0__prev_grid__1 + 0, output_grid_1__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(degrid_1__input_grid__1 + 0, output_grid_1__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_uvgrid_2

    {
      // memcpy #0
      memcpy(grid_0__prev_grid__2 + 0, output_grid_2__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(degrid_1__input_grid__2 + 0, output_grid_2__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_uvgrid_3

    {
      // memcpy #0
      memcpy(grid_0__prev_grid__3 + 0, output_grid_3__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(degrid_1__input_grid__3 + 0, output_grid_3__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    std_degridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, degridding_kernels_0_3__kernels__0,
        degridding_kernel_supports_0_3__kernel_supports__0, degrid_1__input_grid__0,
        degrid_0__corrected_vis_uvw_coords__0, degrid_0__num_corrected_visibilities__0, degrid_1__config__0,
        output_visibilities__input_vis__0); // delta_0_fft_degrid_0

    std_degridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, degridding_kernels_1_3__kernels__0,
        degridding_kernel_supports_1_3__kernel_supports__0, degrid_1__input_grid__1,
        degrid_0__corrected_vis_uvw_coords__1, degrid_0__num_corrected_visibilities__1, degrid_1__config__1,
        output_visibilities__input_vis__1); // delta_0_fft_degrid_1

    std_degridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, degridding_kernels_2_3__kernels__0,
        degridding_kernel_supports_2_3__kernel_supports__0, degrid_1__input_grid__2,
        degrid_0__corrected_vis_uvw_coords__2, degrid_0__num_corrected_visibilities__2, degrid_1__config__2,
        output_visibilities__input_vis__2); // delta_0_fft_degrid_2

    std_degridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, degridding_kernels_3_3__kernels__0,
        degridding_kernel_supports_3_3__kernel_supports__0, degrid_1__input_grid__3,
        degrid_0__corrected_vis_uvw_coords__3, degrid_0__num_corrected_visibilities__3, degrid_1__config__3,
        output_visibilities__input_vis__3); // delta_0_fft_degrid_3

    subtract_from_measurements_finegrid(245280/*NUM_VISIBILITIES*/, output_visibilities_0__gridded_measured_vis__0,
        output_visibilities__input_vis__0, subtract_1__num_finegrid_vis__0, delta_vis__visibilities__0); // delta_0_subtract_from_measurements_finegrid_0

    subtract_from_measurements_finegrid(245280/*NUM_VISIBILITIES*/, output_visibilities_1__gridded_measured_vis__0,
        output_visibilities__input_vis__1, subtract_1__num_finegrid_vis__1, delta_vis__visibilities__1); // delta_0_subtract_from_measurements_finegrid_1

    subtract_from_measurements_finegrid(245280/*NUM_VISIBILITIES*/, output_visibilities_2__gridded_measured_vis__0,
        output_visibilities__input_vis__2, subtract_1__num_finegrid_vis__2, delta_vis__visibilities__2); // delta_0_subtract_from_measurements_finegrid_2

    subtract_from_measurements_finegrid(245280/*NUM_VISIBILITIES*/, output_visibilities_3__gridded_measured_vis__0,
        output_visibilities__input_vis__3, subtract_1__num_finegrid_vis__3, delta_vis__visibilities__3); // delta_0_subtract_from_measurements_finegrid_3

    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_0__maj_iter__0, grid_2__num_corrected_visibilities__0,
        gridding_kernels_0_3__kernels__0, gridding_kernel_supports_0_3__kernel_supports__0,
        grid_1__corrected_vis_uvw_coords__0, delta_vis__visibilities__0, grid_0__config__0, grid_0__prev_grid__0,
        output_grid__grids_0__0); // delta_0_grid_0

    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_1__maj_iter__0, grid_2__num_corrected_visibilities__1,
        gridding_kernels_1_3__kernels__0, gridding_kernel_supports_1_3__kernel_supports__0,
        grid_1__corrected_vis_uvw_coords__1, delta_vis__visibilities__1, grid_0__config__1, grid_0__prev_grid__1,
        output_grid__grids_1__0); // delta_0_grid_1

    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_2__maj_iter__0, grid_2__num_corrected_visibilities__2,
        gridding_kernels_2_3__kernels__0, gridding_kernel_supports_2_3__kernel_supports__0,
        grid_1__corrected_vis_uvw_coords__2, delta_vis__visibilities__2, grid_0__config__2, grid_0__prev_grid__2,
        output_grid__grids_2__0); // delta_0_grid_2

    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_3__maj_iter__0, grid_2__num_corrected_visibilities__3,
        gridding_kernels_3_3__kernels__0, gridding_kernel_supports_3_3__kernel_supports__0,
        grid_1__corrected_vis_uvw_coords__3, delta_vis__visibilities__3, grid_0__config__3, grid_0__prev_grid__3,
        output_grid__grids_3__0); // delta_0_grid_3

    // Join delta_0_implode_delta_0_merge_grids_0_grids

    {
      memcpy(output_grid__grids__0 + 0, output_grid__grids_0__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid__grids__0 + 1073741824, output_grid__grids_1__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid__grids__0 + 2147483648, output_grid__grids_2__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid__grids__0 + 3221225472, output_grid__grids_3__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }
    merge_gridded_visibilities(32768/*GRID_SIZE*/, 4/*SLICES*/, output_grid__grids__0, output_grid__uv_grid_in__0); // delta_0_merge_grids_0

    fft_shift_complex_to_complex_actor(32768/*GRID_SIZE*/, output_grid__uv_grid_in__0, output1_0__config__1,
        uv_grid_out__uv_grid_in__1); // delta_0_inverse_fft_run_0_fft_shift_complex_to_complex_actor_0

    CUFFT_EXECUTE_INVERSE_C2C_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid_in__1, uv_grid_out__uv_grid__0); // delta_0_inverse_fft_run_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0

    fft_shift_complex_to_real_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid__0, output2_1__config__1,
        dirty_image__dirty_image_in__0); // delta_0_inverse_fft_run_0_fft_shift_complex_to_real_actor_0

    execute_convolution_correction_actor(32768/*GRID_SIZE*/, dirty_image__dirty_image_in__0, correct_1__prolate__0,
        cc_4__config__0, dirty_image_out__in__0); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0

    sink(dirty_image_out__in__0); // sink_0_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_dirty_image_out__in__0,(char *)dirty_image_out__in__0, 1073741824);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__source_list__0);
	printf("preesm_md5_out__source_list__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__num_sources__0);
	printf("preesm_md5_out__num_sources__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__psf__0);
	printf("preesm_md5_out__psf__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_output_1__in__0);
	printf("preesm_md5_output_1__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_dirty_image_out__in__0);
	printf("preesm_md5_dirty_image_out__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

