/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Wed May 21 12:28:11 CEST 2025
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif

// Core Global Definitions
char Shared[24697946608]; //  size:= 24697946608*char
char *const FIFO_Head_delta_end_out_Broadcast_gridded_measured_prev__d__0 = (char*) (Shared + 23622320128); // FIFO_Head_delta_end_out_Broadcast_gridded_measured_prev > delta_init_in_grid_prev_grid size:= 1073741824*char
char *const delta_0_split_uvgrid_0__delta_0_explode_delta_0_split_uvgr__0 = (char*) (Shared + 0); // delta_0_split_uvgrid_0 > delta_0_explode_delta_0_split_uvgrid_0_output_grid size:= 4294967296*char
char *const delta_0_implode_delta_0_merge_estimate_grid_0_grids__delta__0 = (char*) (Shared + 0); // delta_0_implode_delta_0_merge_estimate_grid_0_grids > delta_0_merge_estimate_grid_0 size:= 4294967296*char
char *const delta_0_implode_delta_0_merge_measurement_grid_0_grids__de__0 = (char*) (Shared + 4294967296); // delta_0_implode_delta_0_merge_measurement_grid_0_grids > delta_0_merge_measurement_grid_0 size:= 4294967296*char
char *const delta_init_in_grid_prev_grid__delta_0_grid_0__0 = (char*) (Shared + 4294967296); // delta_init_in_grid_prev_grid > delta_0_grid_0 size:= 1073741824*char
char *const src_0_0__delta_0_Broadcast_image_estimate_0__0 = (char*) (Shared + 0); // src_0_0 > delta_0_Broadcast_image_estimate_0 size:= 1073741824*char
char *const src_10_0__delta_0_psf_sink_0__0 = (char*) (Shared + 8589934592); // src_10_0 > delta_0_psf_sink_0 size:= 1073741824*char
char *const delta_0_Broadcast_image_estimate_0__delta_0_inv_conv_corre__0 = (char*) (Shared + 1073741824); // delta_0_Broadcast_image_estimate_0 > delta_0_inv_conv_correction_0 size:= 1073741824*char
char *const delta_0_Broadcast_image_estimate_0__sink_1_0__0 = (char*) (Shared + 9663676416); // delta_0_Broadcast_image_estimate_0 > sink_1_0 size:= 1073741824*char
char *const delta_0_inv_conv_correction_0__delta_0_fft_run_0_fft_shift__0 = (char*) (Shared + 0); // delta_0_inv_conv_correction_0 > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_fft_run_0_fft_shift_real_to_complex_actor_0__delta__0 = (char*) (Shared + 1073741824); // delta_0_fft_run_0_fft_shift_real_to_complex_actor_0 > delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0 size:= 1073741824*char
char *const delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0__delta__0 = (char*) (Shared + 0); // delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0 > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0__de__0 = (char*) (Shared + 10737418240); // delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0 > delta_0_split_uvgrid_0 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___0 = (char*) (Shared + 10737418240); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_g2g_degridgrid_0 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___1 = (char*) (Shared + 11811160064); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_g2g_degridgrid_1 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___2 = (char*) (Shared + 12884901888); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_g2g_degridgrid_2 size:= 1073741824*char
char *const delta_0_explode_delta_0_split_uvgrid_0_output_grid__delta___3 = (char*) (Shared + 13958643712); // delta_0_explode_delta_0_split_uvgrid_0_output_grid > delta_0_g2g_degridgrid_3 size:= 1073741824*char
char *const delta_0_grid_0__delta_0_Broadcast_gridded_measured_0__0 = (char*) (Shared + 5368709120); // delta_0_grid_0 > delta_0_Broadcast_gridded_measured_0 size:= 1073741824*char
char *const delta_0_g2g_degridgrid_0__delta_0_implode_delta_0_merge_es__0 = (char*) (Shared + 15032385536); // delta_0_g2g_degridgrid_0 > delta_0_implode_delta_0_merge_estimate_grid_0_grids size:= 1073741824*char
char *const delta_0_g2g_degridgrid_1__delta_0_implode_delta_0_merge_es__0 = (char*) (Shared + 16106127360); // delta_0_g2g_degridgrid_1 > delta_0_implode_delta_0_merge_estimate_grid_0_grids size:= 1073741824*char
char *const delta_0_g2g_degridgrid_2__delta_0_implode_delta_0_merge_es__0 = (char*) (Shared + 17179869184); // delta_0_g2g_degridgrid_2 > delta_0_implode_delta_0_merge_estimate_grid_0_grids size:= 1073741824*char
char *const delta_0_g2g_degridgrid_3__delta_0_implode_delta_0_merge_es__0 = (char*) (Shared + 18253611008); // delta_0_g2g_degridgrid_3 > delta_0_implode_delta_0_merge_estimate_grid_0_grids size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_0__delta_0_grid_1__0 = (char*) (Shared + 4294967296); // delta_0_Broadcast_gridded_measured_0 > delta_0_grid_1 size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_0__delta_0_implode_delt__0 = (char*) (Shared + 19327352832); // delta_0_Broadcast_gridded_measured_0 > delta_0_implode_delta_0_merge_measurement_grid_0_grids size:= 1073741824*char
char *const delta_0_grid_1__delta_0_Broadcast_gridded_measured_1__0 = (char*) (Shared + 5368709120); // delta_0_grid_1 > delta_0_Broadcast_gridded_measured_1 size:= 1073741824*char
char *const delta_0_merge_estimate_grid_0__delta_0_inverse_fft_run_est__0 = (char*) (Shared + 10737418240); // delta_0_merge_estimate_grid_0 > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_1__delta_0_grid_2__0 = (char*) (Shared + 4294967296); // delta_0_Broadcast_gridded_measured_1 > delta_0_grid_2 size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_1__delta_0_implode_delt__0 = (char*) (Shared + 20401094656); // delta_0_Broadcast_gridded_measured_1 > delta_0_implode_delta_0_merge_measurement_grid_0_grids size:= 1073741824*char
char *const delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to___0 = (char*) (Shared + 0); // delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0 > delta_0_inverse_fft_run_estimation_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 size:= 1073741824*char
char *const delta_0_grid_2__delta_0_Broadcast_gridded_measured_2__0 = (char*) (Shared + 5368709120); // delta_0_grid_2 > delta_0_Broadcast_gridded_measured_2 size:= 1073741824*char
char *const delta_0_inverse_fft_run_estimation_0_CUFFT_EXECUTE_INVERSE__0 = (char*) (Shared + 1073741824); // delta_0_inverse_fft_run_estimation_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0 size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_2__delta_0_grid_3__0 = (char*) (Shared + 4294967296); // delta_0_Broadcast_gridded_measured_2 > delta_0_grid_3 size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_2__delta_0_implode_delt__0 = (char*) (Shared + 21474836480); // delta_0_Broadcast_gridded_measured_2 > delta_0_implode_delta_0_merge_measurement_grid_0_grids size:= 1073741824*char
char *const delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to___1 = (char*) (Shared + 0); // delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0 > delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0 size:= 1073741824*char
char *const delta_0_grid_3__delta_0_Broadcast_gridded_measured_3__0 = (char*) (Shared + 5368709120); // delta_0_grid_3 > delta_0_Broadcast_gridded_measured_3 size:= 1073741824*char
char *const delta_0_convolution_correction_run_estimation_0_execute_co__0 = (char*) (Shared + 1073741824); // delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0 > delta_0_subtract_image_space_0 size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_3__delta_0_implode_delt__0 = (char*) (Shared + 22548578304); // delta_0_Broadcast_gridded_measured_3 > delta_0_implode_delta_0_merge_measurement_grid_0_grids size:= 1073741824*char
char *const delta_0_Broadcast_gridded_measured_3__delta_end_out_Broadc__0 = (char*) (Shared + 23622320128); // delta_0_Broadcast_gridded_measured_3 > delta_end_out_Broadcast_gridded_measured_prev size:= 1073741824*char
char *const delta_0_merge_measurement_grid_0__delta_0_inverse_fft_run___0 = (char*) (Shared + 19327352832); // delta_0_merge_measurement_grid_0 > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0 size:= 1073741824*char
char *const delta_0_inverse_fft_run_measurements_0_fft_shift_complex_t__0 = (char*) (Shared + 4294967296); // delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0 > delta_0_inverse_fft_run_measurements_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 size:= 1073741824*char
char *const delta_0_inverse_fft_run_measurements_0_CUFFT_EXECUTE_INVER__0 = (char*) (Shared + 5368709120); // delta_0_inverse_fft_run_measurements_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0 > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0 size:= 1073741824*char
char *const delta_0_inverse_fft_run_measurements_0_fft_shift_complex_t__1 = (char*) (Shared + 4294967296); // delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 1073741824*char
char *const delta_0_convolution_correction_run_0_execute_convolution_c__0 = (char*) (Shared + 5368709120); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 > delta_0_subtract_image_space_0 size:= 1073741824*char
char *const delta_0_subtract_image_space_0__sink_0_0__0 = (char*) (Shared + 0); // delta_0_subtract_image_space_0 > sink_0_0 size:= 1073741824*char
char *const delta_0_correct_to_finegrid_0_correct_to_finegrid_0__delta__0 = (char*) (Shared + 5368709120); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0 > delta_0_split_s2s_0 size:= 1962244*char
char *const src_1_0__delta_0_correct_to_finegrid_0_apply_gains_0__0 = (char*) (Shared + 5368709120); // src_1_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 981120*char
char *const src_6_0__delta_0_correct_to_finegrid_0_correct_to_finegrid__0 = (char*) (Shared + 5370671364); // src_6_0 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0 size:= 981120*char
char *const delta_0_correct_to_finegrid_0_apply_gains_0__delta_0_corre__0 = (char*) (Shared + 5371652484); // delta_0_correct_to_finegrid_0_apply_gains_0 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0 size:= 981120*char
char *const delta_0_split_s2s_0__delta_0_explode_delta_0_split_s2s_0_o__0 = (char*) (Shared + 5370671364); // delta_0_split_s2s_0 > delta_0_explode_delta_0_split_s2s_0_out_vis_coords size:= 981120*char
char *const delta_0_split_s2s_0__delta_0_explode_delta_0_split_s2s_0_o__1 = (char*) (Shared + 5371652484); // delta_0_split_s2s_0 > delta_0_explode_delta_0_split_s2s_0_output_visibilities size:= 981120*char
char *const delta_0_explode_delta_0_split_s2s_0_out_vis_coords__delta___0 = (char*) (Shared + 5368709120); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords > delta_0_Broadcast_corrected_viscoords_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_out_vis_coords__delta___1 = (char*) (Shared + 6442450944); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords > delta_0_Broadcast_corrected_viscoords_1 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_out_vis_coords__delta___2 = (char*) (Shared + 6442696224); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords > delta_0_Broadcast_corrected_viscoords_2 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_out_vis_coords__delta___3 = (char*) (Shared + 6442941504); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords > delta_0_Broadcast_corrected_viscoords_3 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_output_visibilities__d__0 = (char*) (Shared + 6443186784); // delta_0_explode_delta_0_split_s2s_0_output_visibilities > delta_0_grid_0 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_output_visibilities__d__1 = (char*) (Shared + 6443432064); // delta_0_explode_delta_0_split_s2s_0_output_visibilities > delta_0_grid_1 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_output_visibilities__d__2 = (char*) (Shared + 6443677344); // delta_0_explode_delta_0_split_s2s_0_output_visibilities > delta_0_grid_2 size:= 245280*char
char *const delta_0_explode_delta_0_split_s2s_0_output_visibilities__d__3 = (char*) (Shared + 6443922624); // delta_0_explode_delta_0_split_s2s_0_output_visibilities > delta_0_grid_3 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_0__delta_0_g2g_degri__0 = (char*) (Shared + 24696061952); // delta_0_Broadcast_corrected_viscoords_0 > delta_0_g2g_degridgrid_0 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_0__delta_0_grid_0__0 = (char*) (Shared + 6444167904); // delta_0_Broadcast_corrected_viscoords_0 > delta_0_grid_0 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_1__delta_0_g2g_degri__0 = (char*) (Shared + 24696307232); // delta_0_Broadcast_corrected_viscoords_1 > delta_0_g2g_degridgrid_1 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_1__delta_0_grid_1__0 = (char*) (Shared + 6444413184); // delta_0_Broadcast_corrected_viscoords_1 > delta_0_grid_1 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_2__delta_0_g2g_degri__0 = (char*) (Shared + 24696552512); // delta_0_Broadcast_corrected_viscoords_2 > delta_0_g2g_degridgrid_2 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_2__delta_0_grid_2__0 = (char*) (Shared + 6444658464); // delta_0_Broadcast_corrected_viscoords_2 > delta_0_grid_2 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_3__delta_0_g2g_degri__0 = (char*) (Shared + 24696797792); // delta_0_Broadcast_corrected_viscoords_3 > delta_0_g2g_degridgrid_3 size:= 245280*char
char *const delta_0_Broadcast_corrected_viscoords_3__delta_0_grid_3__0 = (char*) (Shared + 6444903744); // delta_0_Broadcast_corrected_viscoords_3 > delta_0_grid_3 size:= 245280*char
char *const src_8_0__delta_0_correct_to_finegrid_0_apply_gains_0__0 = (char*) (Shared + 5369690240); // src_8_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 130816*char
char *const src_5_0__BR_delta_0__gridding_kernels__0 = (char*) (Shared + 5372633604); // src_5_0 > BR_delta_0__gridding_kernels size:= 108800*char
char *const src_14_0__BR_delta_0__degridding_kernels__0 = (char*) (Shared + 15032385536); // src_14_0 > BR_delta_0__degridding_kernels size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_Broadcast_gridding_k__0 = (char*) (Shared + 5372742404); // BR_delta_0__gridding_kernels > delta_0_Broadcast_gridding_kernels_0 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_Broadcast_gridding_k__1 = (char*) (Shared + 6445149024); // BR_delta_0__gridding_kernels > delta_0_Broadcast_gridding_kernels_1 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_Broadcast_gridding_k__2 = (char*) (Shared + 6445257824); // BR_delta_0__gridding_kernels > delta_0_Broadcast_gridding_kernels_2 size:= 108800*char
char *const BR_delta_0__gridding_kernels__delta_0_Broadcast_gridding_k__3 = (char*) (Shared + 6445366624); // BR_delta_0__gridding_kernels > delta_0_Broadcast_gridding_kernels_3 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_g2g_degridgrid_0__0 = (char*) (Shared + 24697043072); // BR_delta_0__degridding_kernels > delta_0_g2g_degridgrid_0 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_g2g_degridgrid_1__0 = (char*) (Shared + 24697151872); // BR_delta_0__degridding_kernels > delta_0_g2g_degridgrid_1 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_g2g_degridgrid_2__0 = (char*) (Shared + 24697260672); // BR_delta_0__degridding_kernels > delta_0_g2g_degridgrid_2 size:= 108800*char
char *const BR_delta_0__degridding_kernels__delta_0_g2g_degridgrid_3__0 = (char*) (Shared + 24697369472); // BR_delta_0__degridding_kernels > delta_0_g2g_degridgrid_3 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_0__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697478272); // delta_0_Broadcast_gridding_kernels_0 > delta_0_g2g_degridgrid_0 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_0__delta_0_grid_0__0 = (char*) (Shared + 6445475424); // delta_0_Broadcast_gridding_kernels_0 > delta_0_grid_0 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_1__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697587072); // delta_0_Broadcast_gridding_kernels_1 > delta_0_g2g_degridgrid_1 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_1__delta_0_grid_1__0 = (char*) (Shared + 6445584224); // delta_0_Broadcast_gridding_kernels_1 > delta_0_grid_1 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_2__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697695872); // delta_0_Broadcast_gridding_kernels_2 > delta_0_g2g_degridgrid_2 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_2__delta_0_grid_2__0 = (char*) (Shared + 6445693024); // delta_0_Broadcast_gridding_kernels_2 > delta_0_grid_2 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_3__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697804672); // delta_0_Broadcast_gridding_kernels_3 > delta_0_g2g_degridgrid_3 size:= 108800*char
char *const delta_0_Broadcast_gridding_kernels_3__delta_0_grid_3__0 = (char*) (Shared + 6445801824); // delta_0_Broadcast_gridding_kernels_3 > delta_0_grid_3 size:= 108800*char
char *const src_11_0__delta_0_Broadcast_prolate_0__0 = (char*) (Shared + 2147483648); // src_11_0 > delta_0_Broadcast_prolate_0 size:= 16384*char
char *const delta_0_Broadcast_prolate_0__delta_0_inv_conv_correction_0__0 = (char*) (Shared + 2147500032); // delta_0_Broadcast_prolate_0 > delta_0_inv_conv_correction_0 size:= 16384*char
char *const delta_0_Broadcast_prolate_0__delta_0_convolution_correctio__0 = (char*) (Shared + 24697913472); // delta_0_Broadcast_prolate_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 16384*char
char *const delta_0_Broadcast_prolate_0__delta_0_convolution_correctio__1 = (char*) (Shared + 24697929856); // delta_0_Broadcast_prolate_0 > delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0 size:= 16384*char
char *const src_7_0__delta_0_correct_to_finegrid_0_reciprocal_transfor__0 = (char*) (Shared + 5369821056); // src_7_0 > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0 size:= 512*char
char *const delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0__0 = (char*) (Shared + 5369821568); // delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 512*char
char *const src_2_0__delta_0_source_list_sink_0__0 = (char*) (Shared + 24697946240); // src_2_0 > delta_0_source_list_sink_0 size:= 200*char
char *const src_4_0__BR_delta_0__gridding_kernel_supports__0 = (char*) (Shared + 5372851204); // src_4_0 > BR_delta_0__gridding_kernel_supports size:= 17*char
char *const src_13_0__BR_delta_0__degridding_kernel_supports__0 = (char*) (Shared + 15032494336); // src_13_0 > BR_delta_0__degridding_kernel_supports size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_Broadcast_gr__0 = (char*) (Shared + 5372851221); // BR_delta_0__gridding_kernel_supports > delta_0_Broadcast_gridding_kernel_supports_0 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_Broadcast_gr__1 = (char*) (Shared + 6445910624); // BR_delta_0__gridding_kernel_supports > delta_0_Broadcast_gridding_kernel_supports_1 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_Broadcast_gr__2 = (char*) (Shared + 6445910641); // BR_delta_0__gridding_kernel_supports > delta_0_Broadcast_gridding_kernel_supports_2 size:= 17*char
char *const BR_delta_0__gridding_kernel_supports__delta_0_Broadcast_gr__3 = (char*) (Shared + 6445910658); // BR_delta_0__gridding_kernel_supports > delta_0_Broadcast_gridding_kernel_supports_3 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_g2g_degrid__0 = (char*) (Shared + 24697946440); // BR_delta_0__degridding_kernel_supports > delta_0_g2g_degridgrid_0 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_g2g_degrid__1 = (char*) (Shared + 24697946457); // BR_delta_0__degridding_kernel_supports > delta_0_g2g_degridgrid_1 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_g2g_degrid__2 = (char*) (Shared + 24697946474); // BR_delta_0__degridding_kernel_supports > delta_0_g2g_degridgrid_2 size:= 17*char
char *const BR_delta_0__degridding_kernel_supports__delta_0_g2g_degrid__3 = (char*) (Shared + 24697946491); // BR_delta_0__degridding_kernel_supports > delta_0_g2g_degridgrid_3 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_0__delta_0_g2g___0 = (char*) (Shared + 24697946508); // delta_0_Broadcast_gridding_kernel_supports_0 > delta_0_g2g_degridgrid_0 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_0__delta_0_grid__0 = (char*) (Shared + 6445910675); // delta_0_Broadcast_gridding_kernel_supports_0 > delta_0_grid_0 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_1__delta_0_g2g___0 = (char*) (Shared + 24697946525); // delta_0_Broadcast_gridding_kernel_supports_1 > delta_0_g2g_degridgrid_1 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_1__delta_0_grid__0 = (char*) (Shared + 6445910692); // delta_0_Broadcast_gridding_kernel_supports_1 > delta_0_grid_1 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_2__delta_0_g2g___0 = (char*) (Shared + 24697946542); // delta_0_Broadcast_gridding_kernel_supports_2 > delta_0_g2g_degridgrid_2 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_2__delta_0_grid__0 = (char*) (Shared + 6445910709); // delta_0_Broadcast_gridding_kernel_supports_2 > delta_0_grid_2 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_3__delta_0_g2g___0 = (char*) (Shared + 24697946559); // delta_0_Broadcast_gridding_kernel_supports_3 > delta_0_g2g_degridgrid_3 size:= 17*char
char *const delta_0_Broadcast_gridding_kernel_supports_3__delta_0_grid__0 = (char*) (Shared + 6445910726); // delta_0_Broadcast_gridding_kernel_supports_3 > delta_0_grid_3 size:= 17*char
char *const delta_0_split_s2s_0__delta_0_explode_delta_0_split_s2s_0_n__0 = (char*) (Shared + 5372851238); // delta_0_split_s2s_0 > delta_0_explode_delta_0_split_s2s_0_num_vis size:= 16*char
char *const delta_0_split_s2s_0__delta_0_explode_delta_0_split_s2s_0_m__0 = (char*) (Shared + 5372851254); // delta_0_split_s2s_0 > delta_0_explode_delta_0_split_s2s_0_maj_iter_out size:= 16*char
char *const src_3_0__delta_0_source_list_sink_0__0 = (char*) (Shared + 24697946576); // src_3_0 > delta_0_source_list_sink_0 size:= 4*char
char *const src_12_0__delta_0_split_s2s_0__0 = (char*) (Shared + 5372851270); // src_12_0 > delta_0_split_s2s_0 size:= 4*char
char *const delta_0_split_s2s_0__delta_0_explode_delta_0_split_s2s_0_o__2 = (char*) (Shared + 5372851274); // delta_0_split_s2s_0 > delta_0_explode_delta_0_split_s2s_0_output_configs size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_num_vis__delta_0_Broad__0 = (char*) (Shared + 5368954400); // delta_0_explode_delta_0_split_s2s_0_num_vis > delta_0_Broadcast_num_visibilities_0 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_num_vis__delta_0_Broad__1 = (char*) (Shared + 6445910743); // delta_0_explode_delta_0_split_s2s_0_num_vis > delta_0_Broadcast_num_visibilities_1 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_num_vis__delta_0_Broad__2 = (char*) (Shared + 6445910747); // delta_0_explode_delta_0_split_s2s_0_num_vis > delta_0_Broadcast_num_visibilities_2 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_num_vis__delta_0_Broad__3 = (char*) (Shared + 6445910751); // delta_0_explode_delta_0_split_s2s_0_num_vis > delta_0_Broadcast_num_visibilities_3 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_maj_iter_out__delta_0___0 = (char*) (Shared + 6445910755); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out > delta_0_grid_0 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_maj_iter_out__delta_0___1 = (char*) (Shared + 6445910759); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out > delta_0_grid_1 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_maj_iter_out__delta_0___2 = (char*) (Shared + 6445910763); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out > delta_0_grid_2 size:= 4*char
char *const delta_0_explode_delta_0_split_s2s_0_maj_iter_out__delta_0___3 = (char*) (Shared + 6445910767); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out > delta_0_grid_3 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_0__delta_0_grid_0__0 = (char*) (Shared + 6445910771); // delta_0_Broadcast_num_visibilities_0 > delta_0_grid_0 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_0__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697946580); // delta_0_Broadcast_num_visibilities_0 > delta_0_g2g_degridgrid_0 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_1__delta_0_grid_1__0 = (char*) (Shared + 6445910775); // delta_0_Broadcast_num_visibilities_1 > delta_0_grid_1 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_1__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697946584); // delta_0_Broadcast_num_visibilities_1 > delta_0_g2g_degridgrid_1 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_2__delta_0_grid_2__0 = (char*) (Shared + 6445910779); // delta_0_Broadcast_num_visibilities_2 > delta_0_grid_2 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_2__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697946588); // delta_0_Broadcast_num_visibilities_2 > delta_0_g2g_degridgrid_2 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_3__delta_0_grid_3__0 = (char*) (Shared + 6445910783); // delta_0_Broadcast_num_visibilities_3 > delta_0_grid_3 size:= 4*char
char *const delta_0_Broadcast_num_visibilities_3__delta_0_g2g_degridgr__0 = (char*) (Shared + 24697946592); // delta_0_Broadcast_num_visibilities_3 > delta_0_g2g_degridgrid_3 size:= 4*char
char *const src_9_0__delta_0_Broadcast_config_0__0 = (char*) (Shared + 2147516416); // src_9_0 > delta_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_fft_run_0_Broadcast_co__0 = (char*) (Shared + 2147516417); // delta_0_Broadcast_config_0 > delta_0_fft_run_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_inverse_fft_run_estima__0 = (char*) (Shared + 24697946596); // delta_0_Broadcast_config_0 > delta_0_inverse_fft_run_estimation_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_correct_to_finegrid_0___0 = (char*) (Shared + 5369821568); // delta_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_convolution_correction__0 = (char*) (Shared + 24697946597); // delta_0_Broadcast_config_0 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_inv_conv_correction_0__0 = (char*) (Shared + 2147516418); // delta_0_Broadcast_config_0 > delta_0_inv_conv_correction_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_inverse_fft_run_measur__0 = (char*) (Shared + 24697946598); // delta_0_Broadcast_config_0 > delta_0_inverse_fft_run_measurements_0_Broadcast_config_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_convolution_correction__1 = (char*) (Shared + 24697946599); // delta_0_Broadcast_config_0 > delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0 size:= 1*char
char *const delta_0_Broadcast_config_0__delta_0_split_s2s_0__0 = (char*) (Shared + 5372851278); // delta_0_Broadcast_config_0 > delta_0_split_s2s_0 size:= 1*char
char *const delta_0_fft_run_0_Broadcast_config_0__delta_0_fft_run_0_ff__0 = (char*) (Shared + 2147516416); // delta_0_fft_run_0_Broadcast_config_0 > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0 size:= 1*char
char *const delta_0_fft_run_0_Broadcast_config_0__delta_0_fft_run_0_ff__1 = (char*) (Shared + 2147516419); // delta_0_fft_run_0_Broadcast_config_0 > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0 size:= 1*char
char *const delta_0_inverse_fft_run_estimation_0_Broadcast_config_0__d__0 = (char*) (Shared + 24697946600); // delta_0_inverse_fft_run_estimation_0_Broadcast_config_0 > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0 size:= 1*char
char *const delta_0_inverse_fft_run_estimation_0_Broadcast_config_0__d__1 = (char*) (Shared + 24697946601); // delta_0_inverse_fft_run_estimation_0_Broadcast_config_0 > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0 size:= 1*char
char *const delta_0_correct_to_finegrid_0_Broadcast_config_0__delta_0___0 = (char*) (Shared + 5369822080); // delta_0_correct_to_finegrid_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0 size:= 1*char
char *const delta_0_correct_to_finegrid_0_Broadcast_config_0__delta_0___1 = (char*) (Shared + 5369822081); // delta_0_correct_to_finegrid_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_apply_gains_0 size:= 1*char
char *const delta_0_correct_to_finegrid_0_Broadcast_config_0__delta_0___2 = (char*) (Shared + 5372851238); // delta_0_correct_to_finegrid_0_Broadcast_config_0 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0 size:= 1*char
char *const delta_0_inverse_fft_run_measurements_0_Broadcast_config_0___0 = (char*) (Shared + 24697946602); // delta_0_inverse_fft_run_measurements_0_Broadcast_config_0 > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0 size:= 1*char
char *const delta_0_inverse_fft_run_measurements_0_Broadcast_config_0___1 = (char*) (Shared + 24697946603); // delta_0_inverse_fft_run_measurements_0_Broadcast_config_0 > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0 size:= 1*char
char *const delta_0_explode_delta_0_split_s2s_0_output_configs__delta___0 = (char*) (Shared + 5368954404); // delta_0_explode_delta_0_split_s2s_0_output_configs > delta_0_Broadcast_configs_0 size:= 1*char
char *const delta_0_explode_delta_0_split_s2s_0_output_configs__delta___1 = (char*) (Shared + 6445910787); // delta_0_explode_delta_0_split_s2s_0_output_configs > delta_0_Broadcast_configs_1 size:= 1*char
char *const delta_0_explode_delta_0_split_s2s_0_output_configs__delta___2 = (char*) (Shared + 6445910788); // delta_0_explode_delta_0_split_s2s_0_output_configs > delta_0_Broadcast_configs_2 size:= 1*char
char *const delta_0_explode_delta_0_split_s2s_0_output_configs__delta___3 = (char*) (Shared + 6445910789); // delta_0_explode_delta_0_split_s2s_0_output_configs > delta_0_Broadcast_configs_3 size:= 1*char
char *const delta_0_Broadcast_configs_0__delta_0_grid_0__0 = (char*) (Shared + 6445910790); // delta_0_Broadcast_configs_0 > delta_0_grid_0 size:= 1*char
char *const delta_0_Broadcast_configs_0__delta_0_g2g_degridgrid_0__0 = (char*) (Shared + 24697946604); // delta_0_Broadcast_configs_0 > delta_0_g2g_degridgrid_0 size:= 1*char
char *const delta_0_Broadcast_configs_1__delta_0_grid_1__0 = (char*) (Shared + 6445910791); // delta_0_Broadcast_configs_1 > delta_0_grid_1 size:= 1*char
char *const delta_0_Broadcast_configs_1__delta_0_g2g_degridgrid_1__0 = (char*) (Shared + 24697946605); // delta_0_Broadcast_configs_1 > delta_0_g2g_degridgrid_1 size:= 1*char
char *const delta_0_Broadcast_configs_2__delta_0_grid_2__0 = (char*) (Shared + 6445910792); // delta_0_Broadcast_configs_2 > delta_0_grid_2 size:= 1*char
char *const delta_0_Broadcast_configs_2__delta_0_g2g_degridgrid_2__0 = (char*) (Shared + 24697946606); // delta_0_Broadcast_configs_2 > delta_0_g2g_degridgrid_2 size:= 1*char
char *const delta_0_Broadcast_configs_3__delta_0_grid_3__0 = (char*) (Shared + 6445910793); // delta_0_Broadcast_configs_3 > delta_0_grid_3 size:= 1*char
char *const delta_0_Broadcast_configs_3__delta_0_g2g_degridgrid_3__0 = (char*) (Shared + 24697946607); // delta_0_Broadcast_configs_3 > delta_0_g2g_degridgrid_3 size:= 1*char
PRECISION2 *const output_grid__input_grid__0 = (PRECISION2*) (Shared + 0); // delta_0_split_uvgrid_0_output_grid > delta_0_explode_delta_0_split_uvgrid_0_output_grid_input_grid size:= 4294967296*PRECISION2
PRECISION2 *const output_grid__grids__0 = (PRECISION2*) (Shared + 0); // delta_0_implode_delta_0_merge_estimate_grid_0_grids_output_grid > delta_0_merge_estimate_grid_0_grids size:= 4294967296*PRECISION2
PRECISION2 *const merge__grids__0 = (PRECISION2*) (Shared + 4294967296); // delta_0_implode_delta_0_merge_measurement_grid_0_grids_merge > delta_0_merge_measurement_grid_0_grids size:= 4294967296*PRECISION2
PRECISION2 *const prev_grid__prev_grid__0 = (PRECISION2*) (Shared + 4294967296); // delta_init_in_grid_prev_grid_prev_grid > delta_0_grid_0_prev_grid size:= 1073741824*PRECISION2
PRECISION *const out__input__0 = (PRECISION*) (Shared + 0); // src_0_0_out > delta_0_Broadcast_image_estimate_0_input size:= 1073741824*PRECISION
PRECISION *const out__psf__0 = (PRECISION*) (Shared + 8589934592); // src_10_0_out > delta_0_psf_sink_0_psf size:= 1073741824*PRECISION
PRECISION *const fft_run_0__dirty_image_in__0 = (PRECISION*) (Shared + 1073741824); // delta_0_Broadcast_image_estimate_0_fft_run_0 > delta_0_inv_conv_correction_0_dirty_image_in size:= 1073741824*PRECISION
PRECISION *const output_1__in__0 = (PRECISION*) (Shared + 9663676416); // delta_0_Broadcast_image_estimate_0_output_1 > sink_1_0_in size:= 1073741824*PRECISION
PRECISION *const dirty_image_out__image__0 = (PRECISION*) (Shared + 0); // delta_0_inv_conv_correction_0_dirty_image_out > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0_image size:= 1073741824*PRECISION
PRECISION2 *const fourier__uv_grid_in__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_fft_run_0_fft_shift_real_to_complex_actor_0_fourier > delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid_in__0 = (PRECISION2*) (Shared + 0); // delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0_uv_grid_out > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__input_grid__0 = (PRECISION2*) (Shared + 10737418240); // delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0_uv_grid_out > delta_0_split_uvgrid_0_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_0__input_grid__0 = (PRECISION2*) (Shared + 10737418240); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_0 > delta_0_g2g_degridgrid_0_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_1__input_grid__0 = (PRECISION2*) (Shared + 11811160064); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_1 > delta_0_g2g_degridgrid_1_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_2__input_grid__0 = (PRECISION2*) (Shared + 12884901888); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_2 > delta_0_g2g_degridgrid_2_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid_3__input_grid__0 = (PRECISION2*) (Shared + 13958643712); // delta_0_explode_delta_0_split_uvgrid_0_output_grid_output_grid_3 > delta_0_g2g_degridgrid_3_input_grid size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__input__0 = (PRECISION2*) (Shared + 5368709120); // delta_0_grid_0_output_grid > delta_0_Broadcast_gridded_measured_0_input size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_0__0 = (PRECISION2*) (Shared + 15032385536); // delta_0_g2g_degridgrid_0_output_grid > delta_0_implode_delta_0_merge_estimate_grid_0_grids_grids_0 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_1__0 = (PRECISION2*) (Shared + 16106127360); // delta_0_g2g_degridgrid_1_output_grid > delta_0_implode_delta_0_merge_estimate_grid_0_grids_grids_1 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_2__0 = (PRECISION2*) (Shared + 17179869184); // delta_0_g2g_degridgrid_2_output_grid > delta_0_implode_delta_0_merge_estimate_grid_0_grids_grids_2 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__grids_3__0 = (PRECISION2*) (Shared + 18253611008); // delta_0_g2g_degridgrid_3_output_grid > delta_0_implode_delta_0_merge_estimate_grid_0_grids_grids_3 size:= 1073741824*PRECISION2
PRECISION2 *const prev_1__prev_grid__0 = (PRECISION2*) (Shared + 4294967296); // delta_0_Broadcast_gridded_measured_0_prev_1 > delta_0_grid_1_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const merge_0__grids_0__0 = (PRECISION2*) (Shared + 19327352832); // delta_0_Broadcast_gridded_measured_0_merge_0 > delta_0_implode_delta_0_merge_measurement_grid_0_grids_grids_0 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__input__1 = (PRECISION2*) (Shared + 5368709120); // delta_0_grid_1_output_grid > delta_0_Broadcast_gridded_measured_1_input size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__uv_grid_in__0 = (PRECISION2*) (Shared + 10737418240); // delta_0_merge_estimate_grid_0_output_grid > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const prev_1__prev_grid__1 = (PRECISION2*) (Shared + 4294967296); // delta_0_Broadcast_gridded_measured_1_prev_1 > delta_0_grid_2_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const merge_0__grids_1__0 = (PRECISION2*) (Shared + 20401094656); // delta_0_Broadcast_gridded_measured_1_merge_0 > delta_0_implode_delta_0_merge_measurement_grid_0_grids_grids_1 size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid_in__1 = (PRECISION2*) (Shared + 0); // delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0_uv_grid_out > delta_0_inverse_fft_run_estimation_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__input__2 = (PRECISION2*) (Shared + 5368709120); // delta_0_grid_2_output_grid > delta_0_Broadcast_gridded_measured_2_input size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid__0 = (PRECISION2*) (Shared + 1073741824); // delta_0_inverse_fft_run_estimation_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_out > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0_uv_grid size:= 1073741824*PRECISION2
PRECISION2 *const prev_1__prev_grid__2 = (PRECISION2*) (Shared + 4294967296); // delta_0_Broadcast_gridded_measured_2_prev_1 > delta_0_grid_3_prev_grid size:= 1073741824*PRECISION2
PRECISION2 *const merge_0__grids_2__0 = (PRECISION2*) (Shared + 21474836480); // delta_0_Broadcast_gridded_measured_2_merge_0 > delta_0_implode_delta_0_merge_measurement_grid_0_grids_grids_2 size:= 1073741824*PRECISION2
PRECISION *const dirty_image__dirty_image_in__0 = (PRECISION*) (Shared + 0); // delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0_dirty_image > delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0_dirty_image_in size:= 1073741824*PRECISION
PRECISION2 *const output_grid__input__3 = (PRECISION2*) (Shared + 5368709120); // delta_0_grid_3_output_grid > delta_0_Broadcast_gridded_measured_3_input size:= 1073741824*PRECISION2
PRECISION *const dirty_image_out__estimate__0 = (PRECISION*) (Shared + 1073741824); // delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0_dirty_image_out > delta_0_subtract_image_space_0_estimate size:= 1073741824*PRECISION
PRECISION2 *const merge_0__grids_3__0 = (PRECISION2*) (Shared + 22548578304); // delta_0_Broadcast_gridded_measured_3_merge_0 > delta_0_implode_delta_0_merge_measurement_grid_0_grids_grids_3 size:= 1073741824*PRECISION2
PRECISION2 *const prev_1_1__prev_1__0 = (PRECISION2*) (Shared + 23622320128); // delta_0_Broadcast_gridded_measured_3_prev_1_1 > delta_end_out_Broadcast_gridded_measured_prev_prev_1 size:= 1073741824*PRECISION2
PRECISION2 *const output_grid__uv_grid_in__1 = (PRECISION2*) (Shared + 19327352832); // delta_0_merge_measurement_grid_0_output_grid > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid_in__2 = (PRECISION2*) (Shared + 4294967296); // delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0_uv_grid_out > delta_0_inverse_fft_run_measurements_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_in size:= 1073741824*PRECISION2
PRECISION2 *const uv_grid_out__uv_grid__1 = (PRECISION2*) (Shared + 5368709120); // delta_0_inverse_fft_run_measurements_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0_uv_grid_out > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0_uv_grid size:= 1073741824*PRECISION2
PRECISION *const dirty_image__dirty_image_in__1 = (PRECISION*) (Shared + 4294967296); // delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0_dirty_image > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_dirty_image_in size:= 1073741824*PRECISION
PRECISION *const dirty_image_out__measurements__0 = (PRECISION*) (Shared + 5368709120); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_dirty_image_out > delta_0_subtract_image_space_0_measurements size:= 1073741824*PRECISION
PRECISION *const result__in__0 = (PRECISION*) (Shared + 0); // delta_0_subtract_image_space_0_result > sink_0_0_in size:= 1073741824*PRECISION
PRECISION2 *const output_visibilities__measured_visibilities__0 = (PRECISION2*) (Shared + 5368709120); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0_output_visibilities > delta_0_split_s2s_0_measured_visibilities size:= 981120*PRECISION2
PRECISION3 *const output_finegrid_vis_coords__vis_coords__0 = (PRECISION3*) (Shared + 5369690240); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0_output_finegrid_vis_coords > delta_0_split_s2s_0_vis_coords size:= 981120*PRECISION3
int *const num_output_visibilities__num_corrected_vis__0 = (int*) (Shared + 5370671360); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0_num_output_visibilities > delta_0_split_s2s_0_num_corrected_vis size:= 1*int
PRECISION2 *const out__measured_vis__0 = (PRECISION2*) (Shared + 5368709120); // src_1_0_out > delta_0_correct_to_finegrid_0_apply_gains_0_measured_vis size:= 981120*PRECISION2
PRECISION3 *const out__vis_uvw_coords__0 = (PRECISION3*) (Shared + 5370671364); // src_6_0_out > delta_0_correct_to_finegrid_0_correct_to_finegrid_0_vis_uvw_coords size:= 981120*PRECISION3
PRECISION2 *const visibilities_out__input_visibilities__0 = (PRECISION2*) (Shared + 5371652484); // delta_0_correct_to_finegrid_0_apply_gains_0_visibilities_out > delta_0_correct_to_finegrid_0_correct_to_finegrid_0_input_visibilities size:= 981120*PRECISION2
PRECISION3 *const out_vis_coords__input__0 = (PRECISION3*) (Shared + 5370671364); // delta_0_split_s2s_0_out_vis_coords > delta_0_explode_delta_0_split_s2s_0_out_vis_coords_input size:= 981120*PRECISION3
PRECISION2 *const output_visibilities__visibilities__0 = (PRECISION2*) (Shared + 5371652484); // delta_0_split_s2s_0_output_visibilities > delta_0_explode_delta_0_split_s2s_0_output_visibilities_visibilities size:= 981120*PRECISION2
PRECISION3 *const out_vis_coords_0__input__0 = (PRECISION3*) (Shared + 5368709120); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords_out_vis_coords_0 > delta_0_Broadcast_corrected_viscoords_0_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_1__input__0 = (PRECISION3*) (Shared + 6442450944); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords_out_vis_coords_1 > delta_0_Broadcast_corrected_viscoords_1_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_2__input__0 = (PRECISION3*) (Shared + 6442696224); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords_out_vis_coords_2 > delta_0_Broadcast_corrected_viscoords_2_input size:= 245280*PRECISION3
PRECISION3 *const out_vis_coords_3__input__0 = (PRECISION3*) (Shared + 6442941504); // delta_0_explode_delta_0_split_s2s_0_out_vis_coords_out_vis_coords_3 > delta_0_Broadcast_corrected_viscoords_3_input size:= 245280*PRECISION3
PRECISION2 *const output_visibilities_0__visibilities__0 = (PRECISION2*) (Shared + 6443186784); // delta_0_explode_delta_0_split_s2s_0_output_visibilities_output_visibilities_0 > delta_0_grid_0_visibilities size:= 245280*PRECISION2
PRECISION2 *const output_visibilities_1__visibilities__0 = (PRECISION2*) (Shared + 6443432064); // delta_0_explode_delta_0_split_s2s_0_output_visibilities_output_visibilities_1 > delta_0_grid_1_visibilities size:= 245280*PRECISION2
PRECISION2 *const output_visibilities_2__visibilities__0 = (PRECISION2*) (Shared + 6443677344); // delta_0_explode_delta_0_split_s2s_0_output_visibilities_output_visibilities_2 > delta_0_grid_2_visibilities size:= 245280*PRECISION2
PRECISION2 *const output_visibilities_3__visibilities__0 = (PRECISION2*) (Shared + 6443922624); // delta_0_explode_delta_0_split_s2s_0_output_visibilities_output_visibilities_3 > delta_0_grid_3_visibilities size:= 245280*PRECISION2
PRECISION3 *const g2g_0__corrected_vis_uvw_coords__0 = (PRECISION3*) (Shared + 24696061952); // delta_0_Broadcast_corrected_viscoords_0_g2g_0 > delta_0_g2g_degridgrid_0_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_measured_1__corrected_vis_uvw_coords__0 = (PRECISION3*) (Shared + 6444167904); // delta_0_Broadcast_corrected_viscoords_0_grid_measured_1 > delta_0_grid_0_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const g2g_0__corrected_vis_uvw_coords__1 = (PRECISION3*) (Shared + 24696307232); // delta_0_Broadcast_corrected_viscoords_1_g2g_0 > delta_0_g2g_degridgrid_1_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_measured_1__corrected_vis_uvw_coords__1 = (PRECISION3*) (Shared + 6444413184); // delta_0_Broadcast_corrected_viscoords_1_grid_measured_1 > delta_0_grid_1_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const g2g_0__corrected_vis_uvw_coords__2 = (PRECISION3*) (Shared + 24696552512); // delta_0_Broadcast_corrected_viscoords_2_g2g_0 > delta_0_g2g_degridgrid_2_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_measured_1__corrected_vis_uvw_coords__2 = (PRECISION3*) (Shared + 6444658464); // delta_0_Broadcast_corrected_viscoords_2_grid_measured_1 > delta_0_grid_2_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const g2g_0__corrected_vis_uvw_coords__3 = (PRECISION3*) (Shared + 24696797792); // delta_0_Broadcast_corrected_viscoords_3_g2g_0 > delta_0_g2g_degridgrid_3_corrected_vis_uvw_coords size:= 245280*PRECISION3
PRECISION3 *const grid_measured_1__corrected_vis_uvw_coords__3 = (PRECISION3*) (Shared + 6444903744); // delta_0_Broadcast_corrected_viscoords_3_grid_measured_1 > delta_0_grid_3_corrected_vis_uvw_coords size:= 245280*PRECISION3
int2 *const out__receiver_pairs__0 = (int2*) (Shared + 5369690240); // src_8_0_out > delta_0_correct_to_finegrid_0_apply_gains_0_receiver_pairs size:= 130816*int2
PRECISION2 *const out__gridding_kernels__0 = (PRECISION2*) (Shared + 5372633604); // src_5_0_out > BR_delta_0__gridding_kernels_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const out__degridding_kernels__0 = (PRECISION2*) (Shared + 15032385536); // src_14_0_out > BR_delta_0__degridding_kernels_degridding_kernels size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_0_3__input__0 = (PRECISION2*) (Shared + 5372742404); // BR_delta_0__gridding_kernels_gridding_kernels_0_3 > delta_0_Broadcast_gridding_kernels_0_input size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_1_3__input__0 = (PRECISION2*) (Shared + 6445149024); // BR_delta_0__gridding_kernels_gridding_kernels_1_3 > delta_0_Broadcast_gridding_kernels_1_input size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_2_3__input__0 = (PRECISION2*) (Shared + 6445257824); // BR_delta_0__gridding_kernels_gridding_kernels_2_3 > delta_0_Broadcast_gridding_kernels_2_input size:= 108800*PRECISION2
PRECISION2 *const gridding_kernels_3_3__input__0 = (PRECISION2*) (Shared + 6445366624); // BR_delta_0__gridding_kernels_gridding_kernels_3_3 > delta_0_Broadcast_gridding_kernels_3_input size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_0_3__degridding_kernels__0 = (PRECISION2*) (Shared + 24697043072); // BR_delta_0__degridding_kernels_degridding_kernels_0_3 > delta_0_g2g_degridgrid_0_degridding_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_1_3__degridding_kernels__0 = (PRECISION2*) (Shared + 24697151872); // BR_delta_0__degridding_kernels_degridding_kernels_1_3 > delta_0_g2g_degridgrid_1_degridding_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_2_3__degridding_kernels__0 = (PRECISION2*) (Shared + 24697260672); // BR_delta_0__degridding_kernels_degridding_kernels_2_3 > delta_0_g2g_degridgrid_2_degridding_kernels size:= 108800*PRECISION2
PRECISION2 *const degridding_kernels_3_3__degridding_kernels__0 = (PRECISION2*) (Shared + 24697369472); // BR_delta_0__degridding_kernels_degridding_kernels_3_3 > delta_0_g2g_degridgrid_3_degridding_kernels size:= 108800*PRECISION2
PRECISION2 *const g2g_1__gridding_kernels__0 = (PRECISION2*) (Shared + 24697478272); // delta_0_Broadcast_gridding_kernels_0_g2g_1 > delta_0_g2g_degridgrid_0_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const grid_measured_0__kernels__0 = (PRECISION2*) (Shared + 6445475424); // delta_0_Broadcast_gridding_kernels_0_grid_measured_0 > delta_0_grid_0_kernels size:= 108800*PRECISION2
PRECISION2 *const g2g_1__gridding_kernels__1 = (PRECISION2*) (Shared + 24697587072); // delta_0_Broadcast_gridding_kernels_1_g2g_1 > delta_0_g2g_degridgrid_1_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const grid_measured_0__kernels__1 = (PRECISION2*) (Shared + 6445584224); // delta_0_Broadcast_gridding_kernels_1_grid_measured_0 > delta_0_grid_1_kernels size:= 108800*PRECISION2
PRECISION2 *const g2g_1__gridding_kernels__2 = (PRECISION2*) (Shared + 24697695872); // delta_0_Broadcast_gridding_kernels_2_g2g_1 > delta_0_g2g_degridgrid_2_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const grid_measured_0__kernels__2 = (PRECISION2*) (Shared + 6445693024); // delta_0_Broadcast_gridding_kernels_2_grid_measured_0 > delta_0_grid_2_kernels size:= 108800*PRECISION2
PRECISION2 *const g2g_1__gridding_kernels__3 = (PRECISION2*) (Shared + 24697804672); // delta_0_Broadcast_gridding_kernels_3_g2g_1 > delta_0_g2g_degridgrid_3_gridding_kernels size:= 108800*PRECISION2
PRECISION2 *const grid_measured_0__kernels__3 = (PRECISION2*) (Shared + 6445801824); // delta_0_Broadcast_gridding_kernels_3_grid_measured_0 > delta_0_grid_3_kernels size:= 108800*PRECISION2
PRECISION *const out__input__1 = (PRECISION*) (Shared + 2147483648); // src_11_0_out > delta_0_Broadcast_prolate_0_input size:= 16384*PRECISION
PRECISION *const inv_conv_correction_0__prolate__0 = (PRECISION*) (Shared + 2147500032); // delta_0_Broadcast_prolate_0_inv_conv_correction_0 > delta_0_inv_conv_correction_0_prolate size:= 16384*PRECISION
PRECISION *const conv_correction_1__prolate__0 = (PRECISION*) (Shared + 24697913472); // delta_0_Broadcast_prolate_0_conv_correction_1 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_prolate size:= 16384*PRECISION
PRECISION *const conv_correction_est_2__prolate__0 = (PRECISION*) (Shared + 24697929856); // delta_0_Broadcast_prolate_0_conv_correction_est_2 > delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0_prolate size:= 16384*PRECISION
PRECISION2 *const out__gains_in__0 = (PRECISION2*) (Shared + 5369821056); // src_7_0_out > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0_gains_in size:= 512*PRECISION2
PRECISION2 *const gains_out__gains__0 = (PRECISION2*) (Shared + 5369821568); // delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0_gains_out > delta_0_correct_to_finegrid_0_apply_gains_0_gains size:= 512*PRECISION2
PRECISION3 *const out__source_list__0 = (PRECISION3*) (Shared + 24697946240); // src_2_0_out > delta_0_source_list_sink_0_source_list size:= 200*PRECISION3
int2 *const out__gridding_kernel_supports__0 = (int2*) (Shared + 5372851204); // src_4_0_out > BR_delta_0__gridding_kernel_supports_gridding_kernel_supports size:= 17*int2
int2 *const out__degridding_kernel_supports__0 = (int2*) (Shared + 15032494336); // src_13_0_out > BR_delta_0__degridding_kernel_supports_degridding_kernel_supports size:= 17*int2
int2 *const gridding_kernel_supports_0_3__input__0 = (int2*) (Shared + 5372851221); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_0_3 > delta_0_Broadcast_gridding_kernel_supports_0_input size:= 17*int2
int2 *const gridding_kernel_supports_1_3__input__0 = (int2*) (Shared + 6445910624); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_1_3 > delta_0_Broadcast_gridding_kernel_supports_1_input size:= 17*int2
int2 *const gridding_kernel_supports_2_3__input__0 = (int2*) (Shared + 6445910641); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_2_3 > delta_0_Broadcast_gridding_kernel_supports_2_input size:= 17*int2
int2 *const gridding_kernel_supports_3_3__input__0 = (int2*) (Shared + 6445910658); // BR_delta_0__gridding_kernel_supports_gridding_kernel_supports_3_3 > delta_0_Broadcast_gridding_kernel_supports_3_input size:= 17*int2
int2 *const degridding_kernel_supports_0_3__degridding_kernel_supports__0 = (int2*) (Shared + 24697946440); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_0_3 > delta_0_g2g_degridgrid_0_degridding_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_1_3__degridding_kernel_supports__0 = (int2*) (Shared + 24697946457); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_1_3 > delta_0_g2g_degridgrid_1_degridding_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_2_3__degridding_kernel_supports__0 = (int2*) (Shared + 24697946474); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_2_3 > delta_0_g2g_degridgrid_2_degridding_kernel_supports size:= 17*int2
int2 *const degridding_kernel_supports_3_3__degridding_kernel_supports__0 = (int2*) (Shared + 24697946491); // BR_delta_0__degridding_kernel_supports_degridding_kernel_supports_3_3 > delta_0_g2g_degridgrid_3_degridding_kernel_supports size:= 17*int2
int2 *const g2g_1__gridding_kernel_supports__0 = (int2*) (Shared + 24697946508); // delta_0_Broadcast_gridding_kernel_supports_0_g2g_1 > delta_0_g2g_degridgrid_0_gridding_kernel_supports size:= 17*int2
int2 *const grid_measured_0__kernel_supports__0 = (int2*) (Shared + 6445910675); // delta_0_Broadcast_gridding_kernel_supports_0_grid_measured_0 > delta_0_grid_0_kernel_supports size:= 17*int2
int2 *const g2g_1__gridding_kernel_supports__1 = (int2*) (Shared + 24697946525); // delta_0_Broadcast_gridding_kernel_supports_1_g2g_1 > delta_0_g2g_degridgrid_1_gridding_kernel_supports size:= 17*int2
int2 *const grid_measured_0__kernel_supports__1 = (int2*) (Shared + 6445910692); // delta_0_Broadcast_gridding_kernel_supports_1_grid_measured_0 > delta_0_grid_1_kernel_supports size:= 17*int2
int2 *const g2g_1__gridding_kernel_supports__2 = (int2*) (Shared + 24697946542); // delta_0_Broadcast_gridding_kernel_supports_2_g2g_1 > delta_0_g2g_degridgrid_2_gridding_kernel_supports size:= 17*int2
int2 *const grid_measured_0__kernel_supports__2 = (int2*) (Shared + 6445910709); // delta_0_Broadcast_gridding_kernel_supports_2_grid_measured_0 > delta_0_grid_2_kernel_supports size:= 17*int2
int2 *const g2g_1__gridding_kernel_supports__3 = (int2*) (Shared + 24697946559); // delta_0_Broadcast_gridding_kernel_supports_3_g2g_1 > delta_0_g2g_degridgrid_3_gridding_kernel_supports size:= 17*int2
int2 *const grid_measured_0__kernel_supports__3 = (int2*) (Shared + 6445910726); // delta_0_Broadcast_gridding_kernel_supports_3_grid_measured_0 > delta_0_grid_3_kernel_supports size:= 17*int2
int *const num_vis__input__0 = (int*) (Shared + 5372851238); // delta_0_split_s2s_0_num_vis > delta_0_explode_delta_0_split_s2s_0_num_vis_input size:= 4*int
int *const maj_iter_out__maj_iter__0 = (int*) (Shared + 5372851254); // delta_0_split_s2s_0_maj_iter_out > delta_0_explode_delta_0_split_s2s_0_maj_iter_out_maj_iter size:= 4*int
int *const out__num_sources__0 = (int*) (Shared + 24697946576); // src_3_0_out > delta_0_source_list_sink_0_num_sources size:= 1*int
int *const out__maj_iter__0 = (int*) (Shared + 5372851270);  // src_12_0_out > delta_0_split_s2s_0_maj_iter size:= 1*int
Config *const output_configs__input__0 = (Config*) (Shared + 5372851274); // delta_0_split_s2s_0_output_configs > delta_0_explode_delta_0_split_s2s_0_output_configs_input size:= 4*Config
int *const num_vis_0__input__0 = (int*) (Shared + 5368954400); // delta_0_explode_delta_0_split_s2s_0_num_vis_num_vis_0 > delta_0_Broadcast_num_visibilities_0_input size:= 1*int
int *const num_vis_1__input__0 = (int*) (Shared + 6445910743); // delta_0_explode_delta_0_split_s2s_0_num_vis_num_vis_1 > delta_0_Broadcast_num_visibilities_1_input size:= 1*int
int *const num_vis_2__input__0 = (int*) (Shared + 6445910747); // delta_0_explode_delta_0_split_s2s_0_num_vis_num_vis_2 > delta_0_Broadcast_num_visibilities_2_input size:= 1*int
int *const num_vis_3__input__0 = (int*) (Shared + 6445910751); // delta_0_explode_delta_0_split_s2s_0_num_vis_num_vis_3 > delta_0_Broadcast_num_visibilities_3_input size:= 1*int
int *const maj_iter_out_0__maj_iter__0 = (int*) (Shared + 6445910755); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out_maj_iter_out_0 > delta_0_grid_0_maj_iter size:= 1*int
int *const maj_iter_out_1__maj_iter__0 = (int*) (Shared + 6445910759); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out_maj_iter_out_1 > delta_0_grid_1_maj_iter size:= 1*int
int *const maj_iter_out_2__maj_iter__0 = (int*) (Shared + 6445910763); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out_maj_iter_out_2 > delta_0_grid_2_maj_iter size:= 1*int
int *const maj_iter_out_3__maj_iter__0 = (int*) (Shared + 6445910767); // delta_0_explode_delta_0_split_s2s_0_maj_iter_out_maj_iter_out_3 > delta_0_grid_3_maj_iter size:= 1*int
int *const grid_measurement_0__num_corrected_visibilities__0 = (int*) (Shared + 6445910771); // delta_0_Broadcast_num_visibilities_0_grid_measurement_0 > delta_0_grid_0_num_corrected_visibilities size:= 1*int
int *const g2g_1__num_corrected_visibilities__0 = (int*) (Shared + 24697946580); // delta_0_Broadcast_num_visibilities_0_g2g_1 > delta_0_g2g_degridgrid_0_num_corrected_visibilities size:= 1*int
int *const grid_measurement_0__num_corrected_visibilities__1 = (int*) (Shared + 6445910775); // delta_0_Broadcast_num_visibilities_1_grid_measurement_0 > delta_0_grid_1_num_corrected_visibilities size:= 1*int
int *const g2g_1__num_corrected_visibilities__1 = (int*) (Shared + 24697946584); // delta_0_Broadcast_num_visibilities_1_g2g_1 > delta_0_g2g_degridgrid_1_num_corrected_visibilities size:= 1*int
int *const grid_measurement_0__num_corrected_visibilities__2 = (int*) (Shared + 6445910779); // delta_0_Broadcast_num_visibilities_2_grid_measurement_0 > delta_0_grid_2_num_corrected_visibilities size:= 1*int
int *const g2g_1__num_corrected_visibilities__2 = (int*) (Shared + 24697946588); // delta_0_Broadcast_num_visibilities_2_g2g_1 > delta_0_g2g_degridgrid_2_num_corrected_visibilities size:= 1*int
int *const grid_measurement_0__num_corrected_visibilities__3 = (int*) (Shared + 6445910783); // delta_0_Broadcast_num_visibilities_3_grid_measurement_0 > delta_0_grid_3_num_corrected_visibilities size:= 1*int
int *const g2g_1__num_corrected_visibilities__3 = (int*) (Shared + 24697946592); // delta_0_Broadcast_num_visibilities_3_g2g_1 > delta_0_g2g_degridgrid_3_num_corrected_visibilities size:= 1*int
Config *const out__input__2 = (Config*) (Shared + 2147516416); // src_9_0_out > delta_0_Broadcast_config_0_input size:= 1*Config
Config *const fft_run_0__input__0 = (Config*) (Shared + 2147516417); // delta_0_Broadcast_config_0_fft_run_0 > delta_0_fft_run_0_Broadcast_config_0_input size:= 1*Config
Config *const inverse_fft_run_1__input__0 = (Config*) (Shared + 24697946596); // delta_0_Broadcast_config_0_inverse_fft_run_1 > delta_0_inverse_fft_run_estimation_0_Broadcast_config_0_input size:= 1*Config
Config *const finegrid_2__input__0 = (Config*) (Shared + 5369821568); // delta_0_Broadcast_config_0_finegrid_2 > delta_0_correct_to_finegrid_0_Broadcast_config_0_input size:= 1*Config
Config *const conv_correction_3__config__0 = (Config*) (Shared + 24697946597); // delta_0_Broadcast_config_0_conv_correction_3 > delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0_config size:= 1*Config
Config *const inv_conv_correction_4__config__0 = (Config*) (Shared + 2147516418); // delta_0_Broadcast_config_0_inv_conv_correction_4 > delta_0_inv_conv_correction_0_config size:= 1*Config
Config *const inv_fft_measurements_5__input__0 = (Config*) (Shared + 24697946598); // delta_0_Broadcast_config_0_inv_fft_measurements_5 > delta_0_inverse_fft_run_measurements_0_Broadcast_config_0_input size:= 1*Config
Config *const conv_correction_est_6__config__0 = (Config*) (Shared + 24697946599); // delta_0_Broadcast_config_0_conv_correction_est_6 > delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0_config size:= 1*Config
Config *const split_7__config__0 = (Config*) (Shared + 5372851278); // delta_0_Broadcast_config_0_split_7 > delta_0_split_s2s_0_config size:= 1*Config
Config *const output1_0__config__0 = (Config*) (Shared + 2147516416); // delta_0_fft_run_0_Broadcast_config_0_output1_0 > delta_0_fft_run_0_fft_shift_real_to_complex_actor_0_config size:= 1*Config
Config *const output2_1__config__0 = (Config*) (Shared + 2147516419); // delta_0_fft_run_0_Broadcast_config_0_output2_1 > delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0_config size:= 1*Config
Config *const output1_0__config__1 = (Config*) (Shared + 24697946600); // delta_0_inverse_fft_run_estimation_0_Broadcast_config_0_output1_0 > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0_config size:= 1*Config
Config *const output2_1__config__1 = (Config*) (Shared + 24697946601); // delta_0_inverse_fft_run_estimation_0_Broadcast_config_0_output2_1 > delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0_config size:= 1*Config
Config *const output1_0__config__2 = (Config*) (Shared + 5369822080); // delta_0_correct_to_finegrid_0_Broadcast_config_0_output1_0 > delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0_config size:= 1*Config
Config *const output2_1__config__2 = (Config*) (Shared + 5369822081); // delta_0_correct_to_finegrid_0_Broadcast_config_0_output2_1 > delta_0_correct_to_finegrid_0_apply_gains_0_config size:= 1*Config
Config *const output3_2__config__0 = (Config*) (Shared + 5372851238); // delta_0_correct_to_finegrid_0_Broadcast_config_0_output3_2 > delta_0_correct_to_finegrid_0_correct_to_finegrid_0_config size:= 1*Config
Config *const output1_0__config__3 = (Config*) (Shared + 24697946602); // delta_0_inverse_fft_run_measurements_0_Broadcast_config_0_output1_0 > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0_config size:= 1*Config
Config *const output2_1__config__3 = (Config*) (Shared + 24697946603); // delta_0_inverse_fft_run_measurements_0_Broadcast_config_0_output2_1 > delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0_config size:= 1*Config
Config *const output_configs_0__input__0 = (Config*) (Shared + 5368954404); // delta_0_explode_delta_0_split_s2s_0_output_configs_output_configs_0 > delta_0_Broadcast_configs_0_input size:= 1*Config
Config *const output_configs_1__input__0 = (Config*) (Shared + 6445910787); // delta_0_explode_delta_0_split_s2s_0_output_configs_output_configs_1 > delta_0_Broadcast_configs_1_input size:= 1*Config
Config *const output_configs_2__input__0 = (Config*) (Shared + 6445910788); // delta_0_explode_delta_0_split_s2s_0_output_configs_output_configs_2 > delta_0_Broadcast_configs_2_input size:= 1*Config
Config *const output_configs_3__input__0 = (Config*) (Shared + 6445910789); // delta_0_explode_delta_0_split_s2s_0_output_configs_output_configs_3 > delta_0_Broadcast_configs_3_input size:= 1*Config
Config *const grid_0__config__0 = (Config*) (Shared + 6445910790); // delta_0_Broadcast_configs_0_grid_0 > delta_0_grid_0_config size:= 1*Config
Config *const g2g_1__config__0 = (Config*) (Shared + 24697946604); // delta_0_Broadcast_configs_0_g2g_1 > delta_0_g2g_degridgrid_0_config size:= 1*Config
Config *const grid_0__config__1 = (Config*) (Shared + 6445910791); // delta_0_Broadcast_configs_1_grid_0 > delta_0_grid_1_config size:= 1*Config
Config *const g2g_1__config__1 = (Config*) (Shared + 24697946605); // delta_0_Broadcast_configs_1_g2g_1 > delta_0_g2g_degridgrid_1_config size:= 1*Config
Config *const grid_0__config__2 = (Config*) (Shared + 6445910792); // delta_0_Broadcast_configs_2_grid_0 > delta_0_grid_2_config size:= 1*Config
Config *const g2g_1__config__2 = (Config*) (Shared + 24697946606); // delta_0_Broadcast_configs_2_g2g_1 > delta_0_g2g_degridgrid_2_config size:= 1*Config
Config *const grid_0__config__3 = (Config*) (Shared + 6445910793); // delta_0_Broadcast_configs_3_grid_0 > delta_0_grid_3_config size:= 1*Config
Config *const g2g_1__config__3 = (Config*) (Shared + 24697946607); // delta_0_Broadcast_configs_3_g2g_1 > delta_0_g2g_degridgrid_3_config size:= 1*Config

void* computationThread_Core0(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_out__source_list__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__source_list__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__num_sources__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__num_sources__0);
	PREESM_MD5_CTX preesm_md5_ctx_out__psf__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__psf__0);
	PREESM_MD5_CTX preesm_md5_ctx_output_1__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_output_1__in__0);
	PREESM_MD5_CTX preesm_md5_ctx_result__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_result__in__0);
#endif
// Initialisation(s)

  fifoInit(FIFO_Head_delta_end_out_Broadcast_gridded_measured_prev__d__0, 1073741824, NULL, 0); // 1073741824 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(prev_grid__prev_grid__0, FIFO_Head_delta_end_out_Broadcast_gridded_measured_prev__d__0, 1073741824, NULL,
        0); // 1073741824 * char
    src(out__input__0); // src_0_0

    src(out__psf__0); // src_10_0

    src(out__input__1); // src_11_0

    src(out__maj_iter__0); // src_12_0

    src(out__degridding_kernel_supports__0); // src_13_0

    src(out__degridding_kernels__0); // src_14_0

    src(out__measured_vis__0); // src_1_0

    src(out__source_list__0); // src_2_0

    src(out__num_sources__0); // src_3_0

    src(out__gridding_kernel_supports__0); // src_4_0

    src(out__gridding_kernels__0); // src_5_0

    src(out__vis_uvw_coords__0); // src_6_0

    src(out__gains_in__0); // src_7_0

    src(out__receiver_pairs__0); // src_8_0

    src(out__input__2); // src_9_0

    // Broadcast BR_delta_0__degridding_kernel_supports

    {
      // memcpy #0
      memcpy(degridding_kernel_supports_0_3__degridding_kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0,
          17); // 17 * int2
      // memcpy #0
      memcpy(degridding_kernel_supports_1_3__degridding_kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0,
          17); // 17 * int2
      // memcpy #0
      memcpy(degridding_kernel_supports_2_3__degridding_kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0,
          17); // 17 * int2
      // memcpy #0
      memcpy(degridding_kernel_supports_3_3__degridding_kernel_supports__0 + 0, out__degridding_kernel_supports__0 + 0,
          17); // 17 * int2
    }

    // Broadcast BR_delta_0__degridding_kernels

    {
      // memcpy #0
      memcpy(degridding_kernels_0_3__degridding_kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(degridding_kernels_1_3__degridding_kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(degridding_kernels_2_3__degridding_kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(degridding_kernels_3_3__degridding_kernels__0 + 0, out__degridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast BR_delta_0__gridding_kernel_supports

    {
      // memcpy #0
      memcpy(gridding_kernel_supports_0_3__input__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_1_3__input__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_2_3__input__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(gridding_kernel_supports_3_3__input__0 + 0, out__gridding_kernel_supports__0 + 0, 17); // 17 * int2
    }

    // Broadcast BR_delta_0__gridding_kernels

    {
      // memcpy #0
      memcpy(gridding_kernels_0_3__input__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_1_3__input__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_2_3__input__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(gridding_kernels_3_3__input__0 + 0, out__gridding_kernels__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(fft_run_0__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(inverse_fft_run_1__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(finegrid_2__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(conv_correction_3__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(inv_conv_correction_4__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(inv_fft_measurements_5__input__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(conv_correction_est_6__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(split_7__config__0 + 0, out__input__2 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_prolate_0

    {
      // memcpy #0
      memcpy(inv_conv_correction_0__prolate__0 + 0, out__input__1 + 0, 16384); // 16384 * PRECISION
      // memcpy #0
      memcpy(conv_correction_1__prolate__0 + 0, out__input__1 + 0, 16384); // 16384 * PRECISION
      // memcpy #0
      memcpy(conv_correction_est_2__prolate__0 + 0, out__input__1 + 0, 16384); // 16384 * PRECISION
    }

    source_list_sink(200/*MAX_SOURCES*/, out__source_list__0, out__num_sources__0); // delta_0_source_list_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__source_list__0,(char *)out__source_list__0, 200);
		PREESM_MD5_Update(&preesm_md5_ctx_out__num_sources__0,(char *)out__num_sources__0, 4);
		#endif

    // Broadcast delta_0_Broadcast_gridding_kernel_supports_0

    {
      // memcpy #0
      memcpy(grid_measured_0__kernel_supports__0 + 0, gridding_kernel_supports_0_3__input__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(g2g_1__gridding_kernel_supports__0 + 0, gridding_kernel_supports_0_3__input__0 + 0, 17); // 17 * int2
    }

    // Broadcast delta_0_Broadcast_gridding_kernel_supports_1

    {
      // memcpy #0
      memcpy(grid_measured_0__kernel_supports__1 + 0, gridding_kernel_supports_1_3__input__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(g2g_1__gridding_kernel_supports__1 + 0, gridding_kernel_supports_1_3__input__0 + 0, 17); // 17 * int2
    }

    // Broadcast delta_0_Broadcast_gridding_kernel_supports_2

    {
      // memcpy #0
      memcpy(grid_measured_0__kernel_supports__2 + 0, gridding_kernel_supports_2_3__input__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(g2g_1__gridding_kernel_supports__2 + 0, gridding_kernel_supports_2_3__input__0 + 0, 17); // 17 * int2
    }

    // Broadcast delta_0_Broadcast_gridding_kernel_supports_3

    {
      // memcpy #0
      memcpy(grid_measured_0__kernel_supports__3 + 0, gridding_kernel_supports_3_3__input__0 + 0, 17); // 17 * int2
      // memcpy #0
      memcpy(g2g_1__gridding_kernel_supports__3 + 0, gridding_kernel_supports_3_3__input__0 + 0, 17); // 17 * int2
    }

    // Broadcast delta_0_correct_to_finegrid_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__2 + 0, finegrid_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__2 + 0, finegrid_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output3_2__config__0 + 0, finegrid_2__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_fft_run_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__0 + 0, fft_run_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__0 + 0, fft_run_0__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_inverse_fft_run_estimation_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__1 + 0, inverse_fft_run_1__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__1 + 0, inverse_fft_run_1__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_inverse_fft_run_measurements_0_Broadcast_config_0

    {
      // memcpy #0
      memcpy(output1_0__config__3 + 0, inv_fft_measurements_5__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(output2_1__config__3 + 0, inv_fft_measurements_5__input__0 + 0, 1); // 1 * Config
    }

    reciprocal_transform_actor(512/*NUM_RECEIVERS*/, out__gains_in__0, output1_0__config__2, gains_out__gains__0); // delta_0_correct_to_finegrid_0_reciprocal_transform_actor_0

    // Broadcast delta_0_Broadcast_image_estimate_0

    {
      // memcpy #0
      memcpy(fft_run_0__dirty_image_in__0 + 0, out__input__0 + 0, 1073741824); // 1073741824 * PRECISION
      // memcpy #0
      memcpy(output_1__in__0 + 0, out__input__0 + 0, 1073741824); // 1073741824 * PRECISION
    }

    psf_sink(32768/*GRID_SIZE*/, out__psf__0); // delta_0_psf_sink_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__psf__0,(char *)out__psf__0, 1073741824);
		#endif

    apply_gains_only(512/*NUM_RECEIVERS*/, 130816/*NUM_BASELINES*/, 981120/*NUM_VISIBILITIES*/, out__measured_vis__0,
        gains_out__gains__0, out__receiver_pairs__0, output2_1__config__2, visibilities_out__input_visibilities__0); // delta_0_correct_to_finegrid_0_apply_gains_0

    correct_to_finegrid(981120/*NUM_VISIBILITIES*/, 32768/*GRID_SIZE*/, 16/*OVERSAMPLING_FACTOR*/,
        0/*PERFORM_SIMPLIFICATION*/, out__vis_uvw_coords__0, visibilities_out__input_visibilities__0,
        output3_2__config__0, output_visibilities__measured_visibilities__0, output_finegrid_vis_coords__vis_coords__0,
        num_output_visibilities__num_corrected_vis__0); // delta_0_correct_to_finegrid_0_correct_to_finegrid_0

    split_fftdegrid_visibilities(981120/*NUM_VISIBILITIES*/, 4/*SLICES*/, 32768/*GRID_SIZE*/, split_7__config__0,
        output_finegrid_vis_coords__vis_coords__0, output_visibilities__measured_visibilities__0,
        num_output_visibilities__num_corrected_vis__0, out__maj_iter__0, output_visibilities__visibilities__0,
        out_vis_coords__input__0, output_configs__input__0, num_vis__input__0, maj_iter_out__maj_iter__0); // delta_0_split_s2s_0

    // Fork delta_0_explode_delta_0_split_s2s_0_maj_iter_out

    {
      memcpy(maj_iter_out_0__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 0, 4); // 1 * int
      memcpy(maj_iter_out_1__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 1, 4); // 1 * int
      memcpy(maj_iter_out_2__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 2, 4); // 1 * int
      memcpy(maj_iter_out_3__maj_iter__0 + 0, maj_iter_out__maj_iter__0 + 3, 4); // 1 * int
    }
    // Fork delta_0_explode_delta_0_split_s2s_0_num_vis

    {
      memcpy(num_vis_0__input__0 + 0, num_vis__input__0 + 0, 4); // 1 * int
      memcpy(num_vis_1__input__0 + 0, num_vis__input__0 + 1, 4); // 1 * int
      memcpy(num_vis_2__input__0 + 0, num_vis__input__0 + 2, 4); // 1 * int
      memcpy(num_vis_3__input__0 + 0, num_vis__input__0 + 3, 4); // 1 * int
    }
    // Fork delta_0_explode_delta_0_split_s2s_0_out_vis_coords

    {
      memcpy(out_vis_coords_0__input__0 + 0, out_vis_coords__input__0 + 0, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_1__input__0 + 0, out_vis_coords__input__0 + 245280, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_2__input__0 + 0, out_vis_coords__input__0 + 490560, 245280); // 245280 * PRECISION3
      memcpy(out_vis_coords_3__input__0 + 0, out_vis_coords__input__0 + 735840, 245280); // 245280 * PRECISION3
    }
    // Fork delta_0_explode_delta_0_split_s2s_0_output_configs

    {
      memcpy(output_configs_0__input__0 + 0, output_configs__input__0 + 0, 1); // 1 * Config
      memcpy(output_configs_1__input__0 + 0, output_configs__input__0 + 1, 1); // 1 * Config
      memcpy(output_configs_2__input__0 + 0, output_configs__input__0 + 2, 1); // 1 * Config
      memcpy(output_configs_3__input__0 + 0, output_configs__input__0 + 3, 1); // 1 * Config
    }
    // Fork delta_0_explode_delta_0_split_s2s_0_output_visibilities

    {
      memcpy(output_visibilities_0__visibilities__0 + 0, output_visibilities__visibilities__0 + 0, 245280); // 245280 * PRECISION2
      memcpy(output_visibilities_1__visibilities__0 + 0, output_visibilities__visibilities__0 + 245280, 245280); // 245280 * PRECISION2
      memcpy(output_visibilities_2__visibilities__0 + 0, output_visibilities__visibilities__0 + 490560, 245280); // 245280 * PRECISION2
      memcpy(output_visibilities_3__visibilities__0 + 0, output_visibilities__visibilities__0 + 735840, 245280); // 245280 * PRECISION2
    }
    // Broadcast delta_0_Broadcast_configs_0

    {
      // memcpy #0
      memcpy(grid_0__config__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(g2g_1__config__0 + 0, output_configs_0__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_configs_1

    {
      // memcpy #0
      memcpy(grid_0__config__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(g2g_1__config__1 + 0, output_configs_1__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_configs_2

    {
      // memcpy #0
      memcpy(grid_0__config__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(g2g_1__config__2 + 0, output_configs_2__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_configs_3

    {
      // memcpy #0
      memcpy(grid_0__config__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
      // memcpy #0
      memcpy(g2g_1__config__3 + 0, output_configs_3__input__0 + 0, 1); // 1 * Config
    }

    // Broadcast delta_0_Broadcast_num_visibilities_0

    {
      // memcpy #0
      memcpy(grid_measurement_0__num_corrected_visibilities__0 + 0, num_vis_0__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(g2g_1__num_corrected_visibilities__0 + 0, num_vis_0__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_num_visibilities_1

    {
      // memcpy #0
      memcpy(grid_measurement_0__num_corrected_visibilities__1 + 0, num_vis_1__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(g2g_1__num_corrected_visibilities__1 + 0, num_vis_1__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_num_visibilities_2

    {
      // memcpy #0
      memcpy(grid_measurement_0__num_corrected_visibilities__2 + 0, num_vis_2__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(g2g_1__num_corrected_visibilities__2 + 0, num_vis_2__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_num_visibilities_3

    {
      // memcpy #0
      memcpy(grid_measurement_0__num_corrected_visibilities__3 + 0, num_vis_3__input__0 + 0, 4); // 1 * int
      // memcpy #0
      memcpy(g2g_1__num_corrected_visibilities__3 + 0, num_vis_3__input__0 + 0, 4); // 1 * int
    }

    // Broadcast delta_0_Broadcast_gridding_kernels_0

    {
      // memcpy #0
      memcpy(grid_measured_0__kernels__0 + 0, gridding_kernels_0_3__input__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(g2g_1__gridding_kernels__0 + 0, gridding_kernels_0_3__input__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_gridding_kernels_1

    {
      // memcpy #0
      memcpy(grid_measured_0__kernels__1 + 0, gridding_kernels_1_3__input__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(g2g_1__gridding_kernels__1 + 0, gridding_kernels_1_3__input__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_gridding_kernels_2

    {
      // memcpy #0
      memcpy(grid_measured_0__kernels__2 + 0, gridding_kernels_2_3__input__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(g2g_1__gridding_kernels__2 + 0, gridding_kernels_2_3__input__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_gridding_kernels_3

    {
      // memcpy #0
      memcpy(grid_measured_0__kernels__3 + 0, gridding_kernels_3_3__input__0 + 0, 108800); // 108800 * PRECISION2
      // memcpy #0
      memcpy(g2g_1__gridding_kernels__3 + 0, gridding_kernels_3_3__input__0 + 0, 108800); // 108800 * PRECISION2
    }

    // Broadcast delta_0_Broadcast_corrected_viscoords_0

    {
      // memcpy #0
      memcpy(g2g_0__corrected_vis_uvw_coords__0 + 0, out_vis_coords_0__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_measured_1__corrected_vis_uvw_coords__0 + 0, out_vis_coords_0__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_Broadcast_corrected_viscoords_1

    {
      // memcpy #0
      memcpy(g2g_0__corrected_vis_uvw_coords__1 + 0, out_vis_coords_1__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_measured_1__corrected_vis_uvw_coords__1 + 0, out_vis_coords_1__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_Broadcast_corrected_viscoords_2

    {
      // memcpy #0
      memcpy(g2g_0__corrected_vis_uvw_coords__2 + 0, out_vis_coords_2__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_measured_1__corrected_vis_uvw_coords__2 + 0, out_vis_coords_2__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    // Broadcast delta_0_Broadcast_corrected_viscoords_3

    {
      // memcpy #0
      memcpy(g2g_0__corrected_vis_uvw_coords__3 + 0, out_vis_coords_3__input__0 + 0, 245280); // 245280 * PRECISION3
      // memcpy #0
      memcpy(grid_measured_1__corrected_vis_uvw_coords__3 + 0, out_vis_coords_3__input__0 + 0, 245280); // 245280 * PRECISION3
    }

    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_0__maj_iter__0,
        grid_measurement_0__num_corrected_visibilities__0, grid_measured_0__kernels__0,
        grid_measured_0__kernel_supports__0, grid_measured_1__corrected_vis_uvw_coords__0,
        output_visibilities_0__visibilities__0, grid_0__config__0, prev_grid__prev_grid__0, output_grid__input__0); // delta_0_grid_0

    // Broadcast delta_0_Broadcast_gridded_measured_0

    {
      // memcpy #0
      memcpy(merge_0__grids_0__0 + 0, output_grid__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(prev_1__prev_grid__0 + 0, output_grid__input__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    execute_inv_convolution_correction_actor(32768/*GRID_SIZE*/, fft_run_0__dirty_image_in__0,
        inv_conv_correction_0__prolate__0, inv_conv_correction_4__config__0, dirty_image_out__image__0); // delta_0_inv_conv_correction_0

    sink(output_1__in__0); // sink_1_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_output_1__in__0,(char *)output_1__in__0, 1073741824);
		#endif

    fft_shift_real_to_complex_actor(32768/*GRID_SIZE*/, dirty_image_out__image__0, output1_0__config__0,
        fourier__uv_grid_in__0); // delta_0_fft_run_0_fft_shift_real_to_complex_actor_0

    CUFFT_EXECUTE_FORWARD_C2C_actor(32768/*GRID_SIZE*/, fourier__uv_grid_in__0, uv_grid_out__uv_grid_in__0); // delta_0_fft_run_0_CUFFT_EXECUTE_FORWARD_C2C_actor_0

    fft_shift_complex_to_complex_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid_in__0, output2_1__config__0,
        uv_grid_out__input_grid__0); // delta_0_fft_run_0_fft_shift_complex_to_complex_actor_0

    split_uvgrid(32768/*GRID_SIZE*/, 4/*SLICES*/, uv_grid_out__input_grid__0, output_grid__input_grid__0); // delta_0_split_uvgrid_0

    // Fork delta_0_explode_delta_0_split_uvgrid_0_output_grid

    {
      memcpy(output_grid_0__input_grid__0 + 0, output_grid__input_grid__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid_1__input_grid__0 + 0, output_grid__input_grid__0 + 1073741824, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid_2__input_grid__0 + 0, output_grid__input_grid__0 + 2147483648, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid_3__input_grid__0 + 0, output_grid__input_grid__0 + 3221225472, 1073741824); // 1073741824 * PRECISION2
    }
    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_1__maj_iter__0,
        grid_measurement_0__num_corrected_visibilities__1, grid_measured_0__kernels__1,
        grid_measured_0__kernel_supports__1, grid_measured_1__corrected_vis_uvw_coords__1,
        output_visibilities_1__visibilities__0, grid_0__config__1, prev_1__prev_grid__0, output_grid__input__1); // delta_0_grid_1

    // Broadcast delta_0_Broadcast_gridded_measured_1

    {
      // memcpy #0
      memcpy(merge_0__grids_1__0 + 0, output_grid__input__1 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(prev_1__prev_grid__1 + 0, output_grid__input__1 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_2__maj_iter__0,
        grid_measurement_0__num_corrected_visibilities__2, grid_measured_0__kernels__2,
        grid_measured_0__kernel_supports__2, grid_measured_1__corrected_vis_uvw_coords__2,
        output_visibilities_2__visibilities__0, grid_0__config__2, prev_1__prev_grid__1, output_grid__input__2); // delta_0_grid_2

    // Broadcast delta_0_Broadcast_gridded_measured_2

    {
      // memcpy #0
      memcpy(merge_0__grids_2__0 + 0, output_grid__input__2 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(prev_1__prev_grid__2 + 0, output_grid__input__2 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    g2g_degridgrid(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_GRIDDING_KERNELS*/,
        17/*NUM_DEGRIDDING_KERNELS*/, 108800/*TOTAL_GRIDDING_KERNEL_SAMPLES*/,
        108800/*TOTAL_DEGRIDDING_KERNEL_SAMPLES*/, 16/*OVERSAMPLING_FACTOR*/, g2g_1__gridding_kernels__0,
        g2g_1__gridding_kernel_supports__0, degridding_kernels_0_3__degridding_kernels__0,
        degridding_kernel_supports_0_3__degridding_kernel_supports__0, output_grid_0__input_grid__0,
        g2g_0__corrected_vis_uvw_coords__0, g2g_1__num_corrected_visibilities__0, g2g_1__config__0,
        output_grid__grids_0__0); // delta_0_g2g_degridgrid_0

    g2g_degridgrid(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_GRIDDING_KERNELS*/,
        17/*NUM_DEGRIDDING_KERNELS*/, 108800/*TOTAL_GRIDDING_KERNEL_SAMPLES*/,
        108800/*TOTAL_DEGRIDDING_KERNEL_SAMPLES*/, 16/*OVERSAMPLING_FACTOR*/, g2g_1__gridding_kernels__1,
        g2g_1__gridding_kernel_supports__1, degridding_kernels_1_3__degridding_kernels__0,
        degridding_kernel_supports_1_3__degridding_kernel_supports__0, output_grid_1__input_grid__0,
        g2g_0__corrected_vis_uvw_coords__1, g2g_1__num_corrected_visibilities__1, g2g_1__config__1,
        output_grid__grids_1__0); // delta_0_g2g_degridgrid_1

    g2g_degridgrid(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_GRIDDING_KERNELS*/,
        17/*NUM_DEGRIDDING_KERNELS*/, 108800/*TOTAL_GRIDDING_KERNEL_SAMPLES*/,
        108800/*TOTAL_DEGRIDDING_KERNEL_SAMPLES*/, 16/*OVERSAMPLING_FACTOR*/, g2g_1__gridding_kernels__2,
        g2g_1__gridding_kernel_supports__2, degridding_kernels_2_3__degridding_kernels__0,
        degridding_kernel_supports_2_3__degridding_kernel_supports__0, output_grid_2__input_grid__0,
        g2g_0__corrected_vis_uvw_coords__2, g2g_1__num_corrected_visibilities__2, g2g_1__config__2,
        output_grid__grids_2__0); // delta_0_g2g_degridgrid_2

    g2g_degridgrid(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_GRIDDING_KERNELS*/,
        17/*NUM_DEGRIDDING_KERNELS*/, 108800/*TOTAL_GRIDDING_KERNEL_SAMPLES*/,
        108800/*TOTAL_DEGRIDDING_KERNEL_SAMPLES*/, 16/*OVERSAMPLING_FACTOR*/, g2g_1__gridding_kernels__3,
        g2g_1__gridding_kernel_supports__3, degridding_kernels_3_3__degridding_kernels__0,
        degridding_kernel_supports_3_3__degridding_kernel_supports__0, output_grid_3__input_grid__0,
        g2g_0__corrected_vis_uvw_coords__3, g2g_1__num_corrected_visibilities__3, g2g_1__config__3,
        output_grid__grids_3__0); // delta_0_g2g_degridgrid_3

    // Join delta_0_implode_delta_0_merge_estimate_grid_0_grids

    {
      memcpy(output_grid__grids__0 + 0, output_grid__grids_0__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid__grids__0 + 1073741824, output_grid__grids_1__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid__grids__0 + 2147483648, output_grid__grids_2__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(output_grid__grids__0 + 3221225472, output_grid__grids_3__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }
    std_gridding(32768/*GRID_SIZE*/, 245280/*NUM_VISIBILITIES*/, 17/*NUM_KERNELS*/, 108800/*TOTAL_KERNEL_SAMPLES*/,
        16/*OVERSAMPLING_FACTOR*/, 0/*BYPASS*/, maj_iter_out_3__maj_iter__0,
        grid_measurement_0__num_corrected_visibilities__3, grid_measured_0__kernels__3,
        grid_measured_0__kernel_supports__3, grid_measured_1__corrected_vis_uvw_coords__3,
        output_visibilities_3__visibilities__0, grid_0__config__3, prev_1__prev_grid__2, output_grid__input__3); // delta_0_grid_3

    // Broadcast delta_0_Broadcast_gridded_measured_3

    {
      // memcpy #0
      memcpy(merge_0__grids_3__0 + 0, output_grid__input__3 + 0, 1073741824); // 1073741824 * PRECISION2
      // memcpy #0
      memcpy(prev_1_1__prev_1__0 + 0, output_grid__input__3 + 0, 1073741824); // 1073741824 * PRECISION2
    }

    // Join delta_0_implode_delta_0_merge_measurement_grid_0_grids

    {
      memcpy(merge__grids__0 + 0, merge_0__grids_0__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(merge__grids__0 + 1073741824, merge_0__grids_1__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(merge__grids__0 + 2147483648, merge_0__grids_2__0 + 0, 1073741824); // 1073741824 * PRECISION2
      memcpy(merge__grids__0 + 3221225472, merge_0__grids_3__0 + 0, 1073741824); // 1073741824 * PRECISION2
    }
    fifoPush(prev_1_1__prev_1__0, FIFO_Head_delta_end_out_Broadcast_gridded_measured_prev__d__0, 1073741824, NULL, 0); // 1073741824 * char
    merge_gridded_visibilities(32768/*GRID_SIZE*/, 4/*SLICES*/, output_grid__grids__0, output_grid__uv_grid_in__0); // delta_0_merge_estimate_grid_0

    fft_shift_complex_to_complex_actor(32768/*GRID_SIZE*/, output_grid__uv_grid_in__0, output1_0__config__1,
        uv_grid_out__uv_grid_in__1); // delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_complex_actor_0

    CUFFT_EXECUTE_INVERSE_C2C_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid_in__1, uv_grid_out__uv_grid__0); // delta_0_inverse_fft_run_estimation_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0

    fft_shift_complex_to_real_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid__0, output2_1__config__1,
        dirty_image__dirty_image_in__0); // delta_0_inverse_fft_run_estimation_0_fft_shift_complex_to_real_actor_0

    execute_convolution_correction_actor(32768/*GRID_SIZE*/, dirty_image__dirty_image_in__0,
        conv_correction_est_2__prolate__0, conv_correction_est_6__config__0, dirty_image_out__estimate__0); // delta_0_convolution_correction_run_estimation_0_execute_convolution_correction_actor_0

    merge_gridded_visibilities(32768/*GRID_SIZE*/, 4/*SLICES*/, merge__grids__0, output_grid__uv_grid_in__1); // delta_0_merge_measurement_grid_0

    fft_shift_complex_to_complex_actor(32768/*GRID_SIZE*/, output_grid__uv_grid_in__1, output1_0__config__3,
        uv_grid_out__uv_grid_in__2); // delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_complex_actor_0

    CUFFT_EXECUTE_INVERSE_C2C_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid_in__2, uv_grid_out__uv_grid__1); // delta_0_inverse_fft_run_measurements_0_CUFFT_EXECUTE_INVERSE_C2C_actor_0

    fft_shift_complex_to_real_actor(32768/*GRID_SIZE*/, uv_grid_out__uv_grid__1, output2_1__config__3,
        dirty_image__dirty_image_in__1); // delta_0_inverse_fft_run_measurements_0_fft_shift_complex_to_real_actor_0

    execute_convolution_correction_actor(32768/*GRID_SIZE*/, dirty_image__dirty_image_in__1,
        conv_correction_1__prolate__0, conv_correction_3__config__0, dirty_image_out__measurements__0); // delta_0_convolution_correction_run_0_execute_convolution_correction_actor_0

    subtract_image_space(32768/*GRID_SIZE*/, dirty_image_out__measurements__0, dirty_image_out__estimate__0,
        result__in__0); // delta_0_subtract_image_space_0

    sink(result__in__0); // sink_0_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_result__in__0,(char *)result__in__0, 1073741824);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__source_list__0);
	printf("preesm_md5_out__source_list__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__num_sources__0);
	printf("preesm_md5_out__num_sources__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__psf__0);
	printf("preesm_md5_out__psf__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_output_1__in__0);
	printf("preesm_md5_output_1__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_result__in__0);
	printf("preesm_md5_result__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

